In [217]:
# !pip install tika
# !git clone https://github.com/Atharv-Chaudhari/Project-To-Choose-Perfect-Candidate-Based-on-Resume.git
# !ls Project-To-Choose-Perfect-Candidate-Based-on-Resume/dataset/trainResumes

In [218]:
from tika import parser
import os
import string
import re
import nltk
nltk.download('punkt')
nltk.download("stopwords")
nltk.download('wordnet')
from nltk import pos_tag, word_tokenize, RegexpParser
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [219]:
df = pd.DataFrame(columns = ['CandidateID', 'resume'])
for dirname, _, filenames in os.walk('/content/Project-To-Choose-Perfect-Candidate-Based-on-Resume/dataset/trainResumes'):
    for filename in filenames:
        path = os.path.join(dirname, filename)
        raw = parser.from_file(path)
        df = df.append({'CandidateID' : filename[:-4], 'resume' : " ".join(raw['content'].strip().split('\n')[1:])}, 
                ignore_index = True)
df

      CandidateID                                                                                               resume
0   candidate_007    ISABELLA REED C O N S U L T A N T  A N A L Y S T  SKILLS  Data Science, Machine Learning, Busi...
1   candidate_121    J A D E N  W I L L O W FRESHER INTERN  WORK EXPERIENCE  JumpStart  Intern Trainee, Apr 2020 - ...
2   candidate_015    John Allen B U S I N E S S  A N A L Y S T  Executive Profile  I am a business analytics freshe...
3   candidate_123    Telco  Trainee Intern, May 2018 - Dec 2018   Data Handling for clients and giving them insight...
4   candidate_093    D A L T O N  G R E E N DATA SCIENTIST  WORK EXPERIENCE  United Health Group  Data Scientist Ju...
..            ...                                                                                                  ...
85  candidate_027    GAVING WILSON  P R O F I L E Passionate, motivated and highly conjugated towards  a building m...
86  candidate_149    MIRAD YASTEIN A N A L Y S T  I N T E R N  SKILLS  Artificial Intelligence, Deep Learning, Rein...
87  candidate_089    HELENA PATRICKS F R E S H E R  P Y T H O N  D E V E L O P E R  SKILLS  Data Analysis, Machine ...
88  candidate_063    Joseline Hernandez D A T A  S C I E N T I S T  A N D  M A C H I N E  L E A N R I N G E N G I N...
89  candidate_068    MICHAEL REEVER  F R E S H E R  S O F T W A R E  D E V E L O P E R  PROFESSIONAL PROFILE  Hands...

[90 rows x 2 columns]

In [220]:
df_test = pd.DataFrame(columns = ['CandidateID', 'resume'])
for dirname, _, filenames in os.walk('/content/Project-To-Choose-Perfect-Candidate-Based-on-Resume/dataset/testResumes'):
    for filename in filenames:
        path = os.path.join(dirname, filename)
        raw = parser.from_file(path)
        df_test = df_test.append({'CandidateID' : filename[:-4], 'resume' : " ".join(raw['content'].strip().split('\n')[1:])}, 
                ignore_index = True)
df_test

      CandidateID                                                                                               resume
0   candidate_114    G A R E T T E  P A I G E ASSOCIATE SOFTWARE ENGINEER  WORK EXPERIENCE  Delta Info-nancial Serv...
1   candidate_069    RACHEL DAWN D A T A  S C I E N T I S T  SKILLS  Deep learning, Python, SQL , Keras, PyTorch, P...
2   candidate_028    ASI Technologies  Intern,  Dec 2020 - Ongoing  Working as an intern to learn the usage of Neur...
3   candidate_058    S E B A S T I A N  G O L E R ASSOCIATE DATA MANAGER  WORK EXPERIENCE  iNyra Nursing Home  Asso...
4   candidate_119    Willfred Dixon A S S O C I A T E  D A T A  A N A L Y S T  Executive Profile  Data analyst acti...
5   candidate_107    A N D O R A  M C C O N N E L DATA SCIENTIST  WORK EXPERIENCE  HP  Lead Data Scientist, Feb 202...
6   candidate_108    P R O F I L E  I am a fresher business analyst with a knack for building applications that use...
7   candidate_040    ETHAN GARCIA F R E S H E R  D E V E L O P E R  E N G I N E E R  SKILLS  C++, Python, C, Softwa...
8   candidate_053    PENELOPE TORRES  G R A D U T E  R E S E A R C H  F E L L O W  PROFESSIONAL PROFILE  Passionate...
9   candidate_066    HILDA HAWTHORN  P R O F I L E Associate Software Engineer experienced with data  handling and ...
10  candidate_045    P R O F I L E  Young Aspirant looking for roles in data science , analytics and  Machine Learn...
11  candidate_005    ARMIN FITZGERALD  D A  T  A   M  A  N  A  G  E  R  PROFESSIONAL PROFILE  Expertise in Mathemat...
12  candidate_090    DTSl Software Services  Associate Data Engineer, Jul 2019 - Ongoing   Synthesized current busi...
13  candidate_019    JOSHUA WHITE A S S I S T A N T  S O F T W A R E  A N D  M A C H I N E  L E A R N I N G  E N G ...
14  candidate_122    DIANA MILLER  R E S E A R C H  A S S I S T A N T ( M L )  PROFESSIONAL PROFILE  You can find m...
15  candidate_056    Christian Von Kelin J U N I O R  A N A L Y S T  Executive Profile  As a junior analyst I curre...
16  candidate_048    Absolutdata Research & Analytics  Machine Learning Intern, Jan 2020 to Till Date   Implemented...
17  candidate_004    O L I V I A  S A N T O S CONSULTANT ANALYST  WORK EXPERIENCE  Cognizant, Apr 2020 - Ongoing  C...
18  candidate_118    IRIS GAIDON D A T A  A N A L Y S T  SKILLS  Machine Learning, Data Mining, Artificial Intellig...
19  candidate_059    P R O F I L E  An eclectic researcher , with adept creativity in mobilizing thoughts to  words...
20  candidate_073    P R O F I L E  I am a junior developer currently working as a Machine Learning  Engineer. I ma...
21  candidate_078    DOMINIC NEIWHALD  P R O F I L E Fresher who is dynamic and defined when it comes to  domain kn...
22  candidate_131    ZACHARY PEREZ  P R O F I L E Good knowledge of C++ and OOPS concepts. Good  knowledge of Data ...
23  candidate_031    P R O F I L E  An avid explorer of analytics in multiple facets pertaining to  production indu...
24  candidate_094    P R O F I L E  Graduate Looking for roles related to BU analyst and machine  learning.  CDX IN...
25  candidate_054    SETH HALL D A T A  S C I E N T I S T  A N D  D E V E L O P E R  SKILLS  Data Scientist, Machin...
26  candidate_095    ERIC MILROY  S Y S T E M  E N G I N E E R  A N D  A N A L Y S T  PROFESSIONAL PROFILE  Versati...
27  candidate_084    Robert Sergey F R E SHER  Executive Profile  I recently graduated with a B.Tech degree in IT a...
28  candidate_112    Loyalty Rewards Management. Pvt. Ltd.   Business Analyst, Aug 2020 to Till Date    Administeri...
29  candidate_036    James May F R E S H E R  S O F T W A R E  D E V E L O P E R  E N G I N E E R  Executive Profil...
30  candidate_117    MAX LECLERC  P R O F I L E A Fresher Seeking Roles In Machine Learning, Business  Analysis, Da...
31  candidate_075    KEIRON PAVARD D A T A  E N G I N E E R  SKILLS  Data Engineer, Data Analytics , Data Visualiza...
32  candidate_077    Benett Campbell F R E S H E R  D A T A  A N A L Y S T  Executive Profile  I am fresher data an...
33  candidate_128    B E U L A  S M I T H S O N DATA ANALYST  WORK EXPERIENCE  Graphene health tech Pvt Ltd  BI Eng...
34  candidate_018    EVELYNN ADAMS  G R A D U A T E  F R E S H E R  PROFESSIONAL PROFILE  I am a recent graduate wh...
35  candidate_135    KHOLE MOORE G R A D U A T E  R E S E A R C H E R  SKILLS  Machine Learning Engineer, Data Anal...
36  candidate_126    Asher Hall D A T A  C O N S U L T A N T  Executive Profile  Interested in helping businesses t...
37  candidate_017    P R O F I L E  I am a Junior Machine Learning developer who focuses on data  improvement and m...
38  candidate_146    LEHNA PATRICK  P R O F I L E I  have worked on grassroot level design of data based  models an...
39  candidate_039    NICOLE BREWER  P O S T  G R A D U A T E  B U S I N E S S A N A L Y S T  PROFESSIONAL PROFILE  ...
40  candidate_014    GRACE BAILRY M A C H I N E  L E A R N I N G  D E V E L O P M E N T  A N D  D E P L O Y M E N T...
41  candidate_035    CISCO  Software Developer and Analyst Trainee OCT 2018 - May 2019    Developed Async Functions...
42  candidate_120    P R O F I L E  Completed BSc in STATISTICS from the Mumbai University . Completed data  scienc...
43  candidate_102    TANNER WILLIAMS  S O L U T I O N S  E N G I N E E R  PROFESSIONAL PROFILE  I am currently work...
44  candidate_051    S O P H I A  F L O R E S MACHINE LEARNING DEVELOPER(NLP)  WORK EXPERIENCE  eLevaTe LtD.  Machi...
45  candidate_092    Aya Baker G R A D U A T E  S D E  A N D  B U S I N E S S  A N A L Y S T  Executive Profile  Lo...
46  candidate_091    CASH FLORES  P R O F I L E Machine learning Enthusiast. Motivated to learn, grow and  excel my...
47  candidate_016    A M E L I A  M A R T I N DATA SCIENCE MAJOR  WORK EXPERIENCE  NA  ACADEMIC PROFILE  B.Tech(Com...
48  candidate_125    ETHAN HUNT P Y T H O N  D E V E L O P E R    SKILLS  Django, Python, Relational databases, Res...
49  candidate_099    Edison Anys M A C H I N E  L E A R N I N G  E N G I N E E R  Executive Profile  Machine Learni...
50  candidate_044    L E A H  A T K I N JUNIOR DEVELOPER  WORK EXPERIENCE  TRDDC  Junior Developer, Jan 2019- till ...
51  candidate_141    P R O F I L E  Software developer with a niche towards end to end machine learning projects . ...
52  candidate_139    KEISUKE YAMAMOTO  P R O F I L E Professional with 3 months of experience in Web  Development a...
53  candidate_132    DAVID PHIAST A P P L I C A T I O N  D E V E L O P E R  SKILLS  Deep Learning, Machine Learning...
54  candidate_098    VoyaGenius Labs  Software Developer (ML), Dec 2018 - Ongoing   Geocoding and detecting rooftop...
55  candidate_029    Eli Scott F R E SHER  Executive Profile  Seeking challenging opportunity in the field of data ...
56  candidate_042    Ryan Nelson F R E S H E R  S O F T W A R E  D E V E L O P E R    Executive Profile  I consider...
57  candidate_085    HARRY MILES  P R O F I L E Industrious and collaborative individual, Currently looking  for an...
58  candidate_033    CHARLES RODRIGUEZ S O F T W A R E  A N D  P R O J E C T  M A N A G E R  SKILLS  Natural Langua...
59  candidate_103    TESSA MAERS  P R O F I L E A strategic analyst whose skil l  spans over a vast array of  exper...

In [221]:
df=df.sort_values('CandidateID').reset_index(drop=True)
data=pd.DataFrame()
data=df.copy()
original=df.copy()
final_train=df.copy()
final_train_primary=df.copy()
df

      CandidateID                                                                                               resume
0   candidate_000    JACOB SMITH F R E S H E R  SKILLS  Python, SQL, MySQL, Tableau, Power Bi, Pandas , Numpy, Matp...
1   candidate_001    Brianna Williams J U N I O R  D E V E L O P E R  Executive Profile  A curiosity-driven data sc...
2   candidate_002    AMZ Loans and Mortgages ERC Analytics, Jun 2019 to till date  Handling data of employees and f...
3   candidate_003    P R O F I L E  Extremely motivated to constantly develop my skills and grow  professionally. I...
4   candidate_006    JENNIFER ARMSTRONG  P R O F I L E Fresher Computer vision and Machine Learning  Engineer looki...
..            ...                                                                                                  ...
85  candidate_144    BENJAMIN OSTA  F R E S H E R  D E V E L O P E R  PROFESSIONAL PROFILE  As a fresher I have in ...
86  candidate_145    Coca-COla  Big Data Analyst, Nov 2019 to Till Date   Using the production and shipment data, c...
87  candidate_147    Jaroslav Chechnik F R E SHER  Executive Profile  Looking for a job opportunity in which I can ...
88  candidate_148    P R O F I L E  A data science professional with 1 years of demonstrated work experience in  bu...
89  candidate_149    MIRAD YASTEIN A N A L Y S T  I N T E R N  SKILLS  Artificial Intelligence, Deep Learning, Rein...

[90 rows x 2 columns]

Lets Check For Sample

In [222]:
df['resume'][0]

'  JACOB SMITH F R E S H E R  SKILLS  Python, SQL, MySQL, Tableau, Power Bi, Pandas , Numpy, Matplotlib, Excel , Machine Learning, AWS(EMR,EC2,S3), Cloud, Hive(HQL), and Excel  EDUCATION  B. Tech, ECE VIT-AP University 2020  OTHER ACTIVITIES  Deep Learning Masters Machine Learning  PROJECTS  Music Genre Classification  Face, eye, smile recognition  PERSONAL PROFILE I am actively seeking opportunity as Data Analyst or Machine Learning Engineer.  My goal is to discover new business strategies and create an impact through data driven analytical decisions and leading the business to success.  WORK BACKGROUND  Experts Hub Intern, May 2019  I was part of a team that designed and developed a smart parking system based on Object Recognition.'

In [223]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
for i in range(len(df['resume'])):
  df['resume'][i]=df['resume'][i].lower()
  df['resume'][i]=re.sub(r'\d+', '', df['resume'][i])
  df['resume'][i]=df['resume'][i].translate(str.maketrans("","", string.punctuation))
  df['resume'][i]=df['resume'][i].strip()
  temp=df['resume'][i].split()
  x=[]
  for j in range(len(temp)):
    if(len(temp[j])==1):
      x.append(temp[j])
      temp[j]=""
    elif(len(x)==0 or temp[j]==' '):
      continue
    else:
      temp.append("".join(x))
      x=[]
  df['resume'][i]=' '.join(temp)
  tokens=word_tokenize(df['resume'][i])
  stemmer= PorterStemmer()
  lemmatizer=WordNetLemmatizer()
  df['resume'][i]=[lemmatizer.lemmatize(stemmer.stem(i)) for i in tokens if not i in stop_words]

In [224]:
df

      CandidateID                                                                                               resume
0   candidate_000  [jacob, smith, skill, python, sql, mysql, tableau, power, bi, panda, numpi, matplotlib, excel, m...
1   candidate_001  [brianna, william, execut, profil, curiositydriven, data, scientist, eager, leverag, machin, lea...
2   candidate_002  [amz, loan, mortgag, erc, analyt, jun, till, date, handl, data, employe, find, retent, factor, e...
3   candidate_003  [extrem, motiv, constantli, develop, skill, grow, profession, confid, abil, come, innov, solut, ...
4   candidate_006  [jennif, armstrong, fresher, comput, vision, machin, learn, engin, look, job, challeng, fun, ter...
..            ...                                                                                                  ...
85  candidate_144  [benjamin, osta, profession, profil, fresher, field, softwar, develop, busi, manag, right, searc...
86  candidate_145  [cocacola, big, data, analyst, nov, till, date, use, product, shipment, data, creat, deliveri, m...
87  candidate_147  [jaroslav, chechnik, sher, execut, profil, look, job, opportun, interact, learn, contribut, solu...
88  candidate_148  [data, scienc, profession, year, demonstr, work, experi, build, deploy, endtoend, analyt, solut,...
89  candidate_149  [mirad, yastein, skill, artifici, intellig, deep, learn, reinforc, learn, tensorflow, kera, scik...

[90 rows x 2 columns]

In [225]:
data

      CandidateID                                                                                               resume
0   candidate_000    JACOB SMITH F R E S H E R  SKILLS  Python, SQL, MySQL, Tableau, Power Bi, Pandas , Numpy, Matp...
1   candidate_001    Brianna Williams J U N I O R  D E V E L O P E R  Executive Profile  A curiosity-driven data sc...
2   candidate_002    AMZ Loans and Mortgages ERC Analytics, Jun 2019 to till date  Handling data of employees and f...
3   candidate_003    P R O F I L E  Extremely motivated to constantly develop my skills and grow  professionally. I...
4   candidate_006    JENNIFER ARMSTRONG  P R O F I L E Fresher Computer vision and Machine Learning  Engineer looki...
..            ...                                                                                                  ...
85  candidate_144    BENJAMIN OSTA  F R E S H E R  D E V E L O P E R  PROFESSIONAL PROFILE  As a fresher I have in ...
86  candidate_145    Coca-COla  Big Data Analyst, Nov 2019 to Till Date   Using the production and shipment data, c...
87  candidate_147    Jaroslav Chechnik F R E SHER  Executive Profile  Looking for a job opportunity in which I can ...
88  candidate_148    P R O F I L E  A data science professional with 1 years of demonstrated work experience in  bu...
89  candidate_149    MIRAD YASTEIN A N A L Y S T  I N T E R N  SKILLS  Artificial Intelligence, Deep Learning, Rein...

[90 rows x 2 columns]

In [226]:
data.shape

(90, 2)

In [227]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

Function to remove Punctuation

In [228]:
def remove_punct(text):
    text_nopunct = "".join([char for char in text if char not in string.punctuation])
    temp=text_nopunct.split()
    x=[]
    for j in range(len(temp)):
      if(len(temp[j])==1):
        x.append(temp[j])
        temp[j]=""
      elif(len(x)==0 or temp[j]==' '):
        continue
      else:
        temp.append("".join(x))
        x=[]
    text_nopunct=' '.join(temp)
    return text_nopunct

data['resume_text_clean'] = data['resume'].apply(lambda x: remove_punct(x))

data.head()

     CandidateID  ...                                                                                    resume_text_clean
0  candidate_000  ...  JACOB SMITH        SKILLS Python SQL MySQL Tableau Power Bi Pandas Numpy Matplotlib Excel Machin...
1  candidate_001  ...  Brianna Williams                Executive Profile  curiositydriven data scientist eager to lever...
2  candidate_002  ...  AMZ Loans and Mortgages ERC Analytics Jun 2019 to till date Handling data of employees and findi...
3  candidate_003  ...         Extremely motivated to constantly develop my skills and grow professionally  am confident...
4  candidate_006  ...  JENNIFER ARMSTRONG        Fresher Computer vision and Machine Learning Engineer looking for  job...

[5 rows x 3 columns]

Function to Tokenize words

In [229]:
def tokenize(text):
    tokens = re.split('\W+', text) #W+ means that either a word character (A-Za-z0-9_) or a dash (-) can go there.
    return tokens

data['resume_text_tokenized'] = data['resume_text_clean'].apply(lambda x: tokenize(x.lower())) 
#We convert to lower as Python is case-sensitive. 

data.head()

     CandidateID  ...                                                                                resume_text_tokenized
0  candidate_000  ...  [jacob, smith, skills, python, sql, mysql, tableau, power, bi, pandas, numpy, matplotlib, excel,...
1  candidate_001  ...  [brianna, williams, executive, profile, curiositydriven, data, scientist, eager, to, leverage, m...
2  candidate_002  ...  [amz, loans, and, mortgages, erc, analytics, jun, 2019, to, till, date, handling, data, of, empl...
3  candidate_003  ...  [, extremely, motivated, to, constantly, develop, my, skills, and, grow, professionally, am, con...
4  candidate_006  ...  [jennifer, armstrong, fresher, computer, vision, and, machine, learning, engineer, looking, for,...

[5 rows x 4 columns]

Function to remove Stopwords

In [230]:
stopword = nltk.corpus.stopwords.words('english')# All English Stopwords
def remove_stopwords(tokenized_list):
    text = [word for word in tokenized_list if word not in stopword]# To remove all stopwords
    return text

data['resume_text_nostop'] = data['resume_text_tokenized'].apply(lambda x: remove_stopwords(x))

data.head()

     CandidateID  ...                                                                                   resume_text_nostop
0  candidate_000  ...  [jacob, smith, skills, python, sql, mysql, tableau, power, bi, pandas, numpy, matplotlib, excel,...
1  candidate_001  ...  [brianna, williams, executive, profile, curiositydriven, data, scientist, eager, leverage, machi...
2  candidate_002  ...  [amz, loans, mortgages, erc, analytics, jun, 2019, till, date, handling, data, employees, findin...
3  candidate_003  ...  [, extremely, motivated, constantly, develop, skills, grow, professionally, confident, ability, ...
4  candidate_006  ...  [jennifer, armstrong, fresher, computer, vision, machine, learning, engineer, looking, job, chal...

[5 rows x 5 columns]

Preprocessing Data: Using Stemming

In [231]:
ps = nltk.PorterStemmer()

def stemming(tokenized_text):
    text = [ps.stem(word) for word in tokenized_text]
    return text

data['resume_text_stemmed'] = data['resume_text_nostop'].apply(lambda x: stemming(x))

data.head()

     CandidateID  ...                                                                                  resume_text_stemmed
0  candidate_000  ...  [jacob, smith, skill, python, sql, mysql, tableau, power, bi, panda, numpi, matplotlib, excel, m...
1  candidate_001  ...  [brianna, william, execut, profil, curiositydriven, data, scientist, eager, leverag, machin, lea...
2  candidate_002  ...  [amz, loan, mortgag, erc, analyt, jun, 2019, till, date, handl, data, employe, find, retent, fac...
3  candidate_003  ...  [, extrem, motiv, constantli, develop, skill, grow, profession, confid, abil, come, innov, solut...
4  candidate_006  ...  [jennif, armstrong, fresher, comput, vision, machin, learn, engin, look, job, challeng, fun, ter...

[5 rows x 6 columns]

Preprocessing Data: Using a Lemmatizer

In [232]:
wn = nltk.WordNetLemmatizer()

def lemmatizing(tokenized_text):
    text = [wn.lemmatize(word) for word in tokenized_text]
    return text

data['resume_text_lemmatized'] = data['resume_text_nostop'].apply(lambda x: lemmatizing(x))

data.head(10)

     CandidateID  ...                                                                               resume_text_lemmatized
0  candidate_000  ...  [jacob, smith, skill, python, sql, mysql, tableau, power, bi, panda, numpy, matplotlib, excel, m...
1  candidate_001  ...  [brianna, williams, executive, profile, curiositydriven, data, scientist, eager, leverage, machi...
2  candidate_002  ...  [amz, loan, mortgage, erc, analytics, jun, 2019, till, date, handling, data, employee, finding, ...
3  candidate_003  ...  [, extremely, motivated, constantly, develop, skill, grow, professionally, confident, ability, c...
4  candidate_006  ...  [jennifer, armstrong, fresher, computer, vision, machine, learning, engineer, looking, job, chal...
5  candidate_007  ...  [isabella, reed, skill, data, science, machine, learning, business, analysis, business, analytic...
6  candidate_008  ...  [mia, park, executive, profile, looking, utilize, handson, experience, machine, learning, deep, ...
7  candidate_009  ...  [cutthroat, medium, nlp, analyst, user, comment, jan, 2019feb, 2020, used, various, technique, u...
8  candidate_010  ...  [, started, journey, machine, learning, developer, graduating, college, college, also, worked, r...
9  candidate_011  ...  [, fresher, work, experience, intern, trainee, jan, 2020, apr, 2020, dictis, responsible, perfor...

[10 rows x 7 columns]

In [233]:
train=pd.read_csv("/content/Project-To-Choose-Perfect-Candidate-Based-on-Resume/dataset/train.csv")
train.head()

     CandidateID  Match Percentage
0  candidate_011             13.60
1  candidate_113             36.63
2  candidate_123             54.93
3  candidate_012             41.46
4  candidate_002             48.91

In [234]:
final_train_primary['Match Percentage']=train['Match Percentage']

In [235]:
train.shape

(90, 2)

In [236]:
train=train.sort_values('CandidateID').reset_index(drop=True)
train

      CandidateID  Match Percentage
0   candidate_000             13.70
1   candidate_001             40.09
2   candidate_002             48.91
3   candidate_003             36.89
4   candidate_006             44.96
..            ...               ...
85  candidate_144              6.00
86  candidate_145             47.08
87  candidate_147             11.53
88  candidate_148             60.11
89  candidate_149             41.20

[90 rows x 2 columns]

Function to remove punctuation, tokenize, remove stopwords, and stem

In [237]:
pd.set_option('display.max_colwidth', 100) # To extend column width

stopwords = nltk.corpus.stopwords.words('english')
ps = nltk.PorterStemmer()
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

In [238]:
original.drop(columns=['CandidateID'],inplace=True)

In [239]:
original

                                                                                                 resume
0     JACOB SMITH F R E S H E R  SKILLS  Python, SQL, MySQL, Tableau, Power Bi, Pandas , Numpy, Matp...
1     Brianna Williams J U N I O R  D E V E L O P E R  Executive Profile  A curiosity-driven data sc...
2     AMZ Loans and Mortgages ERC Analytics, Jun 2019 to till date  Handling data of employees and f...
3     P R O F I L E  Extremely motivated to constantly develop my skills and grow  professionally. I...
4     JENNIFER ARMSTRONG  P R O F I L E Fresher Computer vision and Machine Learning  Engineer looki...
..                                                                                                  ...
85    BENJAMIN OSTA  F R E S H E R  D E V E L O P E R  PROFESSIONAL PROFILE  As a fresher I have in ...
86    Coca-COla  Big Data Analyst, Nov 2019 to Till Date   Using the production and shipment data, c...
87    Jaroslav Chechnik F R E SHER  Executive Profile  Looking for a job opportunity in which I can ...
88    P R O F I L E  A data science professional with 1 years of demonstrated work experience in  bu...
89    MIRAD YASTEIN A N A L Y S T  I N T E R N  SKILLS  Artificial Intelligence, Deep Learning, Rein...

[90 rows x 1 columns]

Apply CountVectorizer

In [240]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(analyzer=clean_text)
X_counts = count_vect.fit_transform(original['resume'])
print(X_counts.shape)
print(count_vect.get_feature_names())

(90, 1831)
['', '1', '2', '2015', '2017', '2018', '2019', '20192021', '2019august', '2019feb', '2019nov', '2019oct', '2019till', '2020', '20202021', '2020oct', '2020to', '2021', '5', 'a1', 'abbern', 'abigail', 'abil', 'abl', 'abnorm', 'absolut', 'abul', 'ac', 'academ', 'academi', 'acceler', 'access', 'accord', 'account', 'accumul', 'accur', 'accuraci', 'achiev', 'acquaint', 'acquisit', 'across', 'action', 'activ', 'activit', 'ad', 'adapt', 'address', 'adept', 'administr', 'adob', 'adopt', 'advanc', 'adversari', 'advic', 'advisor', 'affect', 'agil', 'agricultur', 'agro', 'ahmedabad', 'ai', 'aibas', 'aid', 'aiffer', 'aim', 'aiml', 'air', 'alexi', 'algorithm', 'align', 'allen', 'alloc', 'along', 'also', 'alteryx', 'alway', 'amass', 'amaz', 'amazon', 'amber', 'amelia', 'amio', 'amiti', 'among', 'amount', 'amz', 'anaconda', 'analys', 'analysi', 'analyst', 'analyt', 'analyz', 'angularj', 'anim', 'ann', 'anna', 'anomal', 'anomali', 'anova', 'answer', 'anthoni', 'anyth', 'apach', 'api', 'app', 'appli', 'applic', 'approach', 'apr', 'arbitr', 'architect', 'architectur', 'arduino', 'area', 'armstrong', 'around', 'arrest', 'arsen', 'art', 'artifici', 'artistri', 'aset', 'ashley', 'asist', 'asl', 'aspect', 'aspen', 'assembl', 'assess', 'assign', 'assist', 'associ', 'atc', 'attack', 'attend', 'attent', 'attitud', 'attrit', 'attun', 'audienc', 'audrey', 'aug', 'auto', 'autocolor', 'autom', 'automat', 'automot', 'avail', 'averi', 'avid', 'aw', 'award', 'awsemrec2s3', 'axi', 'az', 'azur', 'b', 'ba', 'bachelor', 'background', 'baeconom', 'bailey', 'baker', 'balanc', 'baliyaup', 'band', 'bangalor', 'banhadau', 'bank', 'base', 'basher', 'batch', 'bb', 'bba', 'bca', 'bcom', 'beanstalk', 'beauti', 'beginn', 'behavior', 'belarni', 'belemundi', 'believ', 'belt', 'benefici', 'benefit', 'bengaluru', 'benham', 'benjamin', 'benley', 'bert', 'best', 'bestfit', 'bethani', 'better', 'beuford', 'bgb', 'bhagat', 'bhavleesh', 'bhopal', 'bi', 'bib', 'big', 'bigger', 'bigqueri', 'bill', 'biomed', 'birla', 'birsimb', 'biswa', 'bit', 'bitrat', 'bivari', 'blend', 'block', 'blockchain', 'blood', 'bombay', 'bootstrap', 'bot', 'botassist', 'bottom', 'bound', 'boundari', 'box', 'brainstrom', 'brane', 'braxton', 'breath', 'breed', 'brianna', 'bristlecon', 'brokerag', 'broodi', 'brook', 'brown', 'brows', 'bsc', 'bscca', 'bsi', 'btech', 'btechb', 'btechbiotech', 'btechcivil', 'btechcomput', 'btechcs', 'btechec', 'btechelectr', 'btechelectron', 'btechelectronicstelecommun', 'btechinstrument', 'btechit', 'btechmechan', 'btechmetallurgi', 'bu', 'buffet', 'bug', 'build', 'built', 'burnsley', 'busi', 'c', 'ca', 'calcul', 'calcutta', 'calicut', 'caltech', 'camilla', 'campbel', 'cap', 'capabl', 'caption', 'captur', 'card', 'cardiac', 'care', 'career', 'carli', 'carlton', 'carolin', 'carri', 'case', 'cat', 'catalysi', 'catastroph', 'catboost', 'categor', 'categori', 'caus', 'cb', 'cdn', 'cellular', 'centric', 'ceram', 'certif', 'certifi', 'chadrasekhar', 'chain', 'challeng', 'chand', 'chandra', 'chang', 'charact', 'charan', 'charg', 'chat', 'chatbot', 'chechnik', 'checmic', 'chemic', 'chennai', 'chennal', 'children', 'chosen', 'chrysali', 'chunk', 'ci', 'cit', 'civil', 'claim', 'clark', 'classif', 'classifi', 'clean', 'cleans', 'client', 'clientel', 'clifford', 'close', 'cloud', 'cloudbas', 'cloudmail', 'cloudtest', 'cluster', 'cnn', 'co', 'coalesc', 'coarsegrain', 'cocacola', 'code', 'coerciv', 'cognibot', 'cognit', 'cohes', 'coimbator', 'coleson', 'collabor', 'collect', 'colleg', 'combin', 'come', 'comment', 'commerc', 'commerci', 'commun', 'compani', 'comparison', 'compet', 'complet', 'complex', 'compon', 'composit', 'compound', 'compress', 'comput', 'concept', 'conclud', 'confid', 'conjug', 'connect', 'conner', 'consist', 'constantli', 'construct', 'consult', 'consumpt', 'contain', 'contextu', 'continu', 'contribut', 'control', 'convers', 'convert', 'convey', 'convolut', 'conway', 'coolfactormet', 'cooper', 'coordin', 'core', 'corpor', 'correl', 'correspond', 'cost', 'cotton', 'council', 'cours', 'coursework', 'crash', 'creat', 'creation', 'creativ', 'credit', 'crison', 'crisp', 'criteria', 'critic', 'cron', 'crowd', 'cse', 'csi', 'css', 'cultur', 'cummin', 'curiositydriven', 'currenc', 'current', 'curricular', 'custom', 'customiz', 'cutthroat', 'da', 'damian', 'daniel', 'darjeel', 'dashboard', 'dashboardbas', 'dass', 'data', 'databas', 'databrick', 'datacamp', 'datadriven', 'dataflow', 'dataset', 'date', 'day', 'db', 'dbb', 'dbm', 'dbscan', 'dd', 'dealer', 'debug', 'dec', 'decid', 'decis', 'decisionmak', 'declin', 'dedic', 'deep', 'deeper', 'deeplearningai', 'default', 'defect', 'defin', 'degre', 'delhi', 'deliv', 'deliveri', 'deloitt', 'demand', 'demonstr', 'depend', 'deploy', 'deplyo', 'deputi', 'deriv', 'desark', 'descript', 'design', 'desk', 'detail', 'detect', 'determin', 'develop', 'developermachin', 'developmentrel', 'devic', 'devnagari', 'devop', 'dialogu', 'diametr', 'diaster', 'dicti', 'differ', 'digiscap', 'digit', 'dimension', 'diploma', 'direct', 'disciplin', 'disconfigur', 'discov', 'discoveri', 'diseas', 'display', 'disput', 'dissemin', 'distanc', 'distinct', 'dive', 'divis', 'divvi', 'django', 'djr', 'dkb', 'dl', 'dm', 'docker', 'document', 'domain', 'dome', 'dr', 'dravidian', 'drdo', 'drew', 'drive', 'driven', 'drop', 'drove', 'due', 'duggar', 'durat', 'dynam', 'e', 'eager', 'eagerli', 'earli', 'eas', 'easi', 'easier', 'easili', 'ec2', 'ece', 'econom', 'econometr', 'economist', 'eda', 'edg', 'educ', 'effect', 'elast', 'electr', 'electron', 'electronicstelecommun', 'elli', 'elocution', 'email', 'embed', 'emerg', 'employ', 'employe', 'empow', 'end', 'endto', 'endtoend', 'energi', 'engag', 'engin', 'english', 'enhanc', 'enjoy', 'enlist', 'ensur', 'enterpris', 'entertain', 'enthusiasm', 'enthusiast', 'entir', 'entrepreneurship', 'environ', 'ep', 'erc', 'erp', 'error', 'estim', 'etc', 'ethan', 'etl', 'evalu', 'everett', 'evolv', 'exam', 'excel', 'exchang', 'excit', 'execut', 'exercis', 'exhibit', 'expand', 'expect', 'expenditur', 'experi', 'experienc', 'expert', 'expertis', 'explor', 'exploratori', 'export', 'express', 'extens', 'extern', 'extra', 'extract', 'extracurricular', 'extrem', 'eye', 'f', 'face', 'facilit', 'fact', 'factor', 'factori', 'fake', 'fallout', 'familiar', 'fare', 'fascin', 'fashion', 'fault', 'featur', 'feb', 'feed', 'feedback', 'feel', 'felix', 'fernand', 'fi', 'fiat', 'field', 'figur', 'file', 'filtrat', 'final', 'finalist', 'financ', 'financi', 'find', 'finetun', 'firebas', 'firm', 'fit', 'fix', 'flag', 'flair', 'flask', 'flipkart', 'flow', 'flutter', 'focu', 'focus', 'food', 'foot', 'forecast', 'forest', 'forgeri', 'format', 'formula', 'found', 'foundat', 'fourier', 'framework', 'franchis', 'frank', 'fraud', 'fraudul', 'frequenc', 'fresher', 'front', 'frontend', 'fsx', 'fuel', 'full', 'fulli', 'fulltim', 'fun', 'function', 'funnel', 'futur', 'g', 'game', 'gan', 'gandhi', 'garcia', 'garodia', 'gartner', 'gateway', 'gather', 'gave', 'gcp', 'gdp', 'geakmind', 'gener', 'genr', 'gentl', 'geo', 'gestur', 'get', 'ginanna', 'git', 'give', 'given', 'glacier', 'global', 'glove', 'go', 'goa', 'goal', 'gobind', 'gold', 'gomez', 'good', 'goodman', 'googl', 'goto', 'gover', 'gpt', 'gpt2', 'gpu', 'grade', 'graduat', 'gradut', 'grant', 'granul', 'grape', 'graphic', 'graphml', 'graphql', 'grasp', 'greater', 'greatli', 'green', 'group', 'grow', 'growth', 'gru', 'gruvil', 'guap', 'guid', 'guidanc', 'gujarat', 'guru', 'guwahati', 'h', 'h2oai', 'hadoop', 'half', 'hall', 'hamirpur', 'hand', 'handl', 'handson', 'hansraj', 'hardwar', 'hardwork', 'hayden', 'haydon', 'hayle', 'hcl', 'hdf', 'head', 'health', 'helena', 'help', 'hem', 'heramba', 'hernandez', 'heurist', 'hib', 'high', 'highest', 'highli', 'highvolum', 'himach', 'hisher', 'histori', 'hive', 'hivehql', 'hmi', 'hmm', 'holden', 'home', 'honorari', 'hoogli', 'horan', 'horizon', 'host', 'hotspot', 'hous', 'howard', 'hr', 'hs', 'hsbc', 'html', 'hub', 'huggingfac', 'hyderabad', 'hypothesi', 'i', 'iabac', 'ibb', 'ibm', 'icpc', 'ict', 'id', 'idea', 'ident', 'identif', 'identifi', 'ideolog', 'ifr', 'igenc', 'iiit', 'iit', 'ike', 'imag', 'immedi', 'impact', 'implement', 'import', 'improv', 'in', 'inc', 'incid', 'includ', 'inclus', 'incorpor', 'increas', 'indentifi', 'index', 'india', 'indian', 'indic', 'individu', 'indor', 'indosi', 'industri', 'industrylevel', 'ine', 'infect', 'inform', 'informat', 'informatica', 'infotech', 'infrastructur', 'ingest', 'initi', 'injunct', 'innov', 'input', 'insid', 'insight', 'instal', 'institut', 'instructor', 'instrument', 'insur', 'integr', 'intel', 'intellig', 'interact', 'interest', 'interfac', 'intermedi', 'intermitt', 'intern', 'internship', 'interpret', 'intricaci', 'introduc', 'introduct', 'inventori', 'invest', 'invictu', 'invoic', 'involv', 'iot', 'irrm', 'isabella', 'isi', 'issu', 'iti', 'ize', 'j', 'jacob', 'jade', 'jadodia', 'jagjiban', 'jaim', 'jain', 'jan', 'jaroslav', 'java', 'javascript', 'jayla', 'jdbc', 'jeco', 'jen', 'jenkin', 'jennif', 'jensen', 'jeremi', 'jerom', 'jessica', 'jewelri', 'jimmi', 'jiot', 'jira', 'jjr', 'jkg', 'job', 'john', 'join', 'jona', 'jone', 'jose', 'joselin', 'joseph', 'journey', 'jp', 'jr', 'jt', 'jul', 'juli', 'jumpstart', 'jun', 'junior', 'jupyt', 'jvv', 'k', 'kafka', 'kancheepuram', 'kanchipuram', 'kanpur', 'karnataka', 'kashwant', 'keen', 'keep', 'kelsey', 'kera', 'kerala', 'key', 'keyword', 'kharagpur', 'kibana', 'kind', 'kinsgley', 'klp', 'kmean', 'knack', 'knn', 'knowledg', 'knowledgebas', 'knowntobank', 'kochi', 'kolkata', 'kotlin', 'kottam', 'kpg', 'kpi', 'kpmmc', 'kripa', 'ksst', 'ksv', 'ktb', 'kubeflow', 'kubernet', 'kumar', 'kvoct', 'l', 'lab', 'lambda', 'languag', 'laravel', 'larg', 'larger', 'largescal', 'larsen', 'lasso', 'latent', 'lawn', 'layla', 'lead', 'leadership', 'leaf', 'learn', 'learner', 'led', 'ledger', 'legal', 'level', 'leverag', 'lexicon', 'lexiconbas', 'liaison', 'librari', 'life', 'lifecycl', 'like', 'likelihood', 'limit', 'line', 'linear', 'link', 'linux', 'lisa', 'load', 'loan', 'local', 'locat', 'logic', 'logist', 'look', 'lookout', 'lopez', 'loss', 'lot', 'love', 'loyola', 'ls', 'lstm', 'lt', 'ltd', 'ltt', 'lucen', 'lucknow', 'ludhiana', 'lustr', 'machin', 'maci', 'mackey', 'macro', 'made', 'madelyn', 'madra', 'magicpin', 'maharashtra', 'mahindra', 'main', 'maintain', 'mainten', 'major', 'make', 'malviya', 'mamco', 'manag', 'manageri', 'mangalor', 'manip', 'manipul', 'manufactur', 'map', 'mapper', 'mapreduc', 'mar', 'march', 'marcu', 'mariana', 'market', 'markinov', 'mask', 'maskrcnn', 'mason', 'master', 'match', 'math', 'mathew', 'matilda', 'matlab', 'matplotlib', 'maulana', 'may', 'maya', 'mba', 'mbainform', 'mca', 'meaning', 'mechan', 'medal', 'medalist', 'media', 'medic', 'medica', 'medicin', 'member', 'memori', 'mend', 'mental', 'messag', 'mesto', 'method', 'methodolog', 'meticul', 'metric', 'mia', 'michael', 'microcontrol', 'microsoft', 'miet', 'might', 'mikayla', 'mileston', 'milner', 'mind', 'mine', 'mini', 'minitab', 'mirad', 'mirl', 'mirror', 'ml', 'mlop', 'model', 'modern', 'modul', 'modulesdeliver', 'mohantpur', 'moistur', 'molecul', 'molecular', 'mongodb', 'monitor', 'moor', 'mortgag', 'motiv', 'movi', 'mower', 'mqtt', 'ms', 'msc', 'mscca', 'msccomput', 'mscscienc', 'msexcel', 'msfe', 'mtech', 'mtechdata', 'multi', 'multipl', 'multivari', 'mumbai', 'music', 'mysql', 'n', 'nagpur', 'nane', 'nano', 'nanyang', 'nashik', 'nasik', 'nation', 'natur', 'naxapp', 'nazapp', 'nearli', 'need', 'net', 'network', 'neuer', 'neural', 'new', 'newtobank', 'nichola', 'nielsen', 'nist', 'nit', 'nlp', 'nlpbase', 'nltk', 'node', 'nodej', 'noida', 'nois', 'nolan', 'non', 'nonrepair', 'norm', 'normal', 'nosql', 'nov', 'nptel', 'ntb', 'number', 'numer', 'numpi', 'nyu', 'nyugen', 'object', 'objectdetect', 'ocr', 'oct', 'offer', 'offerproduct', 'offic', 'ondevic', 'one', 'one97', 'ongo', 'onlin', 'onwebsit', 'oop', 'opencv', 'oper', 'opportun', 'optim', 'optimis', 'optimum', 'option', 'oracl', 'orchestr', 'orchidia', 'order', 'organ', 'organiz', 'orient', 'origin', 'orissa', 'osmania', 'osta', 'out', 'outcom', 'outlet', 'outlier', 'outofthebox', 'overal', 'owen', 'owner', 'p', 'paint', 'pan', 'panda', 'paper', 'paragraph', 'paramet', 'park', 'parkar', 'parker', 'part', 'particularli', 'partsmateri', 'parttim', 'passeng', 'passion', 'patch', 'patiala', 'patrick', 'pattern', 'payment', 'pe', 'pelinski', 'peopl', 'perceiv', 'perfect', 'perform', 'period', 'person', 'pg', 'pgg', 'photo', 'php', 'pi', 'pictur', 'pierr', 'pig', 'pillow', 'pipelin', 'pixel', 'plan', 'platform', 'player', 'plot', 'point', 'polaris', 'pollut', 'polymon', 'pondicherri', 'popul', 'portal', 'portfolio', 'posit', 'possess', 'possibl', 'post', 'postanalysi', 'postgresql', 'potenti', 'power', 'powerbi', 'practic', 'practition', 'praxi', 'preapprov', 'predict', 'premium', 'prepar', 'preprocess', 'presal', 'presenc', 'present', 'pretrain', 'previous', 'price', 'primarili', 'princip', 'principl', 'priorit', 'privat', 'prm', 'proactiv', 'probabl', 'problem', 'problemsolv', 'procedur', 'process', 'processflow', 'processor', 'produc', 'product', 'productiongrad', 'profession', 'profici', 'profil', 'profit', 'program', 'programm', 'progress', 'project', 'projeect', 'promis', 'proofofconcept', 'proper', 'propos', 'prototyp', 'proudyogiki', 'prove', 'provid', 'psi', 'public', 'publici', 'pune', 'punjab', 'punjabi', 'purchas', 'purpos', 'pvt', 'pycharm', 'pyimagesearch', 'pyspark', 'pytesseract', 'python', 'pythonsoftwar', 'pytorch', 'quadrado', 'quali', 'qualif', 'qualiti', 'qualityori', 'quantifi', 'quantimum', 'quantit', 'quarter', 'queri', 'question', 'quit', 'quiz', 'quromba', 'r', 'ra', 'radio', 'railway', 'rais', 'raja', 'rajiv', 'ramirez', 'ranchi', 'random', 'rang', 'rao', 'raspberri', 'raster', 'ratio', 'rcc', 'rdbm', 'react', 'reaction', 'readi', 'real', 'reallif', 'realtim', 'realworld', 'reason', 'recent', 'recognit', 'recommend', 'record', 'redact', 'redshift', 'reduc', 'reed', 'reever', 'refin', 'registr', 'regonit', 'regress', 'reinforc', 'reinsur', 'relat', 'relay', 'relev', 'reli', 'reliabil', 'remark', 'remiro', 'remot', 'remov', 'report', 'represent', 'request', 'requir', 'research', 'residu', 'resourc', 'respect', 'respons', 'responsibil', 'restapi', 'result', 'retail', 'retent', 'retrain', 'return', 'revolv', 'reward', 'rfi', 'rfp', 'rfq', 'rgpv', 'rich', 'rider', 'ridg', 'right', 'risk', 'riskmodel', 'rm', 'rnn', 'robert', 'robot', 'robust', 'rodney', 'roger', 'role', 'root', 'rossier', 'rout', 'rshini', 'rtoreturn', 'rubi', 'runner', 'runnerup', 's2h', 'sa', 'sadar', 'sadhana', 'sagemak', 'sahara', 'sai', 'saiko', 'sale', 'sampl', 'sanrachna', 'sap', 'sapient', 'satellit', 'satisfact', 'scala', 'scalabl', 'scale', 'scall', 'scarlett', 'scenario', 'scholar', 'school', 'scienc', 'scientist', 'scientistanalyt', 'scikit', 'scikitlearn', 'scorecard', 'scrap', 'script', 'scriptur', 'sde', 'sdedata', 'sdemachin', 'seaborn', 'seamless', 'sean', 'search', 'secondari', 'sector', 'seek', 'segment', 'select', 'selenium', 'semant', 'sens', 'sensor', 'sentenc', 'sentiment', 'sep', 'separ', 'sequenti', 'seri', 'serv', 'server', 'servic', 'set', 'setup', 'sever', 'sgbau', 'sgt', 'shahe', 'sharp', 'shaw', 'shawn', 'sher', 'shipment', 'shiv', 'shock', 'shop', 'show', 'shown', 'shri', 'side', 'signal', 'signific', 'sikkim', 'silver', 'similar', 'simpl', 'simplifi', 'sinc', 'singh', 'singhji', 'site', 'sixsigma', 'sju', 'sk', 'skil', 'skill', 'skillset', 'skin', 'sklearn', 'skn', 'sl', 'sla', 'small', 'smart', 'sme', 'smile', 'smith', 'snake', 'softwar', 'soil', 'solinov', 'solut', 'solv', 'someon', 'son', 'song', 'sota', 'soup', 'sourc', 'sp', 'spaci', 'spark', 'sparkpyspark', 'special', 'specialist', 'specially', 'speech', 'speechbas', 'sppu', 'springboot', 'spss', 'sql', 'srm', 'srmu', 'ssgm', 'st', 'stabil', 'stacey', 'stage', 'stakehold', 'standard', 'stanford', 'star', 'start', 'stateoftheart', 'statist', 'stc', 'ste', 'steam', 'steer', 'stella', 'sten', 'step', 'stock', 'storag', 'store', 'strateg', 'strategi', 'streamlit', 'strive', 'strong', 'structur', 'student', 'studi', 'studio', 'subhash', 'subspac', 'success', 'suitabl', 'summar', 'summari', 'summer', 'supervis', 'suppli', 'support', 'sure', 'survey', 'svm', 'switch', 'sydney', 'symmetr', 'synthesi', 'system', 'systemica', 'tableau', 'tag', 'take', 'talend', 'tanisha', 'target', 'task', 'tata', 'taxi', 'taylor', 'teach', 'team', 'teamwork', 'tech', 'technic', 'techniqu', 'technolog', 'technologyagnost', 'technologyrourkela', 'technosci', 'telco', 'telecommun', 'telemetri', 'templat', 'tensorflow', 'tenur', 'term', 'test', 'tester', 'text', 'textual', 'thakur', 'thala', 'thatcher', 'therefor', 'thesi', 'think', 'though', 'throttl', 'throughout', 'thu', 'ti', 'ticket', 'til', 'till', 'time', 'timeli', 'titl', 'titli', 'tml', 'tone', 'took', 'tool', 'top', 'topic', 'toubro', 'tour', 'toward', 'toxic', 'track', 'tractor', 'train', 'traine', 'traintest', 'transact', 'transfer', 'transform', 'transit', 'translat', 'transmiss', 'transport', 'travel', 'treatment', 'tree', 'trend', 'tri', 'troubleshoot', 'tsc', 'tune', 'turn', 'turnov', 'type', 'u', 'udac', 'ui', 'uiux', 'undergradu', 'underneath', 'understand', 'undertaken', 'unifi', 'uniform', 'unit', 'univari', 'univers', 'unix', 'unstruct', 'unstructur', 'unsupervis', 'upcom', 'updat', 'upi', 'us', 'usag', 'use', 'user', 'uti', 'util', 'utilis', 'uttaranch', 'v', 'vagu', 'valid', 'vari', 'varianc', 'variou', 'vector', 'vehicl', 'vellor', 'vendor', 'ventur', 'verifi', 'versa', 'vgg16', 'vice', 'video', 'view', 'virtual', 'vishwavidyalaya', 'vision', 'visual', 'visualis', 'visveswaraiah', 'vit', 'vitap', 'vizon', 'voic', 'volum', 'volvo', 'vtu', 'vvit', 'w', 'wang', 'want', 'wareh', 'warehous', 'warehousepl', 'wast', 'waterloo', 'way', 'weather', 'web', 'webbas', 'webpag', 'websit', 'weight', 'well', 'wellarm', 'wesbit', 'what', 'whole', 'william', 'wilson', 'winner', 'winston', 'within', 'without', 'word', 'wordcloud', 'work', 'workflow', 'workshop', 'world', 'would', 'wrangl', 'wrt', 'wtpl', 'wyatt', 'x', 'xcelsior', 'xgboost', 'xlnet', 'xml', 'yarn', 'yastein', 'year', 'yolo', 'young', 'younger', 'z', 'zoombot', 'zynta']

In [241]:
X_counts_df = pd.DataFrame(X_counts.toarray(), columns=count_vect.get_feature_names())
X_counts_df.head(10)

      1  2  2015  2017  2018  ...  yolo  young  younger  z  zoombot  zynta
0  1  0  0     0     0     0  ...     0      0        0  0        0      0
1  1  0  0     0     0     1  ...     0      0        0  0        0      0
2  1  0  0     0     0     0  ...     0      0        0  0        0      0
3  1  0  0     0     0     2  ...     0      0        0  0        0      0
4  1  0  0     0     0     0  ...     0      0        0  0        0      0
5  1  0  0     0     0     1  ...     0      0        0  0        0      0
6  1  0  0     0     0     0  ...     0      0        0  0        0      0
7  1  0  0     0     0     0  ...     0      0        0  0        0      0
8  1  0  0     0     0     1  ...     0      0        0  0        0      0
9  1  0  0     0     0     0  ...     0      0        0  0        0      0

[10 rows x 1831 columns]

Vectorizing Raw Data: N-Grams

Apply CountVectorizer (N-Grams)

In [242]:
from sklearn.feature_extraction.text import CountVectorizer

ngram_vect = CountVectorizer(ngram_range=(2,2),analyzer=clean_text) # It applies only bigram vectorizer
X_counts = ngram_vect.fit_transform(original['resume'])
print(X_counts.shape)
print(ngram_vect.get_feature_names())

(90, 1831)
['', '1', '2', '2015', '2017', '2018', '2019', '20192021', '2019august', '2019feb', '2019nov', '2019oct', '2019till', '2020', '20202021', '2020oct', '2020to', '2021', '5', 'a1', 'abbern', 'abigail', 'abil', 'abl', 'abnorm', 'absolut', 'abul', 'ac', 'academ', 'academi', 'acceler', 'access', 'accord', 'account', 'accumul', 'accur', 'accuraci', 'achiev', 'acquaint', 'acquisit', 'across', 'action', 'activ', 'activit', 'ad', 'adapt', 'address', 'adept', 'administr', 'adob', 'adopt', 'advanc', 'adversari', 'advic', 'advisor', 'affect', 'agil', 'agricultur', 'agro', 'ahmedabad', 'ai', 'aibas', 'aid', 'aiffer', 'aim', 'aiml', 'air', 'alexi', 'algorithm', 'align', 'allen', 'alloc', 'along', 'also', 'alteryx', 'alway', 'amass', 'amaz', 'amazon', 'amber', 'amelia', 'amio', 'amiti', 'among', 'amount', 'amz', 'anaconda', 'analys', 'analysi', 'analyst', 'analyt', 'analyz', 'angularj', 'anim', 'ann', 'anna', 'anomal', 'anomali', 'anova', 'answer', 'anthoni', 'anyth', 'apach', 'api', 'app', 'appli', 'applic', 'approach', 'apr', 'arbitr', 'architect', 'architectur', 'arduino', 'area', 'armstrong', 'around', 'arrest', 'arsen', 'art', 'artifici', 'artistri', 'aset', 'ashley', 'asist', 'asl', 'aspect', 'aspen', 'assembl', 'assess', 'assign', 'assist', 'associ', 'atc', 'attack', 'attend', 'attent', 'attitud', 'attrit', 'attun', 'audienc', 'audrey', 'aug', 'auto', 'autocolor', 'autom', 'automat', 'automot', 'avail', 'averi', 'avid', 'aw', 'award', 'awsemrec2s3', 'axi', 'az', 'azur', 'b', 'ba', 'bachelor', 'background', 'baeconom', 'bailey', 'baker', 'balanc', 'baliyaup', 'band', 'bangalor', 'banhadau', 'bank', 'base', 'basher', 'batch', 'bb', 'bba', 'bca', 'bcom', 'beanstalk', 'beauti', 'beginn', 'behavior', 'belarni', 'belemundi', 'believ', 'belt', 'benefici', 'benefit', 'bengaluru', 'benham', 'benjamin', 'benley', 'bert', 'best', 'bestfit', 'bethani', 'better', 'beuford', 'bgb', 'bhagat', 'bhavleesh', 'bhopal', 'bi', 'bib', 'big', 'bigger', 'bigqueri', 'bill', 'biomed', 'birla', 'birsimb', 'biswa', 'bit', 'bitrat', 'bivari', 'blend', 'block', 'blockchain', 'blood', 'bombay', 'bootstrap', 'bot', 'botassist', 'bottom', 'bound', 'boundari', 'box', 'brainstrom', 'brane', 'braxton', 'breath', 'breed', 'brianna', 'bristlecon', 'brokerag', 'broodi', 'brook', 'brown', 'brows', 'bsc', 'bscca', 'bsi', 'btech', 'btechb', 'btechbiotech', 'btechcivil', 'btechcomput', 'btechcs', 'btechec', 'btechelectr', 'btechelectron', 'btechelectronicstelecommun', 'btechinstrument', 'btechit', 'btechmechan', 'btechmetallurgi', 'bu', 'buffet', 'bug', 'build', 'built', 'burnsley', 'busi', 'c', 'ca', 'calcul', 'calcutta', 'calicut', 'caltech', 'camilla', 'campbel', 'cap', 'capabl', 'caption', 'captur', 'card', 'cardiac', 'care', 'career', 'carli', 'carlton', 'carolin', 'carri', 'case', 'cat', 'catalysi', 'catastroph', 'catboost', 'categor', 'categori', 'caus', 'cb', 'cdn', 'cellular', 'centric', 'ceram', 'certif', 'certifi', 'chadrasekhar', 'chain', 'challeng', 'chand', 'chandra', 'chang', 'charact', 'charan', 'charg', 'chat', 'chatbot', 'chechnik', 'checmic', 'chemic', 'chennai', 'chennal', 'children', 'chosen', 'chrysali', 'chunk', 'ci', 'cit', 'civil', 'claim', 'clark', 'classif', 'classifi', 'clean', 'cleans', 'client', 'clientel', 'clifford', 'close', 'cloud', 'cloudbas', 'cloudmail', 'cloudtest', 'cluster', 'cnn', 'co', 'coalesc', 'coarsegrain', 'cocacola', 'code', 'coerciv', 'cognibot', 'cognit', 'cohes', 'coimbator', 'coleson', 'collabor', 'collect', 'colleg', 'combin', 'come', 'comment', 'commerc', 'commerci', 'commun', 'compani', 'comparison', 'compet', 'complet', 'complex', 'compon', 'composit', 'compound', 'compress', 'comput', 'concept', 'conclud', 'confid', 'conjug', 'connect', 'conner', 'consist', 'constantli', 'construct', 'consult', 'consumpt', 'contain', 'contextu', 'continu', 'contribut', 'control', 'convers', 'convert', 'convey', 'convolut', 'conway', 'coolfactormet', 'cooper', 'coordin', 'core', 'corpor', 'correl', 'correspond', 'cost', 'cotton', 'council', 'cours', 'coursework', 'crash', 'creat', 'creation', 'creativ', 'credit', 'crison', 'crisp', 'criteria', 'critic', 'cron', 'crowd', 'cse', 'csi', 'css', 'cultur', 'cummin', 'curiositydriven', 'currenc', 'current', 'curricular', 'custom', 'customiz', 'cutthroat', 'da', 'damian', 'daniel', 'darjeel', 'dashboard', 'dashboardbas', 'dass', 'data', 'databas', 'databrick', 'datacamp', 'datadriven', 'dataflow', 'dataset', 'date', 'day', 'db', 'dbb', 'dbm', 'dbscan', 'dd', 'dealer', 'debug', 'dec', 'decid', 'decis', 'decisionmak', 'declin', 'dedic', 'deep', 'deeper', 'deeplearningai', 'default', 'defect', 'defin', 'degre', 'delhi', 'deliv', 'deliveri', 'deloitt', 'demand', 'demonstr', 'depend', 'deploy', 'deplyo', 'deputi', 'deriv', 'desark', 'descript', 'design', 'desk', 'detail', 'detect', 'determin', 'develop', 'developermachin', 'developmentrel', 'devic', 'devnagari', 'devop', 'dialogu', 'diametr', 'diaster', 'dicti', 'differ', 'digiscap', 'digit', 'dimension', 'diploma', 'direct', 'disciplin', 'disconfigur', 'discov', 'discoveri', 'diseas', 'display', 'disput', 'dissemin', 'distanc', 'distinct', 'dive', 'divis', 'divvi', 'django', 'djr', 'dkb', 'dl', 'dm', 'docker', 'document', 'domain', 'dome', 'dr', 'dravidian', 'drdo', 'drew', 'drive', 'driven', 'drop', 'drove', 'due', 'duggar', 'durat', 'dynam', 'e', 'eager', 'eagerli', 'earli', 'eas', 'easi', 'easier', 'easili', 'ec2', 'ece', 'econom', 'econometr', 'economist', 'eda', 'edg', 'educ', 'effect', 'elast', 'electr', 'electron', 'electronicstelecommun', 'elli', 'elocution', 'email', 'embed', 'emerg', 'employ', 'employe', 'empow', 'end', 'endto', 'endtoend', 'energi', 'engag', 'engin', 'english', 'enhanc', 'enjoy', 'enlist', 'ensur', 'enterpris', 'entertain', 'enthusiasm', 'enthusiast', 'entir', 'entrepreneurship', 'environ', 'ep', 'erc', 'erp', 'error', 'estim', 'etc', 'ethan', 'etl', 'evalu', 'everett', 'evolv', 'exam', 'excel', 'exchang', 'excit', 'execut', 'exercis', 'exhibit', 'expand', 'expect', 'expenditur', 'experi', 'experienc', 'expert', 'expertis', 'explor', 'exploratori', 'export', 'express', 'extens', 'extern', 'extra', 'extract', 'extracurricular', 'extrem', 'eye', 'f', 'face', 'facilit', 'fact', 'factor', 'factori', 'fake', 'fallout', 'familiar', 'fare', 'fascin', 'fashion', 'fault', 'featur', 'feb', 'feed', 'feedback', 'feel', 'felix', 'fernand', 'fi', 'fiat', 'field', 'figur', 'file', 'filtrat', 'final', 'finalist', 'financ', 'financi', 'find', 'finetun', 'firebas', 'firm', 'fit', 'fix', 'flag', 'flair', 'flask', 'flipkart', 'flow', 'flutter', 'focu', 'focus', 'food', 'foot', 'forecast', 'forest', 'forgeri', 'format', 'formula', 'found', 'foundat', 'fourier', 'framework', 'franchis', 'frank', 'fraud', 'fraudul', 'frequenc', 'fresher', 'front', 'frontend', 'fsx', 'fuel', 'full', 'fulli', 'fulltim', 'fun', 'function', 'funnel', 'futur', 'g', 'game', 'gan', 'gandhi', 'garcia', 'garodia', 'gartner', 'gateway', 'gather', 'gave', 'gcp', 'gdp', 'geakmind', 'gener', 'genr', 'gentl', 'geo', 'gestur', 'get', 'ginanna', 'git', 'give', 'given', 'glacier', 'global', 'glove', 'go', 'goa', 'goal', 'gobind', 'gold', 'gomez', 'good', 'goodman', 'googl', 'goto', 'gover', 'gpt', 'gpt2', 'gpu', 'grade', 'graduat', 'gradut', 'grant', 'granul', 'grape', 'graphic', 'graphml', 'graphql', 'grasp', 'greater', 'greatli', 'green', 'group', 'grow', 'growth', 'gru', 'gruvil', 'guap', 'guid', 'guidanc', 'gujarat', 'guru', 'guwahati', 'h', 'h2oai', 'hadoop', 'half', 'hall', 'hamirpur', 'hand', 'handl', 'handson', 'hansraj', 'hardwar', 'hardwork', 'hayden', 'haydon', 'hayle', 'hcl', 'hdf', 'head', 'health', 'helena', 'help', 'hem', 'heramba', 'hernandez', 'heurist', 'hib', 'high', 'highest', 'highli', 'highvolum', 'himach', 'hisher', 'histori', 'hive', 'hivehql', 'hmi', 'hmm', 'holden', 'home', 'honorari', 'hoogli', 'horan', 'horizon', 'host', 'hotspot', 'hous', 'howard', 'hr', 'hs', 'hsbc', 'html', 'hub', 'huggingfac', 'hyderabad', 'hypothesi', 'i', 'iabac', 'ibb', 'ibm', 'icpc', 'ict', 'id', 'idea', 'ident', 'identif', 'identifi', 'ideolog', 'ifr', 'igenc', 'iiit', 'iit', 'ike', 'imag', 'immedi', 'impact', 'implement', 'import', 'improv', 'in', 'inc', 'incid', 'includ', 'inclus', 'incorpor', 'increas', 'indentifi', 'index', 'india', 'indian', 'indic', 'individu', 'indor', 'indosi', 'industri', 'industrylevel', 'ine', 'infect', 'inform', 'informat', 'informatica', 'infotech', 'infrastructur', 'ingest', 'initi', 'injunct', 'innov', 'input', 'insid', 'insight', 'instal', 'institut', 'instructor', 'instrument', 'insur', 'integr', 'intel', 'intellig', 'interact', 'interest', 'interfac', 'intermedi', 'intermitt', 'intern', 'internship', 'interpret', 'intricaci', 'introduc', 'introduct', 'inventori', 'invest', 'invictu', 'invoic', 'involv', 'iot', 'irrm', 'isabella', 'isi', 'issu', 'iti', 'ize', 'j', 'jacob', 'jade', 'jadodia', 'jagjiban', 'jaim', 'jain', 'jan', 'jaroslav', 'java', 'javascript', 'jayla', 'jdbc', 'jeco', 'jen', 'jenkin', 'jennif', 'jensen', 'jeremi', 'jerom', 'jessica', 'jewelri', 'jimmi', 'jiot', 'jira', 'jjr', 'jkg', 'job', 'john', 'join', 'jona', 'jone', 'jose', 'joselin', 'joseph', 'journey', 'jp', 'jr', 'jt', 'jul', 'juli', 'jumpstart', 'jun', 'junior', 'jupyt', 'jvv', 'k', 'kafka', 'kancheepuram', 'kanchipuram', 'kanpur', 'karnataka', 'kashwant', 'keen', 'keep', 'kelsey', 'kera', 'kerala', 'key', 'keyword', 'kharagpur', 'kibana', 'kind', 'kinsgley', 'klp', 'kmean', 'knack', 'knn', 'knowledg', 'knowledgebas', 'knowntobank', 'kochi', 'kolkata', 'kotlin', 'kottam', 'kpg', 'kpi', 'kpmmc', 'kripa', 'ksst', 'ksv', 'ktb', 'kubeflow', 'kubernet', 'kumar', 'kvoct', 'l', 'lab', 'lambda', 'languag', 'laravel', 'larg', 'larger', 'largescal', 'larsen', 'lasso', 'latent', 'lawn', 'layla', 'lead', 'leadership', 'leaf', 'learn', 'learner', 'led', 'ledger', 'legal', 'level', 'leverag', 'lexicon', 'lexiconbas', 'liaison', 'librari', 'life', 'lifecycl', 'like', 'likelihood', 'limit', 'line', 'linear', 'link', 'linux', 'lisa', 'load', 'loan', 'local', 'locat', 'logic', 'logist', 'look', 'lookout', 'lopez', 'loss', 'lot', 'love', 'loyola', 'ls', 'lstm', 'lt', 'ltd', 'ltt', 'lucen', 'lucknow', 'ludhiana', 'lustr', 'machin', 'maci', 'mackey', 'macro', 'made', 'madelyn', 'madra', 'magicpin', 'maharashtra', 'mahindra', 'main', 'maintain', 'mainten', 'major', 'make', 'malviya', 'mamco', 'manag', 'manageri', 'mangalor', 'manip', 'manipul', 'manufactur', 'map', 'mapper', 'mapreduc', 'mar', 'march', 'marcu', 'mariana', 'market', 'markinov', 'mask', 'maskrcnn', 'mason', 'master', 'match', 'math', 'mathew', 'matilda', 'matlab', 'matplotlib', 'maulana', 'may', 'maya', 'mba', 'mbainform', 'mca', 'meaning', 'mechan', 'medal', 'medalist', 'media', 'medic', 'medica', 'medicin', 'member', 'memori', 'mend', 'mental', 'messag', 'mesto', 'method', 'methodolog', 'meticul', 'metric', 'mia', 'michael', 'microcontrol', 'microsoft', 'miet', 'might', 'mikayla', 'mileston', 'milner', 'mind', 'mine', 'mini', 'minitab', 'mirad', 'mirl', 'mirror', 'ml', 'mlop', 'model', 'modern', 'modul', 'modulesdeliver', 'mohantpur', 'moistur', 'molecul', 'molecular', 'mongodb', 'monitor', 'moor', 'mortgag', 'motiv', 'movi', 'mower', 'mqtt', 'ms', 'msc', 'mscca', 'msccomput', 'mscscienc', 'msexcel', 'msfe', 'mtech', 'mtechdata', 'multi', 'multipl', 'multivari', 'mumbai', 'music', 'mysql', 'n', 'nagpur', 'nane', 'nano', 'nanyang', 'nashik', 'nasik', 'nation', 'natur', 'naxapp', 'nazapp', 'nearli', 'need', 'net', 'network', 'neuer', 'neural', 'new', 'newtobank', 'nichola', 'nielsen', 'nist', 'nit', 'nlp', 'nlpbase', 'nltk', 'node', 'nodej', 'noida', 'nois', 'nolan', 'non', 'nonrepair', 'norm', 'normal', 'nosql', 'nov', 'nptel', 'ntb', 'number', 'numer', 'numpi', 'nyu', 'nyugen', 'object', 'objectdetect', 'ocr', 'oct', 'offer', 'offerproduct', 'offic', 'ondevic', 'one', 'one97', 'ongo', 'onlin', 'onwebsit', 'oop', 'opencv', 'oper', 'opportun', 'optim', 'optimis', 'optimum', 'option', 'oracl', 'orchestr', 'orchidia', 'order', 'organ', 'organiz', 'orient', 'origin', 'orissa', 'osmania', 'osta', 'out', 'outcom', 'outlet', 'outlier', 'outofthebox', 'overal', 'owen', 'owner', 'p', 'paint', 'pan', 'panda', 'paper', 'paragraph', 'paramet', 'park', 'parkar', 'parker', 'part', 'particularli', 'partsmateri', 'parttim', 'passeng', 'passion', 'patch', 'patiala', 'patrick', 'pattern', 'payment', 'pe', 'pelinski', 'peopl', 'perceiv', 'perfect', 'perform', 'period', 'person', 'pg', 'pgg', 'photo', 'php', 'pi', 'pictur', 'pierr', 'pig', 'pillow', 'pipelin', 'pixel', 'plan', 'platform', 'player', 'plot', 'point', 'polaris', 'pollut', 'polymon', 'pondicherri', 'popul', 'portal', 'portfolio', 'posit', 'possess', 'possibl', 'post', 'postanalysi', 'postgresql', 'potenti', 'power', 'powerbi', 'practic', 'practition', 'praxi', 'preapprov', 'predict', 'premium', 'prepar', 'preprocess', 'presal', 'presenc', 'present', 'pretrain', 'previous', 'price', 'primarili', 'princip', 'principl', 'priorit', 'privat', 'prm', 'proactiv', 'probabl', 'problem', 'problemsolv', 'procedur', 'process', 'processflow', 'processor', 'produc', 'product', 'productiongrad', 'profession', 'profici', 'profil', 'profit', 'program', 'programm', 'progress', 'project', 'projeect', 'promis', 'proofofconcept', 'proper', 'propos', 'prototyp', 'proudyogiki', 'prove', 'provid', 'psi', 'public', 'publici', 'pune', 'punjab', 'punjabi', 'purchas', 'purpos', 'pvt', 'pycharm', 'pyimagesearch', 'pyspark', 'pytesseract', 'python', 'pythonsoftwar', 'pytorch', 'quadrado', 'quali', 'qualif', 'qualiti', 'qualityori', 'quantifi', 'quantimum', 'quantit', 'quarter', 'queri', 'question', 'quit', 'quiz', 'quromba', 'r', 'ra', 'radio', 'railway', 'rais', 'raja', 'rajiv', 'ramirez', 'ranchi', 'random', 'rang', 'rao', 'raspberri', 'raster', 'ratio', 'rcc', 'rdbm', 'react', 'reaction', 'readi', 'real', 'reallif', 'realtim', 'realworld', 'reason', 'recent', 'recognit', 'recommend', 'record', 'redact', 'redshift', 'reduc', 'reed', 'reever', 'refin', 'registr', 'regonit', 'regress', 'reinforc', 'reinsur', 'relat', 'relay', 'relev', 'reli', 'reliabil', 'remark', 'remiro', 'remot', 'remov', 'report', 'represent', 'request', 'requir', 'research', 'residu', 'resourc', 'respect', 'respons', 'responsibil', 'restapi', 'result', 'retail', 'retent', 'retrain', 'return', 'revolv', 'reward', 'rfi', 'rfp', 'rfq', 'rgpv', 'rich', 'rider', 'ridg', 'right', 'risk', 'riskmodel', 'rm', 'rnn', 'robert', 'robot', 'robust', 'rodney', 'roger', 'role', 'root', 'rossier', 'rout', 'rshini', 'rtoreturn', 'rubi', 'runner', 'runnerup', 's2h', 'sa', 'sadar', 'sadhana', 'sagemak', 'sahara', 'sai', 'saiko', 'sale', 'sampl', 'sanrachna', 'sap', 'sapient', 'satellit', 'satisfact', 'scala', 'scalabl', 'scale', 'scall', 'scarlett', 'scenario', 'scholar', 'school', 'scienc', 'scientist', 'scientistanalyt', 'scikit', 'scikitlearn', 'scorecard', 'scrap', 'script', 'scriptur', 'sde', 'sdedata', 'sdemachin', 'seaborn', 'seamless', 'sean', 'search', 'secondari', 'sector', 'seek', 'segment', 'select', 'selenium', 'semant', 'sens', 'sensor', 'sentenc', 'sentiment', 'sep', 'separ', 'sequenti', 'seri', 'serv', 'server', 'servic', 'set', 'setup', 'sever', 'sgbau', 'sgt', 'shahe', 'sharp', 'shaw', 'shawn', 'sher', 'shipment', 'shiv', 'shock', 'shop', 'show', 'shown', 'shri', 'side', 'signal', 'signific', 'sikkim', 'silver', 'similar', 'simpl', 'simplifi', 'sinc', 'singh', 'singhji', 'site', 'sixsigma', 'sju', 'sk', 'skil', 'skill', 'skillset', 'skin', 'sklearn', 'skn', 'sl', 'sla', 'small', 'smart', 'sme', 'smile', 'smith', 'snake', 'softwar', 'soil', 'solinov', 'solut', 'solv', 'someon', 'son', 'song', 'sota', 'soup', 'sourc', 'sp', 'spaci', 'spark', 'sparkpyspark', 'special', 'specialist', 'specially', 'speech', 'speechbas', 'sppu', 'springboot', 'spss', 'sql', 'srm', 'srmu', 'ssgm', 'st', 'stabil', 'stacey', 'stage', 'stakehold', 'standard', 'stanford', 'star', 'start', 'stateoftheart', 'statist', 'stc', 'ste', 'steam', 'steer', 'stella', 'sten', 'step', 'stock', 'storag', 'store', 'strateg', 'strategi', 'streamlit', 'strive', 'strong', 'structur', 'student', 'studi', 'studio', 'subhash', 'subspac', 'success', 'suitabl', 'summar', 'summari', 'summer', 'supervis', 'suppli', 'support', 'sure', 'survey', 'svm', 'switch', 'sydney', 'symmetr', 'synthesi', 'system', 'systemica', 'tableau', 'tag', 'take', 'talend', 'tanisha', 'target', 'task', 'tata', 'taxi', 'taylor', 'teach', 'team', 'teamwork', 'tech', 'technic', 'techniqu', 'technolog', 'technologyagnost', 'technologyrourkela', 'technosci', 'telco', 'telecommun', 'telemetri', 'templat', 'tensorflow', 'tenur', 'term', 'test', 'tester', 'text', 'textual', 'thakur', 'thala', 'thatcher', 'therefor', 'thesi', 'think', 'though', 'throttl', 'throughout', 'thu', 'ti', 'ticket', 'til', 'till', 'time', 'timeli', 'titl', 'titli', 'tml', 'tone', 'took', 'tool', 'top', 'topic', 'toubro', 'tour', 'toward', 'toxic', 'track', 'tractor', 'train', 'traine', 'traintest', 'transact', 'transfer', 'transform', 'transit', 'translat', 'transmiss', 'transport', 'travel', 'treatment', 'tree', 'trend', 'tri', 'troubleshoot', 'tsc', 'tune', 'turn', 'turnov', 'type', 'u', 'udac', 'ui', 'uiux', 'undergradu', 'underneath', 'understand', 'undertaken', 'unifi', 'uniform', 'unit', 'univari', 'univers', 'unix', 'unstruct', 'unstructur', 'unsupervis', 'upcom', 'updat', 'upi', 'us', 'usag', 'use', 'user', 'uti', 'util', 'utilis', 'uttaranch', 'v', 'vagu', 'valid', 'vari', 'varianc', 'variou', 'vector', 'vehicl', 'vellor', 'vendor', 'ventur', 'verifi', 'versa', 'vgg16', 'vice', 'video', 'view', 'virtual', 'vishwavidyalaya', 'vision', 'visual', 'visualis', 'visveswaraiah', 'vit', 'vitap', 'vizon', 'voic', 'volum', 'volvo', 'vtu', 'vvit', 'w', 'wang', 'want', 'wareh', 'warehous', 'warehousepl', 'wast', 'waterloo', 'way', 'weather', 'web', 'webbas', 'webpag', 'websit', 'weight', 'well', 'wellarm', 'wesbit', 'what', 'whole', 'william', 'wilson', 'winner', 'winston', 'within', 'without', 'word', 'wordcloud', 'work', 'workflow', 'workshop', 'world', 'would', 'wrangl', 'wrt', 'wtpl', 'wyatt', 'x', 'xcelsior', 'xgboost', 'xlnet', 'xml', 'yarn', 'yastein', 'year', 'yolo', 'young', 'younger', 'z', 'zoombot', 'zynta']

In [243]:
X_counts_df = pd.DataFrame(X_counts.toarray(), columns=ngram_vect.get_feature_names())
X_counts_df.head(10)

      1  2  2015  2017  2018  ...  yolo  young  younger  z  zoombot  zynta
0  1  0  0     0     0     0  ...     0      0        0  0        0      0
1  1  0  0     0     0     1  ...     0      0        0  0        0      0
2  1  0  0     0     0     0  ...     0      0        0  0        0      0
3  1  0  0     0     0     2  ...     0      0        0  0        0      0
4  1  0  0     0     0     0  ...     0      0        0  0        0      0
5  1  0  0     0     0     1  ...     0      0        0  0        0      0
6  1  0  0     0     0     0  ...     0      0        0  0        0      0
7  1  0  0     0     0     0  ...     0      0        0  0        0      0
8  1  0  0     0     0     1  ...     0      0        0  0        0      0
9  1  0  0     0     0     0  ...     0      0        0  0        0      0

[10 rows x 1831 columns]

Vectorizing Raw Data: TF-IDF

Apply TfidfVectorizer

In [244]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(analyzer=clean_text)
X_tfidf = tfidf_vect.fit_transform(original['resume'])
print(X_tfidf.shape)
print(tfidf_vect.get_feature_names())

(90, 1831)
['', '1', '2', '2015', '2017', '2018', '2019', '20192021', '2019august', '2019feb', '2019nov', '2019oct', '2019till', '2020', '20202021', '2020oct', '2020to', '2021', '5', 'a1', 'abbern', 'abigail', 'abil', 'abl', 'abnorm', 'absolut', 'abul', 'ac', 'academ', 'academi', 'acceler', 'access', 'accord', 'account', 'accumul', 'accur', 'accuraci', 'achiev', 'acquaint', 'acquisit', 'across', 'action', 'activ', 'activit', 'ad', 'adapt', 'address', 'adept', 'administr', 'adob', 'adopt', 'advanc', 'adversari', 'advic', 'advisor', 'affect', 'agil', 'agricultur', 'agro', 'ahmedabad', 'ai', 'aibas', 'aid', 'aiffer', 'aim', 'aiml', 'air', 'alexi', 'algorithm', 'align', 'allen', 'alloc', 'along', 'also', 'alteryx', 'alway', 'amass', 'amaz', 'amazon', 'amber', 'amelia', 'amio', 'amiti', 'among', 'amount', 'amz', 'anaconda', 'analys', 'analysi', 'analyst', 'analyt', 'analyz', 'angularj', 'anim', 'ann', 'anna', 'anomal', 'anomali', 'anova', 'answer', 'anthoni', 'anyth', 'apach', 'api', 'app', 'appli', 'applic', 'approach', 'apr', 'arbitr', 'architect', 'architectur', 'arduino', 'area', 'armstrong', 'around', 'arrest', 'arsen', 'art', 'artifici', 'artistri', 'aset', 'ashley', 'asist', 'asl', 'aspect', 'aspen', 'assembl', 'assess', 'assign', 'assist', 'associ', 'atc', 'attack', 'attend', 'attent', 'attitud', 'attrit', 'attun', 'audienc', 'audrey', 'aug', 'auto', 'autocolor', 'autom', 'automat', 'automot', 'avail', 'averi', 'avid', 'aw', 'award', 'awsemrec2s3', 'axi', 'az', 'azur', 'b', 'ba', 'bachelor', 'background', 'baeconom', 'bailey', 'baker', 'balanc', 'baliyaup', 'band', 'bangalor', 'banhadau', 'bank', 'base', 'basher', 'batch', 'bb', 'bba', 'bca', 'bcom', 'beanstalk', 'beauti', 'beginn', 'behavior', 'belarni', 'belemundi', 'believ', 'belt', 'benefici', 'benefit', 'bengaluru', 'benham', 'benjamin', 'benley', 'bert', 'best', 'bestfit', 'bethani', 'better', 'beuford', 'bgb', 'bhagat', 'bhavleesh', 'bhopal', 'bi', 'bib', 'big', 'bigger', 'bigqueri', 'bill', 'biomed', 'birla', 'birsimb', 'biswa', 'bit', 'bitrat', 'bivari', 'blend', 'block', 'blockchain', 'blood', 'bombay', 'bootstrap', 'bot', 'botassist', 'bottom', 'bound', 'boundari', 'box', 'brainstrom', 'brane', 'braxton', 'breath', 'breed', 'brianna', 'bristlecon', 'brokerag', 'broodi', 'brook', 'brown', 'brows', 'bsc', 'bscca', 'bsi', 'btech', 'btechb', 'btechbiotech', 'btechcivil', 'btechcomput', 'btechcs', 'btechec', 'btechelectr', 'btechelectron', 'btechelectronicstelecommun', 'btechinstrument', 'btechit', 'btechmechan', 'btechmetallurgi', 'bu', 'buffet', 'bug', 'build', 'built', 'burnsley', 'busi', 'c', 'ca', 'calcul', 'calcutta', 'calicut', 'caltech', 'camilla', 'campbel', 'cap', 'capabl', 'caption', 'captur', 'card', 'cardiac', 'care', 'career', 'carli', 'carlton', 'carolin', 'carri', 'case', 'cat', 'catalysi', 'catastroph', 'catboost', 'categor', 'categori', 'caus', 'cb', 'cdn', 'cellular', 'centric', 'ceram', 'certif', 'certifi', 'chadrasekhar', 'chain', 'challeng', 'chand', 'chandra', 'chang', 'charact', 'charan', 'charg', 'chat', 'chatbot', 'chechnik', 'checmic', 'chemic', 'chennai', 'chennal', 'children', 'chosen', 'chrysali', 'chunk', 'ci', 'cit', 'civil', 'claim', 'clark', 'classif', 'classifi', 'clean', 'cleans', 'client', 'clientel', 'clifford', 'close', 'cloud', 'cloudbas', 'cloudmail', 'cloudtest', 'cluster', 'cnn', 'co', 'coalesc', 'coarsegrain', 'cocacola', 'code', 'coerciv', 'cognibot', 'cognit', 'cohes', 'coimbator', 'coleson', 'collabor', 'collect', 'colleg', 'combin', 'come', 'comment', 'commerc', 'commerci', 'commun', 'compani', 'comparison', 'compet', 'complet', 'complex', 'compon', 'composit', 'compound', 'compress', 'comput', 'concept', 'conclud', 'confid', 'conjug', 'connect', 'conner', 'consist', 'constantli', 'construct', 'consult', 'consumpt', 'contain', 'contextu', 'continu', 'contribut', 'control', 'convers', 'convert', 'convey', 'convolut', 'conway', 'coolfactormet', 'cooper', 'coordin', 'core', 'corpor', 'correl', 'correspond', 'cost', 'cotton', 'council', 'cours', 'coursework', 'crash', 'creat', 'creation', 'creativ', 'credit', 'crison', 'crisp', 'criteria', 'critic', 'cron', 'crowd', 'cse', 'csi', 'css', 'cultur', 'cummin', 'curiositydriven', 'currenc', 'current', 'curricular', 'custom', 'customiz', 'cutthroat', 'da', 'damian', 'daniel', 'darjeel', 'dashboard', 'dashboardbas', 'dass', 'data', 'databas', 'databrick', 'datacamp', 'datadriven', 'dataflow', 'dataset', 'date', 'day', 'db', 'dbb', 'dbm', 'dbscan', 'dd', 'dealer', 'debug', 'dec', 'decid', 'decis', 'decisionmak', 'declin', 'dedic', 'deep', 'deeper', 'deeplearningai', 'default', 'defect', 'defin', 'degre', 'delhi', 'deliv', 'deliveri', 'deloitt', 'demand', 'demonstr', 'depend', 'deploy', 'deplyo', 'deputi', 'deriv', 'desark', 'descript', 'design', 'desk', 'detail', 'detect', 'determin', 'develop', 'developermachin', 'developmentrel', 'devic', 'devnagari', 'devop', 'dialogu', 'diametr', 'diaster', 'dicti', 'differ', 'digiscap', 'digit', 'dimension', 'diploma', 'direct', 'disciplin', 'disconfigur', 'discov', 'discoveri', 'diseas', 'display', 'disput', 'dissemin', 'distanc', 'distinct', 'dive', 'divis', 'divvi', 'django', 'djr', 'dkb', 'dl', 'dm', 'docker', 'document', 'domain', 'dome', 'dr', 'dravidian', 'drdo', 'drew', 'drive', 'driven', 'drop', 'drove', 'due', 'duggar', 'durat', 'dynam', 'e', 'eager', 'eagerli', 'earli', 'eas', 'easi', 'easier', 'easili', 'ec2', 'ece', 'econom', 'econometr', 'economist', 'eda', 'edg', 'educ', 'effect', 'elast', 'electr', 'electron', 'electronicstelecommun', 'elli', 'elocution', 'email', 'embed', 'emerg', 'employ', 'employe', 'empow', 'end', 'endto', 'endtoend', 'energi', 'engag', 'engin', 'english', 'enhanc', 'enjoy', 'enlist', 'ensur', 'enterpris', 'entertain', 'enthusiasm', 'enthusiast', 'entir', 'entrepreneurship', 'environ', 'ep', 'erc', 'erp', 'error', 'estim', 'etc', 'ethan', 'etl', 'evalu', 'everett', 'evolv', 'exam', 'excel', 'exchang', 'excit', 'execut', 'exercis', 'exhibit', 'expand', 'expect', 'expenditur', 'experi', 'experienc', 'expert', 'expertis', 'explor', 'exploratori', 'export', 'express', 'extens', 'extern', 'extra', 'extract', 'extracurricular', 'extrem', 'eye', 'f', 'face', 'facilit', 'fact', 'factor', 'factori', 'fake', 'fallout', 'familiar', 'fare', 'fascin', 'fashion', 'fault', 'featur', 'feb', 'feed', 'feedback', 'feel', 'felix', 'fernand', 'fi', 'fiat', 'field', 'figur', 'file', 'filtrat', 'final', 'finalist', 'financ', 'financi', 'find', 'finetun', 'firebas', 'firm', 'fit', 'fix', 'flag', 'flair', 'flask', 'flipkart', 'flow', 'flutter', 'focu', 'focus', 'food', 'foot', 'forecast', 'forest', 'forgeri', 'format', 'formula', 'found', 'foundat', 'fourier', 'framework', 'franchis', 'frank', 'fraud', 'fraudul', 'frequenc', 'fresher', 'front', 'frontend', 'fsx', 'fuel', 'full', 'fulli', 'fulltim', 'fun', 'function', 'funnel', 'futur', 'g', 'game', 'gan', 'gandhi', 'garcia', 'garodia', 'gartner', 'gateway', 'gather', 'gave', 'gcp', 'gdp', 'geakmind', 'gener', 'genr', 'gentl', 'geo', 'gestur', 'get', 'ginanna', 'git', 'give', 'given', 'glacier', 'global', 'glove', 'go', 'goa', 'goal', 'gobind', 'gold', 'gomez', 'good', 'goodman', 'googl', 'goto', 'gover', 'gpt', 'gpt2', 'gpu', 'grade', 'graduat', 'gradut', 'grant', 'granul', 'grape', 'graphic', 'graphml', 'graphql', 'grasp', 'greater', 'greatli', 'green', 'group', 'grow', 'growth', 'gru', 'gruvil', 'guap', 'guid', 'guidanc', 'gujarat', 'guru', 'guwahati', 'h', 'h2oai', 'hadoop', 'half', 'hall', 'hamirpur', 'hand', 'handl', 'handson', 'hansraj', 'hardwar', 'hardwork', 'hayden', 'haydon', 'hayle', 'hcl', 'hdf', 'head', 'health', 'helena', 'help', 'hem', 'heramba', 'hernandez', 'heurist', 'hib', 'high', 'highest', 'highli', 'highvolum', 'himach', 'hisher', 'histori', 'hive', 'hivehql', 'hmi', 'hmm', 'holden', 'home', 'honorari', 'hoogli', 'horan', 'horizon', 'host', 'hotspot', 'hous', 'howard', 'hr', 'hs', 'hsbc', 'html', 'hub', 'huggingfac', 'hyderabad', 'hypothesi', 'i', 'iabac', 'ibb', 'ibm', 'icpc', 'ict', 'id', 'idea', 'ident', 'identif', 'identifi', 'ideolog', 'ifr', 'igenc', 'iiit', 'iit', 'ike', 'imag', 'immedi', 'impact', 'implement', 'import', 'improv', 'in', 'inc', 'incid', 'includ', 'inclus', 'incorpor', 'increas', 'indentifi', 'index', 'india', 'indian', 'indic', 'individu', 'indor', 'indosi', 'industri', 'industrylevel', 'ine', 'infect', 'inform', 'informat', 'informatica', 'infotech', 'infrastructur', 'ingest', 'initi', 'injunct', 'innov', 'input', 'insid', 'insight', 'instal', 'institut', 'instructor', 'instrument', 'insur', 'integr', 'intel', 'intellig', 'interact', 'interest', 'interfac', 'intermedi', 'intermitt', 'intern', 'internship', 'interpret', 'intricaci', 'introduc', 'introduct', 'inventori', 'invest', 'invictu', 'invoic', 'involv', 'iot', 'irrm', 'isabella', 'isi', 'issu', 'iti', 'ize', 'j', 'jacob', 'jade', 'jadodia', 'jagjiban', 'jaim', 'jain', 'jan', 'jaroslav', 'java', 'javascript', 'jayla', 'jdbc', 'jeco', 'jen', 'jenkin', 'jennif', 'jensen', 'jeremi', 'jerom', 'jessica', 'jewelri', 'jimmi', 'jiot', 'jira', 'jjr', 'jkg', 'job', 'john', 'join', 'jona', 'jone', 'jose', 'joselin', 'joseph', 'journey', 'jp', 'jr', 'jt', 'jul', 'juli', 'jumpstart', 'jun', 'junior', 'jupyt', 'jvv', 'k', 'kafka', 'kancheepuram', 'kanchipuram', 'kanpur', 'karnataka', 'kashwant', 'keen', 'keep', 'kelsey', 'kera', 'kerala', 'key', 'keyword', 'kharagpur', 'kibana', 'kind', 'kinsgley', 'klp', 'kmean', 'knack', 'knn', 'knowledg', 'knowledgebas', 'knowntobank', 'kochi', 'kolkata', 'kotlin', 'kottam', 'kpg', 'kpi', 'kpmmc', 'kripa', 'ksst', 'ksv', 'ktb', 'kubeflow', 'kubernet', 'kumar', 'kvoct', 'l', 'lab', 'lambda', 'languag', 'laravel', 'larg', 'larger', 'largescal', 'larsen', 'lasso', 'latent', 'lawn', 'layla', 'lead', 'leadership', 'leaf', 'learn', 'learner', 'led', 'ledger', 'legal', 'level', 'leverag', 'lexicon', 'lexiconbas', 'liaison', 'librari', 'life', 'lifecycl', 'like', 'likelihood', 'limit', 'line', 'linear', 'link', 'linux', 'lisa', 'load', 'loan', 'local', 'locat', 'logic', 'logist', 'look', 'lookout', 'lopez', 'loss', 'lot', 'love', 'loyola', 'ls', 'lstm', 'lt', 'ltd', 'ltt', 'lucen', 'lucknow', 'ludhiana', 'lustr', 'machin', 'maci', 'mackey', 'macro', 'made', 'madelyn', 'madra', 'magicpin', 'maharashtra', 'mahindra', 'main', 'maintain', 'mainten', 'major', 'make', 'malviya', 'mamco', 'manag', 'manageri', 'mangalor', 'manip', 'manipul', 'manufactur', 'map', 'mapper', 'mapreduc', 'mar', 'march', 'marcu', 'mariana', 'market', 'markinov', 'mask', 'maskrcnn', 'mason', 'master', 'match', 'math', 'mathew', 'matilda', 'matlab', 'matplotlib', 'maulana', 'may', 'maya', 'mba', 'mbainform', 'mca', 'meaning', 'mechan', 'medal', 'medalist', 'media', 'medic', 'medica', 'medicin', 'member', 'memori', 'mend', 'mental', 'messag', 'mesto', 'method', 'methodolog', 'meticul', 'metric', 'mia', 'michael', 'microcontrol', 'microsoft', 'miet', 'might', 'mikayla', 'mileston', 'milner', 'mind', 'mine', 'mini', 'minitab', 'mirad', 'mirl', 'mirror', 'ml', 'mlop', 'model', 'modern', 'modul', 'modulesdeliver', 'mohantpur', 'moistur', 'molecul', 'molecular', 'mongodb', 'monitor', 'moor', 'mortgag', 'motiv', 'movi', 'mower', 'mqtt', 'ms', 'msc', 'mscca', 'msccomput', 'mscscienc', 'msexcel', 'msfe', 'mtech', 'mtechdata', 'multi', 'multipl', 'multivari', 'mumbai', 'music', 'mysql', 'n', 'nagpur', 'nane', 'nano', 'nanyang', 'nashik', 'nasik', 'nation', 'natur', 'naxapp', 'nazapp', 'nearli', 'need', 'net', 'network', 'neuer', 'neural', 'new', 'newtobank', 'nichola', 'nielsen', 'nist', 'nit', 'nlp', 'nlpbase', 'nltk', 'node', 'nodej', 'noida', 'nois', 'nolan', 'non', 'nonrepair', 'norm', 'normal', 'nosql', 'nov', 'nptel', 'ntb', 'number', 'numer', 'numpi', 'nyu', 'nyugen', 'object', 'objectdetect', 'ocr', 'oct', 'offer', 'offerproduct', 'offic', 'ondevic', 'one', 'one97', 'ongo', 'onlin', 'onwebsit', 'oop', 'opencv', 'oper', 'opportun', 'optim', 'optimis', 'optimum', 'option', 'oracl', 'orchestr', 'orchidia', 'order', 'organ', 'organiz', 'orient', 'origin', 'orissa', 'osmania', 'osta', 'out', 'outcom', 'outlet', 'outlier', 'outofthebox', 'overal', 'owen', 'owner', 'p', 'paint', 'pan', 'panda', 'paper', 'paragraph', 'paramet', 'park', 'parkar', 'parker', 'part', 'particularli', 'partsmateri', 'parttim', 'passeng', 'passion', 'patch', 'patiala', 'patrick', 'pattern', 'payment', 'pe', 'pelinski', 'peopl', 'perceiv', 'perfect', 'perform', 'period', 'person', 'pg', 'pgg', 'photo', 'php', 'pi', 'pictur', 'pierr', 'pig', 'pillow', 'pipelin', 'pixel', 'plan', 'platform', 'player', 'plot', 'point', 'polaris', 'pollut', 'polymon', 'pondicherri', 'popul', 'portal', 'portfolio', 'posit', 'possess', 'possibl', 'post', 'postanalysi', 'postgresql', 'potenti', 'power', 'powerbi', 'practic', 'practition', 'praxi', 'preapprov', 'predict', 'premium', 'prepar', 'preprocess', 'presal', 'presenc', 'present', 'pretrain', 'previous', 'price', 'primarili', 'princip', 'principl', 'priorit', 'privat', 'prm', 'proactiv', 'probabl', 'problem', 'problemsolv', 'procedur', 'process', 'processflow', 'processor', 'produc', 'product', 'productiongrad', 'profession', 'profici', 'profil', 'profit', 'program', 'programm', 'progress', 'project', 'projeect', 'promis', 'proofofconcept', 'proper', 'propos', 'prototyp', 'proudyogiki', 'prove', 'provid', 'psi', 'public', 'publici', 'pune', 'punjab', 'punjabi', 'purchas', 'purpos', 'pvt', 'pycharm', 'pyimagesearch', 'pyspark', 'pytesseract', 'python', 'pythonsoftwar', 'pytorch', 'quadrado', 'quali', 'qualif', 'qualiti', 'qualityori', 'quantifi', 'quantimum', 'quantit', 'quarter', 'queri', 'question', 'quit', 'quiz', 'quromba', 'r', 'ra', 'radio', 'railway', 'rais', 'raja', 'rajiv', 'ramirez', 'ranchi', 'random', 'rang', 'rao', 'raspberri', 'raster', 'ratio', 'rcc', 'rdbm', 'react', 'reaction', 'readi', 'real', 'reallif', 'realtim', 'realworld', 'reason', 'recent', 'recognit', 'recommend', 'record', 'redact', 'redshift', 'reduc', 'reed', 'reever', 'refin', 'registr', 'regonit', 'regress', 'reinforc', 'reinsur', 'relat', 'relay', 'relev', 'reli', 'reliabil', 'remark', 'remiro', 'remot', 'remov', 'report', 'represent', 'request', 'requir', 'research', 'residu', 'resourc', 'respect', 'respons', 'responsibil', 'restapi', 'result', 'retail', 'retent', 'retrain', 'return', 'revolv', 'reward', 'rfi', 'rfp', 'rfq', 'rgpv', 'rich', 'rider', 'ridg', 'right', 'risk', 'riskmodel', 'rm', 'rnn', 'robert', 'robot', 'robust', 'rodney', 'roger', 'role', 'root', 'rossier', 'rout', 'rshini', 'rtoreturn', 'rubi', 'runner', 'runnerup', 's2h', 'sa', 'sadar', 'sadhana', 'sagemak', 'sahara', 'sai', 'saiko', 'sale', 'sampl', 'sanrachna', 'sap', 'sapient', 'satellit', 'satisfact', 'scala', 'scalabl', 'scale', 'scall', 'scarlett', 'scenario', 'scholar', 'school', 'scienc', 'scientist', 'scientistanalyt', 'scikit', 'scikitlearn', 'scorecard', 'scrap', 'script', 'scriptur', 'sde', 'sdedata', 'sdemachin', 'seaborn', 'seamless', 'sean', 'search', 'secondari', 'sector', 'seek', 'segment', 'select', 'selenium', 'semant', 'sens', 'sensor', 'sentenc', 'sentiment', 'sep', 'separ', 'sequenti', 'seri', 'serv', 'server', 'servic', 'set', 'setup', 'sever', 'sgbau', 'sgt', 'shahe', 'sharp', 'shaw', 'shawn', 'sher', 'shipment', 'shiv', 'shock', 'shop', 'show', 'shown', 'shri', 'side', 'signal', 'signific', 'sikkim', 'silver', 'similar', 'simpl', 'simplifi', 'sinc', 'singh', 'singhji', 'site', 'sixsigma', 'sju', 'sk', 'skil', 'skill', 'skillset', 'skin', 'sklearn', 'skn', 'sl', 'sla', 'small', 'smart', 'sme', 'smile', 'smith', 'snake', 'softwar', 'soil', 'solinov', 'solut', 'solv', 'someon', 'son', 'song', 'sota', 'soup', 'sourc', 'sp', 'spaci', 'spark', 'sparkpyspark', 'special', 'specialist', 'specially', 'speech', 'speechbas', 'sppu', 'springboot', 'spss', 'sql', 'srm', 'srmu', 'ssgm', 'st', 'stabil', 'stacey', 'stage', 'stakehold', 'standard', 'stanford', 'star', 'start', 'stateoftheart', 'statist', 'stc', 'ste', 'steam', 'steer', 'stella', 'sten', 'step', 'stock', 'storag', 'store', 'strateg', 'strategi', 'streamlit', 'strive', 'strong', 'structur', 'student', 'studi', 'studio', 'subhash', 'subspac', 'success', 'suitabl', 'summar', 'summari', 'summer', 'supervis', 'suppli', 'support', 'sure', 'survey', 'svm', 'switch', 'sydney', 'symmetr', 'synthesi', 'system', 'systemica', 'tableau', 'tag', 'take', 'talend', 'tanisha', 'target', 'task', 'tata', 'taxi', 'taylor', 'teach', 'team', 'teamwork', 'tech', 'technic', 'techniqu', 'technolog', 'technologyagnost', 'technologyrourkela', 'technosci', 'telco', 'telecommun', 'telemetri', 'templat', 'tensorflow', 'tenur', 'term', 'test', 'tester', 'text', 'textual', 'thakur', 'thala', 'thatcher', 'therefor', 'thesi', 'think', 'though', 'throttl', 'throughout', 'thu', 'ti', 'ticket', 'til', 'till', 'time', 'timeli', 'titl', 'titli', 'tml', 'tone', 'took', 'tool', 'top', 'topic', 'toubro', 'tour', 'toward', 'toxic', 'track', 'tractor', 'train', 'traine', 'traintest', 'transact', 'transfer', 'transform', 'transit', 'translat', 'transmiss', 'transport', 'travel', 'treatment', 'tree', 'trend', 'tri', 'troubleshoot', 'tsc', 'tune', 'turn', 'turnov', 'type', 'u', 'udac', 'ui', 'uiux', 'undergradu', 'underneath', 'understand', 'undertaken', 'unifi', 'uniform', 'unit', 'univari', 'univers', 'unix', 'unstruct', 'unstructur', 'unsupervis', 'upcom', 'updat', 'upi', 'us', 'usag', 'use', 'user', 'uti', 'util', 'utilis', 'uttaranch', 'v', 'vagu', 'valid', 'vari', 'varianc', 'variou', 'vector', 'vehicl', 'vellor', 'vendor', 'ventur', 'verifi', 'versa', 'vgg16', 'vice', 'video', 'view', 'virtual', 'vishwavidyalaya', 'vision', 'visual', 'visualis', 'visveswaraiah', 'vit', 'vitap', 'vizon', 'voic', 'volum', 'volvo', 'vtu', 'vvit', 'w', 'wang', 'want', 'wareh', 'warehous', 'warehousepl', 'wast', 'waterloo', 'way', 'weather', 'web', 'webbas', 'webpag', 'websit', 'weight', 'well', 'wellarm', 'wesbit', 'what', 'whole', 'william', 'wilson', 'winner', 'winston', 'within', 'without', 'word', 'wordcloud', 'work', 'workflow', 'workshop', 'world', 'would', 'wrangl', 'wrt', 'wtpl', 'wyatt', 'x', 'xcelsior', 'xgboost', 'xlnet', 'xml', 'yarn', 'yastein', 'year', 'yolo', 'young', 'younger', 'z', 'zoombot', 'zynta']

In [245]:
X_tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vect.get_feature_names())
X_tfidf_df.head(10)

               1    2  2015  2017  ...  young  younger    z  zoombot  zynta
0  0.034690  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
1  0.024864  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
2  0.029422  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
3  0.023408  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
4  0.027264  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
5  0.031732  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
6  0.030665  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
7  0.026585  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
8  0.020594  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
9  0.034850  0.0  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0

[10 rows x 1831 columns]

In [246]:
print(X_tfidf_df.loc[(X_tfidf_df!=0).any(axis=1)])

                     1    2  2015  2017  ...  young  younger    z  zoombot  zynta
0   0.034690  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
1   0.024864  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
2   0.029422  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
3   0.023408  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
4   0.027264  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
..       ...       ...  ...   ...   ...  ...    ...      ...  ...      ...    ...
85  0.039004  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
86  0.028402  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
87  0.037903  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
88  0.025641  0.105758  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
89  0.034808  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0

[90 rows x 1831 columns]

Feature Engineering: Feature Creation

Create feature for text message length and % of punctuation in text

Function to calculate length of message excluding space

In [247]:
original['body_len'] = original['resume'].apply(lambda x: len(x) - x.count(" "))

original.head()

def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return round(count/(len(text) - text.count(" ")), 3)*100

original['punct%'] = original['resume'].apply(lambda x: count_punct(x))

original.head()

                                                                                                resume  ...  punct%
0    JACOB SMITH F R E S H E R  SKILLS  Python, SQL, MySQL, Tableau, Power Bi, Pandas , Numpy, Matp...  ...     4.6
1    Brianna Williams J U N I O R  D E V E L O P E R  Executive Profile  A curiosity-driven data sc...  ...     3.6
2    AMZ Loans and Mortgages ERC Analytics, Jun 2019 to till date  Handling data of employees and f...  ...     4.3
3    P R O F I L E  Extremely motivated to constantly develop my skills and grow  professionally. I...  ...     3.7
4    JENNIFER ARMSTRONG  P R O F I L E Fresher Computer vision and Machine Learning  Engineer looki...  ...     2.2

[5 rows x 3 columns]

In [248]:
train

      CandidateID  Match Percentage
0   candidate_000             13.70
1   candidate_001             40.09
2   candidate_002             48.91
3   candidate_003             36.89
4   candidate_006             44.96
..            ...               ...
85  candidate_144              6.00
86  candidate_145             47.08
87  candidate_147             11.53
88  candidate_148             60.11
89  candidate_149             41.20

[90 rows x 2 columns]

In [249]:
X_tfidf_df

                     1    2  2015  2017  ...  young  younger    z  zoombot  zynta
0   0.034690  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
1   0.024864  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
2   0.029422  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
3   0.023408  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
4   0.027264  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
..       ...       ...  ...   ...   ...  ...    ...      ...  ...      ...    ...
85  0.039004  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
86  0.028402  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
87  0.037903  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
88  0.025641  0.105758  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0
89  0.034808  0.000000  0.0   0.0   0.0  ...    0.0      0.0  0.0      0.0    0.0

[90 rows x 1831 columns]

In [250]:
X_tfidf_df['Match Percentage']=train['Match Percentage']

In [251]:
X_tfidf_df

                     1    2  2015  ...    z  zoombot  zynta  Match Percentage
0   0.034690  0.000000  0.0   0.0  ...  0.0      0.0    0.0             13.70
1   0.024864  0.000000  0.0   0.0  ...  0.0      0.0    0.0             40.09
2   0.029422  0.000000  0.0   0.0  ...  0.0      0.0    0.0             48.91
3   0.023408  0.000000  0.0   0.0  ...  0.0      0.0    0.0             36.89
4   0.027264  0.000000  0.0   0.0  ...  0.0      0.0    0.0             44.96
..       ...       ...  ...   ...  ...  ...      ...    ...               ...
85  0.039004  0.000000  0.0   0.0  ...  0.0      0.0    0.0              6.00
86  0.028402  0.000000  0.0   0.0  ...  0.0      0.0    0.0             47.08
87  0.037903  0.000000  0.0   0.0  ...  0.0      0.0    0.0             11.53
88  0.025641  0.105758  0.0   0.0  ...  0.0      0.0    0.0             60.11
89  0.034808  0.000000  0.0   0.0  ...  0.0      0.0    0.0             41.20

[90 rows x 1832 columns]

In [252]:
test=pd.read_csv("/content/Project-To-Choose-Perfect-Candidate-Based-on-Resume/dataset/test.csv")
test.head()

     CandidateID
0  candidate_014
1  candidate_098
2  candidate_075
3  candidate_016
4  candidate_131

In [253]:
final_test_primary_original=test.copy()

In [254]:
final_test_primary=df_test.copy()

In [255]:
df_test=df_test.sort_values('CandidateID').reset_index(drop=True)
df_test

      CandidateID                                                                                               resume
0   candidate_004    O L I V I A  S A N T O S CONSULTANT ANALYST  WORK EXPERIENCE  Cognizant, Apr 2020 - Ongoing  C...
1   candidate_005    ARMIN FITZGERALD  D A  T  A   M  A  N  A  G  E  R  PROFESSIONAL PROFILE  Expertise in Mathemat...
2   candidate_014    GRACE BAILRY M A C H I N E  L E A R N I N G  D E V E L O P M E N T  A N D  D E P L O Y M E N T...
3   candidate_016    A M E L I A  M A R T I N DATA SCIENCE MAJOR  WORK EXPERIENCE  NA  ACADEMIC PROFILE  B.Tech(Com...
4   candidate_017    P R O F I L E  I am a Junior Machine Learning developer who focuses on data  improvement and m...
5   candidate_018    EVELYNN ADAMS  G R A D U A T E  F R E S H E R  PROFESSIONAL PROFILE  I am a recent graduate wh...
6   candidate_019    JOSHUA WHITE A S S I S T A N T  S O F T W A R E  A N D  M A C H I N E  L E A R N I N G  E N G ...
7   candidate_028    ASI Technologies  Intern,  Dec 2020 - Ongoing  Working as an intern to learn the usage of Neur...
8   candidate_029    Eli Scott F R E SHER  Executive Profile  Seeking challenging opportunity in the field of data ...
9   candidate_031    P R O F I L E  An avid explorer of analytics in multiple facets pertaining to  production indu...
10  candidate_033    CHARLES RODRIGUEZ S O F T W A R E  A N D  P R O J E C T  M A N A G E R  SKILLS  Natural Langua...
11  candidate_035    CISCO  Software Developer and Analyst Trainee OCT 2018 - May 2019    Developed Async Functions...
12  candidate_036    James May F R E S H E R  S O F T W A R E  D E V E L O P E R  E N G I N E E R  Executive Profil...
13  candidate_039    NICOLE BREWER  P O S T  G R A D U A T E  B U S I N E S S A N A L Y S T  PROFESSIONAL PROFILE  ...
14  candidate_040    ETHAN GARCIA F R E S H E R  D E V E L O P E R  E N G I N E E R  SKILLS  C++, Python, C, Softwa...
15  candidate_042    Ryan Nelson F R E S H E R  S O F T W A R E  D E V E L O P E R    Executive Profile  I consider...
16  candidate_044    L E A H  A T K I N JUNIOR DEVELOPER  WORK EXPERIENCE  TRDDC  Junior Developer, Jan 2019- till ...
17  candidate_045    P R O F I L E  Young Aspirant looking for roles in data science , analytics and  Machine Learn...
18  candidate_048    Absolutdata Research & Analytics  Machine Learning Intern, Jan 2020 to Till Date   Implemented...
19  candidate_051    S O P H I A  F L O R E S MACHINE LEARNING DEVELOPER(NLP)  WORK EXPERIENCE  eLevaTe LtD.  Machi...
20  candidate_053    PENELOPE TORRES  G R A D U T E  R E S E A R C H  F E L L O W  PROFESSIONAL PROFILE  Passionate...
21  candidate_054    SETH HALL D A T A  S C I E N T I S T  A N D  D E V E L O P E R  SKILLS  Data Scientist, Machin...
22  candidate_056    Christian Von Kelin J U N I O R  A N A L Y S T  Executive Profile  As a junior analyst I curre...
23  candidate_058    S E B A S T I A N  G O L E R ASSOCIATE DATA MANAGER  WORK EXPERIENCE  iNyra Nursing Home  Asso...
24  candidate_059    P R O F I L E  An eclectic researcher , with adept creativity in mobilizing thoughts to  words...
25  candidate_066    HILDA HAWTHORN  P R O F I L E Associate Software Engineer experienced with data  handling and ...
26  candidate_069    RACHEL DAWN D A T A  S C I E N T I S T  SKILLS  Deep learning, Python, SQL , Keras, PyTorch, P...
27  candidate_073    P R O F I L E  I am a junior developer currently working as a Machine Learning  Engineer. I ma...
28  candidate_075    KEIRON PAVARD D A T A  E N G I N E E R  SKILLS  Data Engineer, Data Analytics , Data Visualiza...
29  candidate_077    Benett Campbell F R E S H E R  D A T A  A N A L Y S T  Executive Profile  I am fresher data an...
30  candidate_078    DOMINIC NEIWHALD  P R O F I L E Fresher who is dynamic and defined when it comes to  domain kn...
31  candidate_084    Robert Sergey F R E SHER  Executive Profile  I recently graduated with a B.Tech degree in IT a...
32  candidate_085    HARRY MILES  P R O F I L E Industrious and collaborative individual, Currently looking  for an...
33  candidate_090    DTSl Software Services  Associate Data Engineer, Jul 2019 - Ongoing   Synthesized current busi...
34  candidate_091    CASH FLORES  P R O F I L E Machine learning Enthusiast. Motivated to learn, grow and  excel my...
35  candidate_092    Aya Baker G R A D U A T E  S D E  A N D  B U S I N E S S  A N A L Y S T  Executive Profile  Lo...
36  candidate_094    P R O F I L E  Graduate Looking for roles related to BU analyst and machine  learning.  CDX IN...
37  candidate_095    ERIC MILROY  S Y S T E M  E N G I N E E R  A N D  A N A L Y S T  PROFESSIONAL PROFILE  Versati...
38  candidate_098    VoyaGenius Labs  Software Developer (ML), Dec 2018 - Ongoing   Geocoding and detecting rooftop...
39  candidate_099    Edison Anys M A C H I N E  L E A R N I N G  E N G I N E E R  Executive Profile  Machine Learni...
40  candidate_102    TANNER WILLIAMS  S O L U T I O N S  E N G I N E E R  PROFESSIONAL PROFILE  I am currently work...
41  candidate_103    TESSA MAERS  P R O F I L E A strategic analyst whose skil l  spans over a vast array of  exper...
42  candidate_107    A N D O R A  M C C O N N E L DATA SCIENTIST  WORK EXPERIENCE  HP  Lead Data Scientist, Feb 202...
43  candidate_108    P R O F I L E  I am a fresher business analyst with a knack for building applications that use...
44  candidate_112    Loyalty Rewards Management. Pvt. Ltd.   Business Analyst, Aug 2020 to Till Date    Administeri...
45  candidate_114    G A R E T T E  P A I G E ASSOCIATE SOFTWARE ENGINEER  WORK EXPERIENCE  Delta Info-nancial Serv...
46  candidate_117    MAX LECLERC  P R O F I L E A Fresher Seeking Roles In Machine Learning, Business  Analysis, Da...
47  candidate_118    IRIS GAIDON D A T A  A N A L Y S T  SKILLS  Machine Learning, Data Mining, Artificial Intellig...
48  candidate_119    Willfred Dixon A S S O C I A T E  D A T A  A N A L Y S T  Executive Profile  Data analyst acti...
49  candidate_120    P R O F I L E  Completed BSc in STATISTICS from the Mumbai University . Completed data  scienc...
50  candidate_122    DIANA MILLER  R E S E A R C H  A S S I S T A N T ( M L )  PROFESSIONAL PROFILE  You can find m...
51  candidate_125    ETHAN HUNT P Y T H O N  D E V E L O P E R    SKILLS  Django, Python, Relational databases, Res...
52  candidate_126    Asher Hall D A T A  C O N S U L T A N T  Executive Profile  Interested in helping businesses t...
53  candidate_128    B E U L A  S M I T H S O N DATA ANALYST  WORK EXPERIENCE  Graphene health tech Pvt Ltd  BI Eng...
54  candidate_131    ZACHARY PEREZ  P R O F I L E Good knowledge of C++ and OOPS concepts. Good  knowledge of Data ...
55  candidate_132    DAVID PHIAST A P P L I C A T I O N  D E V E L O P E R  SKILLS  Deep Learning, Machine Learning...
56  candidate_135    KHOLE MOORE G R A D U A T E  R E S E A R C H E R  SKILLS  Machine Learning Engineer, Data Anal...
57  candidate_139    KEISUKE YAMAMOTO  P R O F I L E Professional with 3 months of experience in Web  Development a...
58  candidate_141    P R O F I L E  Software developer with a niche towards end to end machine learning projects . ...
59  candidate_146    LEHNA PATRICK  P R O F I L E I  have worked on grassroot level design of data based  models an...

In [256]:
final_test=df_test.copy()

In [257]:
# Function to calculate length of message excluding space
df_test['body_len'] = df_test['resume'].apply(lambda x: len(x) - x.count(" "))

df_test.head()

def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return round(count/(len(text) - text.count(" ")), 3)*100

df_test['punct%'] = df_test['resume'].apply(lambda x: count_punct(x))

df_test.head()

     CandidateID  ... punct%
0  candidate_004  ...    2.4
1  candidate_005  ...    2.5
2  candidate_014  ...    2.3
3  candidate_016  ...    3.3
4  candidate_017  ...    3.7

[5 rows x 4 columns]

In [258]:
# def clean_text(text):
#     text = "".join([word.lower() for word in text if word not in string.punctuation])
#     tokens = re.split('\W+', text)
#     text = [ps.stem(word) for word in tokens if word not in stopwords]
#     return text

# # TF-IDF
# tfidf_vect = TfidfVectorizer(analyzer=clean_text)
# X_tfidf = tfidf_vect.fit_transform(df_test['resume'])
# X_tfidf_feat = pd.concat([df_test['resume'], df_test['punct%'], pd.DataFrame(X_tfidf.toarray())], axis=1)

# # CountVectorizer
# count_vect = CountVectorizer(analyzer=clean_text)
# X_count = count_vect.fit_transform(df_test['resume'])
# X_count_feat = pd.concat([df_test['resume'], df_test['punct%'], pd.DataFrame(X_count.toarray())], axis=1)

In [259]:
X_tfidf_feat

                                                                                                 resume  ...      1409
0     O L I V I A  S A N T O S CONSULTANT ANALYST  WORK EXPERIENCE  Cognizant, Apr 2020 - Ongoing  C...  ...  0.000000
1     ARMIN FITZGERALD  D A  T  A   M  A  N  A  G  E  R  PROFESSIONAL PROFILE  Expertise in Mathemat...  ...  0.000000
2     GRACE BAILRY M A C H I N E  L E A R N I N G  D E V E L O P M E N T  A N D  D E P L O Y M E N T...  ...  0.000000
3     A M E L I A  M A R T I N DATA SCIENCE MAJOR  WORK EXPERIENCE  NA  ACADEMIC PROFILE  B.Tech(Com...  ...  0.000000
4     P R O F I L E  I am a Junior Machine Learning developer who focuses on data  improvement and m...  ...  0.000000
5     EVELYNN ADAMS  G R A D U A T E  F R E S H E R  PROFESSIONAL PROFILE  I am a recent graduate wh...  ...  0.000000
6     JOSHUA WHITE A S S I S T A N T  S O F T W A R E  A N D  M A C H I N E  L E A R N I N G  E N G ...  ...  0.000000
7     ASI Technologies  Intern,  Dec 2020 - Ongoing  Working as an intern to learn the usage of Neur...  ...  0.000000
8     Eli Scott F R E SHER  Executive Profile  Seeking challenging opportunity in the field of data ...  ...  0.000000
9     P R O F I L E  An avid explorer of analytics in multiple facets pertaining to  production indu...  ...  0.000000
10    CHARLES RODRIGUEZ S O F T W A R E  A N D  P R O J E C T  M A N A G E R  SKILLS  Natural Langua...  ...  0.000000
11    CISCO  Software Developer and Analyst Trainee OCT 2018 - May 2019    Developed Async Functions...  ...  0.000000
12    James May F R E S H E R  S O F T W A R E  D E V E L O P E R  E N G I N E E R  Executive Profil...  ...  0.000000
13    NICOLE BREWER  P O S T  G R A D U A T E  B U S I N E S S A N A L Y S T  PROFESSIONAL PROFILE  ...  ...  0.000000
14    ETHAN GARCIA F R E S H E R  D E V E L O P E R  E N G I N E E R  SKILLS  C++, Python, C, Softwa...  ...  0.000000
15    Ryan Nelson F R E S H E R  S O F T W A R E  D E V E L O P E R    Executive Profile  I consider...  ...  0.000000
16    L E A H  A T K I N JUNIOR DEVELOPER  WORK EXPERIENCE  TRDDC  Junior Developer, Jan 2019- till ...  ...  0.000000
17    P R O F I L E  Young Aspirant looking for roles in data science , analytics and  Machine Learn...  ...  0.000000
18    Absolutdata Research & Analytics  Machine Learning Intern, Jan 2020 to Till Date   Implemented...  ...  0.000000
19    S O P H I A  F L O R E S MACHINE LEARNING DEVELOPER(NLP)  WORK EXPERIENCE  eLevaTe LtD.  Machi...  ...  0.000000
20    PENELOPE TORRES  G R A D U T E  R E S E A R C H  F E L L O W  PROFESSIONAL PROFILE  Passionate...  ...  0.000000
21    SETH HALL D A T A  S C I E N T I S T  A N D  D E V E L O P E R  SKILLS  Data Scientist, Machin...  ...  0.000000
22    Christian Von Kelin J U N I O R  A N A L Y S T  Executive Profile  As a junior analyst I curre...  ...  0.000000
23    S E B A S T I A N  G O L E R ASSOCIATE DATA MANAGER  WORK EXPERIENCE  iNyra Nursing Home  Asso...  ...  0.000000
24    P R O F I L E  An eclectic researcher , with adept creativity in mobilizing thoughts to  words...  ...  0.000000
25    HILDA HAWTHORN  P R O F I L E Associate Software Engineer experienced with data  handling and ...  ...  0.000000
26    RACHEL DAWN D A T A  S C I E N T I S T  SKILLS  Deep learning, Python, SQL , Keras, PyTorch, P...  ...  0.000000
27    P R O F I L E  I am a junior developer currently working as a Machine Learning  Engineer. I ma...  ...  0.000000
28    KEIRON PAVARD D A T A  E N G I N E E R  SKILLS  Data Engineer, Data Analytics , Data Visualiza...  ...  0.000000
29    Benett Campbell F R E S H E R  D A T A  A N A L Y S T  Executive Profile  I am fresher data an...  ...  0.000000
30    DOMINIC NEIWHALD  P R O F I L E Fresher who is dynamic and defined when it comes to  domain kn...  ...  0.000000
31    Robert Sergey F R E SHER  Executive Profile  I recently graduated with a B.Tech degree in IT a...  ...  0.000000
32    HARRY MILES  P R O F I L E Industrious and collaborative individual, Currently looking  for an...  ...  0.000000
33    DTSl Software Services  Associate Data Engineer, Jul 2019 - Ongoing   Synthesized current busi...  ...  0.000000
34    CASH FLORES  P R O F I L E Machine learning Enthusiast. Motivated to learn, grow and  excel my...  ...  0.000000
35    Aya Baker G R A D U A T E  S D E  A N D  B U S I N E S S  A N A L Y S T  Executive Profile  Lo...  ...  0.184555
36    P R O F I L E  Graduate Looking for roles related to BU analyst and machine  learning.  CDX IN...  ...  0.000000
37    ERIC MILROY  S Y S T E M  E N G I N E E R  A N D  A N A L Y S T  PROFESSIONAL PROFILE  Versati...  ...  0.000000
38    VoyaGenius Labs  Software Developer (ML), Dec 2018 - Ongoing   Geocoding and detecting rooftop...  ...  0.000000
39    Edison Anys M A C H I N E  L E A R N I N G  E N G I N E E R  Executive Profile  Machine Learni...  ...  0.000000
40    TANNER WILLIAMS  S O L U T I O N S  E N G I N E E R  PROFESSIONAL PROFILE  I am currently work...  ...  0.000000
41    TESSA MAERS  P R O F I L E A strategic analyst whose skil l  spans over a vast array of  exper...  ...  0.000000
42    A N D O R A  M C C O N N E L DATA SCIENTIST  WORK EXPERIENCE  HP  Lead Data Scientist, Feb 202...  ...  0.000000
43    P R O F I L E  I am a fresher business analyst with a knack for building applications that use...  ...  0.000000
44    Loyalty Rewards Management. Pvt. Ltd.   Business Analyst, Aug 2020 to Till Date    Administeri...  ...  0.000000
45    G A R E T T E  P A I G E ASSOCIATE SOFTWARE ENGINEER  WORK EXPERIENCE  Delta Info-nancial Serv...  ...  0.000000
46    MAX LECLERC  P R O F I L E A Fresher Seeking Roles In Machine Learning, Business  Analysis, Da...  ...  0.000000
47    IRIS GAIDON D A T A  A N A L Y S T  SKILLS  Machine Learning, Data Mining, Artificial Intellig...  ...  0.000000
48    Willfred Dixon A S S O C I A T E  D A T A  A N A L Y S T  Executive Profile  Data analyst acti...  ...  0.000000
49    P R O F I L E  Completed BSc in STATISTICS from the Mumbai University . Completed data  scienc...  ...  0.000000
50    DIANA MILLER  R E S E A R C H  A S S I S T A N T ( M L )  PROFESSIONAL PROFILE  You can find m...  ...  0.000000
51    ETHAN HUNT P Y T H O N  D E V E L O P E R    SKILLS  Django, Python, Relational databases, Res...  ...  0.000000
52    Asher Hall D A T A  C O N S U L T A N T  Executive Profile  Interested in helping businesses t...  ...  0.000000
53    B E U L A  S M I T H S O N DATA ANALYST  WORK EXPERIENCE  Graphene health tech Pvt Ltd  BI Eng...  ...  0.000000
54    ZACHARY PEREZ  P R O F I L E Good knowledge of C++ and OOPS concepts. Good  knowledge of Data ...  ...  0.000000
55    DAVID PHIAST A P P L I C A T I O N  D E V E L O P E R  SKILLS  Deep Learning, Machine Learning...  ...  0.000000
56    KHOLE MOORE G R A D U A T E  R E S E A R C H E R  SKILLS  Machine Learning Engineer, Data Anal...  ...  0.000000
57    KEISUKE YAMAMOTO  P R O F I L E Professional with 3 months of experience in Web  Development a...  ...  0.000000
58    P R O F I L E  Software developer with a niche towards end to end machine learning projects . ...  ...  0.000000
59    LEHNA PATRICK  P R O F I L E I  have worked on grassroot level design of data based  models an...  ...  0.000000

[60 rows x 1412 columns]

In [260]:
final_test.drop(columns=['CandidateID'],inplace=True)

In [261]:
final_test

                                                                                                 resume
0     O L I V I A  S A N T O S CONSULTANT ANALYST  WORK EXPERIENCE  Cognizant, Apr 2020 - Ongoing  C...
1     ARMIN FITZGERALD  D A  T  A   M  A  N  A  G  E  R  PROFESSIONAL PROFILE  Expertise in Mathemat...
2     GRACE BAILRY M A C H I N E  L E A R N I N G  D E V E L O P M E N T  A N D  D E P L O Y M E N T...
3     A M E L I A  M A R T I N DATA SCIENCE MAJOR  WORK EXPERIENCE  NA  ACADEMIC PROFILE  B.Tech(Com...
4     P R O F I L E  I am a Junior Machine Learning developer who focuses on data  improvement and m...
5     EVELYNN ADAMS  G R A D U A T E  F R E S H E R  PROFESSIONAL PROFILE  I am a recent graduate wh...
6     JOSHUA WHITE A S S I S T A N T  S O F T W A R E  A N D  M A C H I N E  L E A R N I N G  E N G ...
7     ASI Technologies  Intern,  Dec 2020 - Ongoing  Working as an intern to learn the usage of Neur...
8     Eli Scott F R E SHER  Executive Profile  Seeking challenging opportunity in the field of data ...
9     P R O F I L E  An avid explorer of analytics in multiple facets pertaining to  production indu...
10    CHARLES RODRIGUEZ S O F T W A R E  A N D  P R O J E C T  M A N A G E R  SKILLS  Natural Langua...
11    CISCO  Software Developer and Analyst Trainee OCT 2018 - May 2019    Developed Async Functions...
12    James May F R E S H E R  S O F T W A R E  D E V E L O P E R  E N G I N E E R  Executive Profil...
13    NICOLE BREWER  P O S T  G R A D U A T E  B U S I N E S S A N A L Y S T  PROFESSIONAL PROFILE  ...
14    ETHAN GARCIA F R E S H E R  D E V E L O P E R  E N G I N E E R  SKILLS  C++, Python, C, Softwa...
15    Ryan Nelson F R E S H E R  S O F T W A R E  D E V E L O P E R    Executive Profile  I consider...
16    L E A H  A T K I N JUNIOR DEVELOPER  WORK EXPERIENCE  TRDDC  Junior Developer, Jan 2019- till ...
17    P R O F I L E  Young Aspirant looking for roles in data science , analytics and  Machine Learn...
18    Absolutdata Research & Analytics  Machine Learning Intern, Jan 2020 to Till Date   Implemented...
19    S O P H I A  F L O R E S MACHINE LEARNING DEVELOPER(NLP)  WORK EXPERIENCE  eLevaTe LtD.  Machi...
20    PENELOPE TORRES  G R A D U T E  R E S E A R C H  F E L L O W  PROFESSIONAL PROFILE  Passionate...
21    SETH HALL D A T A  S C I E N T I S T  A N D  D E V E L O P E R  SKILLS  Data Scientist, Machin...
22    Christian Von Kelin J U N I O R  A N A L Y S T  Executive Profile  As a junior analyst I curre...
23    S E B A S T I A N  G O L E R ASSOCIATE DATA MANAGER  WORK EXPERIENCE  iNyra Nursing Home  Asso...
24    P R O F I L E  An eclectic researcher , with adept creativity in mobilizing thoughts to  words...
25    HILDA HAWTHORN  P R O F I L E Associate Software Engineer experienced with data  handling and ...
26    RACHEL DAWN D A T A  S C I E N T I S T  SKILLS  Deep learning, Python, SQL , Keras, PyTorch, P...
27    P R O F I L E  I am a junior developer currently working as a Machine Learning  Engineer. I ma...
28    KEIRON PAVARD D A T A  E N G I N E E R  SKILLS  Data Engineer, Data Analytics , Data Visualiza...
29    Benett Campbell F R E S H E R  D A T A  A N A L Y S T  Executive Profile  I am fresher data an...
30    DOMINIC NEIWHALD  P R O F I L E Fresher who is dynamic and defined when it comes to  domain kn...
31    Robert Sergey F R E SHER  Executive Profile  I recently graduated with a B.Tech degree in IT a...
32    HARRY MILES  P R O F I L E Industrious and collaborative individual, Currently looking  for an...
33    DTSl Software Services  Associate Data Engineer, Jul 2019 - Ongoing   Synthesized current busi...
34    CASH FLORES  P R O F I L E Machine learning Enthusiast. Motivated to learn, grow and  excel my...
35    Aya Baker G R A D U A T E  S D E  A N D  B U S I N E S S  A N A L Y S T  Executive Profile  Lo...
36    P R O F I L E  Graduate Looking for roles related to BU analyst and machine  learning.  CDX IN...
37    ERIC MILROY  S Y S T E M  E N G I N E E R  A N D  A N A L Y S T  PROFESSIONAL PROFILE  Versati...
38    VoyaGenius Labs  Software Developer (ML), Dec 2018 - Ongoing   Geocoding and detecting rooftop...
39    Edison Anys M A C H I N E  L E A R N I N G  E N G I N E E R  Executive Profile  Machine Learni...
40    TANNER WILLIAMS  S O L U T I O N S  E N G I N E E R  PROFESSIONAL PROFILE  I am currently work...
41    TESSA MAERS  P R O F I L E A strategic analyst whose skil l  spans over a vast array of  exper...
42    A N D O R A  M C C O N N E L DATA SCIENTIST  WORK EXPERIENCE  HP  Lead Data Scientist, Feb 202...
43    P R O F I L E  I am a fresher business analyst with a knack for building applications that use...
44    Loyalty Rewards Management. Pvt. Ltd.   Business Analyst, Aug 2020 to Till Date    Administeri...
45    G A R E T T E  P A I G E ASSOCIATE SOFTWARE ENGINEER  WORK EXPERIENCE  Delta Info-nancial Serv...
46    MAX LECLERC  P R O F I L E A Fresher Seeking Roles In Machine Learning, Business  Analysis, Da...
47    IRIS GAIDON D A T A  A N A L Y S T  SKILLS  Machine Learning, Data Mining, Artificial Intellig...
48    Willfred Dixon A S S O C I A T E  D A T A  A N A L Y S T  Executive Profile  Data analyst acti...
49    P R O F I L E  Completed BSc in STATISTICS from the Mumbai University . Completed data  scienc...
50    DIANA MILLER  R E S E A R C H  A S S I S T A N T ( M L )  PROFESSIONAL PROFILE  You can find m...
51    ETHAN HUNT P Y T H O N  D E V E L O P E R    SKILLS  Django, Python, Relational databases, Res...
52    Asher Hall D A T A  C O N S U L T A N T  Executive Profile  Interested in helping businesses t...
53    B E U L A  S M I T H S O N DATA ANALYST  WORK EXPERIENCE  Graphene health tech Pvt Ltd  BI Eng...
54    ZACHARY PEREZ  P R O F I L E Good knowledge of C++ and OOPS concepts. Good  knowledge of Data ...
55    DAVID PHIAST A P P L I C A T I O N  D E V E L O P E R  SKILLS  Deep Learning, Machine Learning...
56    KHOLE MOORE G R A D U A T E  R E S E A R C H E R  SKILLS  Machine Learning Engineer, Data Anal...
57    KEISUKE YAMAMOTO  P R O F I L E Professional with 3 months of experience in Web  Development a...
58    P R O F I L E  Software developer with a niche towards end to end machine learning projects . ...
59    LEHNA PATRICK  P R O F I L E I  have worked on grassroot level design of data based  models an...

In [262]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(analyzer=clean_text)
X_tfidf = tfidf_vect.fit_transform(final_test['resume'])
print(X_tfidf.shape)
print(tfidf_vect.get_feature_names())

(60, 1410)
['', '084', '1', '101', '11', '15', '2', '2016', '2017', '2018', '2018till', '2019', '2019jun', '2019oct2020', '2019sep', '2019till', '2020', '2020achiev', '2021', '20min', '2min', '3', '35', '4', '90', 'abil', 'abl', 'absolutdata', 'academ', 'accentur', 'access', 'accolad', 'accuraci', 'achiev', 'acp', 'acquaint', 'act', 'actionori', 'activ', 'activit', 'ad', 'adam', 'adapt', 'address', 'adept', 'adhoc', 'administ', 'adnet', 'adsens', 'advanc', 'advisor', 'aegi', 'aerodynam', 'ag', 'agil', 'agricultur', 'ahmedabad', 'ai', 'ait', 'al', 'alarm', 'alert', 'algorithm', 'align', 'alloc', 'allow', 'along', 'also', 'alway', 'amaz', 'amazon', 'amit', 'amn', 'amount', 'analysi', 'analyst', 'analyt', 'analyticsbas', 'analyz', 'android', 'angularj', 'ani', 'ann', 'anna', 'anomali', 'api', 'appear', 'appli', 'applic', 'approach', 'approv', 'apr', 'architect', 'architectur', 'ardent', 'arduino', 'arjuvo', 'armin', 'around', 'array', 'art', 'articl', 'artifici', 'asher', 'asi', 'asm', 'aspect', 'aspir', 'assess', 'assist', 'associ', 'assur', 'async', 'attack', 'attitud', 'audit', 'aug', 'august', 'aurangabad', 'auto', 'autom', 'automat', 'automl', 'automot', 'avail', 'avid', 'aw', 'awar', 'award', 'axiom', 'aya', 'azur', 'b', 'ba', 'baburao', 'bachelor', 'backend', 'background', 'baidu', 'bailri', 'baker', 'banara', 'bangalor', 'bank', 'barrier', 'base', 'basi', 'basket', 'batteri', 'bba', 'bca', 'bcom', 'becom', 'beginn', 'beit', 'belagavi', 'benett', 'bert', 'best', 'better', 'bhimrao', 'bhu', 'bhubaneshwar', 'bi', 'big', 'bigdata', 'bijnor', 'birla', 'bit', 'blake', 'bluem', 'bm', 'bmi', 'board', 'bose', 'bpm', 'brewer', 'bring', 'broaden', 'brokerag', 'bryce', 'bsc', 'bscappli', 'bscstat', 'btech', 'btechchem', 'btechcivil', 'btechcomput', 'btechcs', 'btechelectr', 'btechelectron', 'btechelectronicstelecommun', 'btechinstrument', 'btechmechan', 'btechmetallurgi', 'btechtelecommun', 'bu', 'build', 'builder', 'built', 'busi', 'bvb', 'c', 'ca', 'cafeteria', 'cage', 'calcul', 'calicut', 'campaign', 'campbel', 'capit', 'capitum', 'capston', 'caption', 'captur', 'carbon', 'card', 'caribo', 'case', 'cash', 'casino', 'cassava', 'catalog', 'categor', 'caus', 'cdac', 'cdx', 'celebr', 'certif', 'certifi', 'chaco', 'challeng', 'chand', 'chandigarh', 'chang', 'charact', 'charl', 'chat', 'chatbot', 'check', 'chemic', 'chennai', 'chess', 'choic', 'christian', 'cisco', 'cit', 'citi', 'civil', 'claim', 'class', 'classic', 'classif', 'clean', 'cleans', 'client', 'climb', 'close', 'closest', 'cloud', 'cloudbas', 'cluster', 'cnn', 'co', 'code', 'cogniz', 'cognizantdec', 'cogno', 'collabor', 'collect', 'colleg', 'color', 'colton', 'come', 'comment', 'commerc', 'commit', 'commun', 'compani', 'compens', 'compet', 'complet', 'complex', 'compon', 'comprehend', 'comput', 'concept', 'concern', 'condit', 'configur', 'conflict', 'congress', 'connect', 'consid', 'consult', 'contain', 'contribut', 'contributor', 'control', 'convers', 'convert', 'correct', 'correctli', 'correl', 'correspondencedist', 'cost', 'could', 'counter', 'coupl', 'cours', 'crave', 'creat', 'creation', 'creativ', 'credit', 'cricket', 'crisprcas9', 'cron', 'crust', 'css', 'current', 'curricular', 'custom', 'cut', 'cybersecur', 'cycl', 'daffodil', 'daili', 'daman', 'dashboard', 'data', 'databas', 'databrick', 'datacamp', 'dataset', 'date', 'davi', 'david', 'dawn', 'dax', 'day', 'dd', 'deal', 'dealer', 'dealt', 'debug', 'dec', 'decid', 'decis', 'decomposit', 'deep', 'deepspeech', 'defect', 'defin', 'degre', 'delafey', 'delhi', 'delimit', 'deliv', 'deliveri', 'dell', 'delta', 'demand', 'demonstr', 'dena', 'depart', 'deploy', 'depth', 'descriptor', 'design', 'desir', 'detect', 'determin', 'develop', 'developernlp', 'diana', 'differ', 'diploma', 'directori', 'dirichlet', 'disast', 'diseas', 'distribut', 'diu', 'dixon', 'django', 'dlib', 'dm', 'dnarna', 'dnn', 'docker', 'dockerbas', 'document', 'domain', 'domin', 'done', 'dotnet', 'dr', 'drive', 'driven', 'driver', 'drop', 'druck', 'dtsl', 'dual', 'due', 'dvr', 'dylan', 'dynam', 'e', 'eam', 'easili', 'ec2', 'ece', 'ecep', 'eclect', 'econom', 'eda', 'edison', 'eduardo', 'educ', 'effici', 'electr', 'electron', 'elev', 'eli', 'elo', 'elucidata', 'embed', 'emd', 'emertx', 'emi', 'emot', 'emper', 'empir', 'employ', 'employe', 'empryean', 'encod', 'end', 'endeavor', 'endtoend', 'engin', 'engine', 'engineerdevelop', 'engineersolut', 'english', 'engross', 'enhanc', 'enov', 'enrol', 'enthusiast', 'entir', 'entiti', 'entri', 'environ', 'ep', 'equip', 'eric', 'erp', 'etc', 'ethan', 'ethic', 'etl', 'ev', 'evalu', 'evangelist', 'evelynn', 'excel', 'excit', 'execut', 'exhibit', 'eximiu', 'exist', 'experi', 'experienc', 'expertis', 'explor', 'export', 'extens', 'extra', 'extract', 'extracurricular', 'f', 'f1score', 'face', 'facet', 'factual', 'fals', 'familiar', 'fascin', 'fashion', 'fast', 'faster', 'fault', 'faulti', 'fcn', 'feasibl', 'featur', 'feb', 'feder', 'feed', 'feeder', 'fellow', 'fellowship', 'field', 'file', 'final', 'financ', 'financi', 'find', 'finder', 'firm', 'fitzgerald', 'flask', 'flore', 'flutter', 'focus', 'fold', 'forecast', 'forest', 'format', 'formul', 'forward', 'foundat', 'frame', 'frequenc', 'fresher', 'front', 'frontend', 'fuel', 'full', 'function', 'fund', 'fundament', 'futur', 'g', 'gaidon', 'gandhi', 'garcia', 'gather', 'gdmn', 'ge', 'gener', 'genom', 'geocod', 'geograph', 'german', 'germani', 'get', 'ghaziabad', 'git', 'github', 'give', 'given', 'global', 'goa', 'goal', 'gobind', 'godavari', 'gold', 'gomez', 'good', 'googl', 'got', 'govern', 'goyal', 'grace', 'grade', 'graduat', 'grape', 'graph', 'graphen', 'graphic', 'grasp', 'grassroot', 'great', 'group', 'grow', 'growth', 'gru', 'gurgaon', 'guru', 'gurukulnagar', 'gzn', 'h', 'hadoop', 'haldia', 'hall', 'hamirpur', 'handl', 'handson', 'handwrit', 'hannov', 'hardwork', 'harper', 'harri', 'haskel', 'hawthorn', 'head', 'health', 'healthcar', 'help', 'hernandez', 'heroku', 'heurist', 'highend', 'highest', 'highli', 'highlight', 'hiit', 'hilda', 'hill', 'hindi', 'hindu', 'histori', 'hit', 'hive', 'hoc', 'hold', 'hollywood', 'home', 'hon', 'hone', 'hopkin', 'hosiyarpur', 'hotel', 'hous', 'hp', 'hr', 'html', 'huan', 'huggingfac', 'hunt', 'hybrid', 'hyderabad', 'iabac', 'iam', 'ibm', 'idea', 'identif', 'identifi', 'igenc', 'iiit', 'iisc', 'iit', 'imag', 'imarticu', 'impact', 'impig', 'implement', 'import', 'improv', 'imput', 'incid', 'includ', 'incom', 'increas', 'inderprastha', 'india', 'indian', 'indira', 'individu', 'indivudu', 'indusoft', 'industri', 'infer', 'infonanci', 'inform', 'infotech', 'ing', 'initi', 'innoplexu', 'innov', 'input', 'insid', 'insight', 'insitut', 'institut', 'integr', 'intel', 'intellig', 'intens', 'interact', 'interest', 'intern', 'interperson', 'interpret', 'intrigu', 'introduct', 'invest', 'involv', 'inyra', 'iot', 'iri', 'issu', 'j', 'jaipur', 'jame', 'jan', 'java', 'javascript', 'jawaharl', 'jb', 'jcp', 'jenkin', 'jharkhand', 'jira', 'jntu', 'job', 'jodhpur', 'john', 'join', 'jonathan', 'joshua', 'jp', 'ju', 'jul', 'juli', 'julia', 'jun', 'junior', 'jupyt', 'justdial', 'jyothi', 'k', 'kancheepuram', 'kanpur', 'kayla', 'kcce', 'keegan', 'keen', 'keiron', 'keisuk', 'kelin', 'kera', 'key', 'kharagpur', 'khole', 'kimberli', 'kind', 'kle', 'kln', 'kmean', 'knack', 'knn', 'knowledg', 'kormand', 'kottam', 'kruzr', 'kt', 'ktm', 'kubernet', 'kvcc20', 'kvit', 'l', 'l1', 'l2', 'lab', 'laboratori', 'ladder', 'lake', 'landmark', 'lando', 'landscap', 'languag', 'larg', 'largescal', 'larsen', 'layer', 'lead', 'lean', 'learn', 'learnig', 'leav', 'leclerc', 'legaci', 'lehna', 'lemmat', 'lend', 'lesli', 'level', 'leverag', 'librari', 'life', 'lifecycl', 'light', 'like', 'limit', 'linear', 'literatur', 'load', 'loan', 'local', 'lodg', 'logic', 'logist', 'long', 'look', 'lookup', 'loss', 'lot', 'low', 'loyalti', 'lpu', 'ls', 'lsmw', 'lstm', 'lt', 'ltd', 'lucknow', 'lydia', 'machin', 'maer', 'magazin', 'mahindra', 'mail', 'main', 'maintain', 'mainten', 'major', 'make', 'manag', 'mani', 'manip', 'manipul', 'manner', 'manual', 'mar', 'march', 'mark', 'market', 'master', 'masteri', 'masterstrok', 'match', 'materi', 'mathemat', 'matlab', 'matplotlib', 'max', 'may', 'mca', 'measur', 'mechan', 'mecomput', 'medalist', 'media', 'medic', 'member', 'memori', 'mental', 'mestli', 'metalik', 'metallurgi', 'method', 'methodolog', 'mi', 'microaverag', 'microsoft', 'middlewar', 'might', 'mile', 'miller', 'milroy', 'mine', 'minim', 'miss', 'ml', 'mobil', 'mobilenetv2', 'mode', 'model', 'modern', 'modul', 'money', 'mongodb', 'monitor', 'monje', 'month', 'moor', 'morgan', 'motiv', 'movi', 'msartifici', 'msc', 'mtech', 'mtechchem', 'mtechintegr', 'much', 'multipl', 'mumbai', 'murshidabad', 'music', 'mysor', 'mysql', 'n', 'na', 'name', 'nand', 'nanyang', 'narse', 'nashik', 'nasik', 'nation', 'natur', 'need', 'nehru', 'neiwhald', 'nelson', 'network', 'networkbas', 'neural', 'neuratech', 'new', 'news', 'nich', 'nicol', 'nidhiram', 'nit', 'nk', 'nlp', 'nlpbase', 'nltk', 'nodej', 'noida', 'nolan', 'norm', 'nosql', 'nov', 'nse', 'number', 'numer', 'numpi', 'nurs', 'nurtur', 'object', 'objectori', 'oclosia', 'ocr', 'ocrbas', 'oct', 'octillion', 'offer', 'old', 'olymp', 'ondevic', 'ongo', 'ontolog', 'oop', 'open', 'opencv', 'opensourc', 'oper', 'opportun', 'optim', 'oracledb', 'order', 'organ', 'orient', 'os', 'osra', 'outcom', 'outlook', 'overcom', 'p', 'pain', 'pair', 'panda', 'paper', 'part', 'particip', 'parttim', 'passeng', 'passion', 'patient', 'patil', 'patrick', 'pattern', 'pavard', 'pdf', 'pdfextractor', 'penelop', 'peopl', 'per', 'perez', 'perform', 'period', 'person', 'pertain', 'pg', 'pgg', 'phiast', 'phish', 'php', 'pick', 'pictograph', 'pilani', 'pioneer', 'pipelin', 'pivot', 'place', 'plan', 'platform', 'player', 'plot', 'plotli', 'point', 'polar', 'polish', 'popular', 'portal', 'possibl', 'post', 'postgresql', 'power', 'powerbi', 'ppc', 'practic', 'pranveer', 'predict', 'prepar', 'preprocess', 'prescrib', 'present', 'pretrain', 'price', 'problem', 'procedur', 'process', 'procur', 'produc', 'product', 'production', 'profession', 'profici', 'profil', 'profit', 'program', 'programm', 'progress', 'project', 'promis', 'proof', 'properti', 'prophet', 'propos', 'protect', 'provid', 'prune', 'publish', 'pune', 'pursu', 'pvt', 'pyspark', 'python', 'pythonist', 'pytorch', 'qa', 'qualif', 'qualiti', 'queri', 'quick', 'r', 'rachel', 'rais', 'random', 'rasa', 'rate', 'reach', 'reaction', 'reactj', 'readi', 'real', 'realli', 'realtim', 'reason', 'recent', 'recognit', 'recommend', 'record', 'redshift', 'reduc', 'refin', 'regress', 'regular', 'reinforc', 'relat', 'relationship', 'report', 'represent', 'requir', 'research', 'respons', 'rest', 'restapi', 'restor', 'result', 'retriev', 'reward', 'rich', 'right', 'risk', 'rm', 'rnn', 'rnt', 'robert', 'robot', 'rodriguez', 'role', 'rooftop', 'rubi', 'ryan', 'sa', 'saa', 'safe', 'safeti', 'sagemak', 'sai', 'sail', 'sailpoint', 'sale', 'salesforc', 'sampl', 'sanghvi', 'sap', 'sapc', 'satisfact', 'scala', 'scalabl', 'scale', 'scanner', 'scenario', 'schedul', 'school', 'scienc', 'scientist', 'scikit', 'scope', 'scorecard', 'scott', 'scratch', 'script', 'sde', 'sdlc', 'seaborn', 'search', 'sector', 'secur', 'seek', 'segment', 'select', 'semiconductor', 'sen', 'send', 'senior', 'sensor', 'sentenc', 'sentiment', 'sep', 'sergey', 'seri', 'servic', 'set', 'seth', 'sever', 'sgg', 'sgn', 'shang', 'share', 'sher', 'shivaji', 'short', 'shri', 'side', 'sighania', 'silnivesh', 'simon', 'simplifi', 'simul', 'simultan', 'singh', 'singhji', 'sit', 'size', 'skil', 'skill', 'small', 'smaller', 'smart', 'smartphon', 'sme', 'smile', 'smv', 'softwar', 'soh', 'solapur', 'solut', 'solv', 'sophist', 'sorter', 'sound', 'sourc', 'space', 'spaci', 'span', 'spark', 'sparkocr', 'special', 'specialist', 'specif', 'splice', 'spp', 'spsc', 'spss', 'sql', 'srd', 'sri', 'ssm', 'stack', 'stakehold', 'stanford', 'start', 'stat', 'statement', 'statist', 'steel', 'stem', 'stori', 'strateg', 'strategi', 'strive', 'strong', 'structur', 'student', 'studi', 'subject', 'succeed', 'success', 'suggest', 'suion', 'summar', 'summari', 'supervis', 'suppli', 'support', 'survey', 'svm', 'svn', 'svu', 'swaroop', 'switch', 'symbiosi', 'synthes', 'system', 'systemdm', 'tabl', 'tableau', 'take', 'taken', 'tanner', 'target', 'task', 'tat', 'tata', 'teach', 'team', 'tech', 'technic', 'techniqu', 'technolog', 'telecommun', 'tender', 'tensoflow', 'tensorflow', 'tensorflowj', 'term', 'tessa', 'tesseract', 'test', 'testdom', 'text', 'texual', 'theft', 'thoma', 'thought', 'ti', 'til', 'till', 'time', 'timeseri', 'tirupati', 'tmlf', 'togeth', 'toler', 'tool', 'topic', 'tornado', 'torr', 'toubro', 'toward', 'toxic', 'track', 'tradit', 'traffic', 'train', 'traine', 'trainer', 'trait', 'transact', 'transform', 'transit', 'translat', 'trddc', 'tread', 'treatment', 'tree', 'trend', 'tri', 'ttr', 'tuc', 'type', 'u', 'udac', 'udemi', 'ui', 'uk', 'ukbas', 'understand', 'understood', 'unit', 'univers', 'unlabel', 'unstructur', 'unsupervis', 'usag', 'use', 'user', 'util', 'uttarpradesh', 'v', 'valid', 'valu', 'valuabl', 'valuat', 'variabl', 'varieti', 'variou', 'vast', 'vba', 'veget', 'vellor', 'venkateshwara', 'ventur', 'verdict', 'verifi', 'versatil', 'version', 'via', 'virendra', 'vision', 'visual', 'visualis', 'vit', 'von', 'voyageniu', 'vw', 'w', 'wafer', 'walchand', 'walker', 'want', 'warang', 'wareh', 'warehous', 'wasnt', 'watson', 'way', 'web', 'webscrap', 'websit', 'well', 'whether', 'white', 'whose', 'willfr', 'william', 'willing', 'windmil', 'within', 'wood', 'word', 'work', 'workday', 'workshop', 'would', 'wrangl', 'write', 'wrt', 'wsm', 'x', 'xml', 'yamamoto', 'year', 'yolo', 'young', 'zachari', 'zeal', 'zf', 'zigsaw']

In [263]:
X_tfidf_df_test = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vect.get_feature_names())
X_tfidf_df_test.head(10)

             084    1  101   11   15  ...  yolo  young  zachari  zeal   zf  zigsaw
0  0.030578  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
1  0.031836  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
2  0.022182  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
3  0.029624  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
4  0.024405  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
5  0.028169  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
6  0.026038  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
7  0.030488  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
8  0.041629  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0
9  0.027372  0.0  0.0  0.0  0.0  0.0  ...   0.0    0.0      0.0   0.0  0.0     0.0

[10 rows x 1410 columns]

In [264]:
print(X_tfidf_df_test.loc[(X_tfidf_df_test!=0).any(axis=1)])

                   084         1  ...      zeal        zf    zigsaw
0   0.030578  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1   0.031836  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2   0.022182  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3   0.029624  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4   0.024405  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5   0.028169  0.000000  0.000000  ...  0.000000  0.000000  0.000000
6   0.026038  0.000000  0.000000  ...  0.000000  0.000000  0.000000
7   0.030488  0.000000  0.000000  ...  0.000000  0.000000  0.000000
8   0.041629  0.000000  0.000000  ...  0.000000  0.000000  0.000000
9   0.027372  0.000000  0.000000  ...  0.000000  0.000000  0.000000
10  0.027351  0.000000  0.000000  ...  0.000000  0.000000  0.000000
11  0.031658  0.000000  0.000000  ...  0.000000  0.000000  0.000000
12  0.029667  0.000000  0.000000  ...  0.000000  0.000000  0.000000
13  0.031154  0.000000  0.000000  ...  0.000000  0.000000  0.000000
14  0.037134  0.000000  0.000000  ...  0.000000  0.000000  0.000000
15  0.035911  0.000000  0.000000  ...  0.000000  0.000000  0.000000
16  0.033826  0.000000  0.000000  ...  0.000000  0.000000  0.000000
17  0.031814  0.000000  0.000000  ...  0.000000  0.000000  0.000000
18  0.030394  0.000000  0.000000  ...  0.000000  0.000000  0.000000
19  0.033931  0.000000  0.000000  ...  0.000000  0.000000  0.000000
20  0.027991  0.000000  0.000000  ...  0.123657  0.000000  0.000000
21  0.031552  0.000000  0.000000  ...  0.000000  0.000000  0.000000
22  0.033392  0.000000  0.000000  ...  0.000000  0.000000  0.000000
23  0.033673  0.000000  0.000000  ...  0.000000  0.000000  0.000000
24  0.032702  0.000000  0.000000  ...  0.000000  0.000000  0.000000
25  0.026528  0.000000  0.000000  ...  0.000000  0.000000  0.000000
26  0.022550  0.099619  0.000000  ...  0.000000  0.000000  0.000000
27  0.028055  0.000000  0.000000  ...  0.000000  0.000000  0.000000
28  0.029900  0.000000  0.000000  ...  0.000000  0.132089  0.000000
29  0.022736  0.000000  0.000000  ...  0.000000  0.000000  0.000000
30  0.028515  0.000000  0.000000  ...  0.000000  0.000000  0.000000
31  0.038919  0.000000  0.000000  ...  0.000000  0.000000  0.000000
32  0.030594  0.000000  0.000000  ...  0.000000  0.000000  0.000000
33  0.029100  0.000000  0.128555  ...  0.000000  0.000000  0.000000
34  0.036409  0.000000  0.000000  ...  0.000000  0.000000  0.000000
35  0.041776  0.000000  0.000000  ...  0.000000  0.000000  0.184555
36  0.032167  0.000000  0.000000  ...  0.000000  0.000000  0.000000
37  0.031910  0.000000  0.000000  ...  0.000000  0.000000  0.000000
38  0.034853  0.000000  0.000000  ...  0.000000  0.000000  0.000000
39  0.031508  0.000000  0.000000  ...  0.000000  0.000000  0.000000
40  0.026292  0.000000  0.000000  ...  0.000000  0.000000  0.000000
41  0.025369  0.000000  0.000000  ...  0.000000  0.000000  0.000000
42  0.024264  0.000000  0.000000  ...  0.000000  0.000000  0.000000
43  0.026621  0.000000  0.000000  ...  0.000000  0.000000  0.000000
44  0.028626  0.000000  0.000000  ...  0.000000  0.000000  0.000000
45  0.024967  0.000000  0.000000  ...  0.000000  0.000000  0.000000
46  0.029982  0.000000  0.000000  ...  0.000000  0.000000  0.000000
47  0.025350  0.000000  0.000000  ...  0.000000  0.000000  0.000000
48  0.035203  0.000000  0.000000  ...  0.000000  0.000000  0.000000
49  0.026131  0.000000  0.000000  ...  0.000000  0.000000  0.000000
50  0.033146  0.000000  0.000000  ...  0.000000  0.000000  0.000000
51  0.026366  0.000000  0.000000  ...  0.000000  0.000000  0.000000
52  0.031318  0.000000  0.000000  ...  0.000000  0.000000  0.000000
53  0.028609  0.000000  0.000000  ...  0.000000  0.000000  0.000000
54  0.025549  0.000000  0.000000  ...  0.000000  0.000000  0.000000
55  0.024881  0.000000  0.000000  ...  0.000000  0.000000  0.000000
56  0.031436  0.000000  0.000000  ...  0.000000  0.000000  0.000000
57  0.026197  0.000000  0.000000  ...  0.000000  0.000000  0.000000
58  0.027643  0.000000  0.000000  ...  0.000000  0.000000  0.000000
59  0.028326  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[60 rows x 1410 columns]

In [265]:
from sklearn.feature_extraction.text import CountVectorizer

ngram_vect = CountVectorizer(ngram_range=(2,2),analyzer=clean_text) # It applies only bigram vectorizer
X_counts = ngram_vect.fit_transform(final_test['resume'])
print(X_counts.shape)
print(ngram_vect.get_feature_names())
X_counts_df_test = pd.DataFrame(X_counts.toarray(), columns=ngram_vect.get_feature_names())
X_counts_df_test.head(10)

(60, 1410)
['', '084', '1', '101', '11', '15', '2', '2016', '2017', '2018', '2018till', '2019', '2019jun', '2019oct2020', '2019sep', '2019till', '2020', '2020achiev', '2021', '20min', '2min', '3', '35', '4', '90', 'abil', 'abl', 'absolutdata', 'academ', 'accentur', 'access', 'accolad', 'accuraci', 'achiev', 'acp', 'acquaint', 'act', 'actionori', 'activ', 'activit', 'ad', 'adam', 'adapt', 'address', 'adept', 'adhoc', 'administ', 'adnet', 'adsens', 'advanc', 'advisor', 'aegi', 'aerodynam', 'ag', 'agil', 'agricultur', 'ahmedabad', 'ai', 'ait', 'al', 'alarm', 'alert', 'algorithm', 'align', 'alloc', 'allow', 'along', 'also', 'alway', 'amaz', 'amazon', 'amit', 'amn', 'amount', 'analysi', 'analyst', 'analyt', 'analyticsbas', 'analyz', 'android', 'angularj', 'ani', 'ann', 'anna', 'anomali', 'api', 'appear', 'appli', 'applic', 'approach', 'approv', 'apr', 'architect', 'architectur', 'ardent', 'arduino', 'arjuvo', 'armin', 'around', 'array', 'art', 'articl', 'artifici', 'asher', 'asi', 'asm', 'aspect', 'aspir', 'assess', 'assist', 'associ', 'assur', 'async', 'attack', 'attitud', 'audit', 'aug', 'august', 'aurangabad', 'auto', 'autom', 'automat', 'automl', 'automot', 'avail', 'avid', 'aw', 'awar', 'award', 'axiom', 'aya', 'azur', 'b', 'ba', 'baburao', 'bachelor', 'backend', 'background', 'baidu', 'bailri', 'baker', 'banara', 'bangalor', 'bank', 'barrier', 'base', 'basi', 'basket', 'batteri', 'bba', 'bca', 'bcom', 'becom', 'beginn', 'beit', 'belagavi', 'benett', 'bert', 'best', 'better', 'bhimrao', 'bhu', 'bhubaneshwar', 'bi', 'big', 'bigdata', 'bijnor', 'birla', 'bit', 'blake', 'bluem', 'bm', 'bmi', 'board', 'bose', 'bpm', 'brewer', 'bring', 'broaden', 'brokerag', 'bryce', 'bsc', 'bscappli', 'bscstat', 'btech', 'btechchem', 'btechcivil', 'btechcomput', 'btechcs', 'btechelectr', 'btechelectron', 'btechelectronicstelecommun', 'btechinstrument', 'btechmechan', 'btechmetallurgi', 'btechtelecommun', 'bu', 'build', 'builder', 'built', 'busi', 'bvb', 'c', 'ca', 'cafeteria', 'cage', 'calcul', 'calicut', 'campaign', 'campbel', 'capit', 'capitum', 'capston', 'caption', 'captur', 'carbon', 'card', 'caribo', 'case', 'cash', 'casino', 'cassava', 'catalog', 'categor', 'caus', 'cdac', 'cdx', 'celebr', 'certif', 'certifi', 'chaco', 'challeng', 'chand', 'chandigarh', 'chang', 'charact', 'charl', 'chat', 'chatbot', 'check', 'chemic', 'chennai', 'chess', 'choic', 'christian', 'cisco', 'cit', 'citi', 'civil', 'claim', 'class', 'classic', 'classif', 'clean', 'cleans', 'client', 'climb', 'close', 'closest', 'cloud', 'cloudbas', 'cluster', 'cnn', 'co', 'code', 'cogniz', 'cognizantdec', 'cogno', 'collabor', 'collect', 'colleg', 'color', 'colton', 'come', 'comment', 'commerc', 'commit', 'commun', 'compani', 'compens', 'compet', 'complet', 'complex', 'compon', 'comprehend', 'comput', 'concept', 'concern', 'condit', 'configur', 'conflict', 'congress', 'connect', 'consid', 'consult', 'contain', 'contribut', 'contributor', 'control', 'convers', 'convert', 'correct', 'correctli', 'correl', 'correspondencedist', 'cost', 'could', 'counter', 'coupl', 'cours', 'crave', 'creat', 'creation', 'creativ', 'credit', 'cricket', 'crisprcas9', 'cron', 'crust', 'css', 'current', 'curricular', 'custom', 'cut', 'cybersecur', 'cycl', 'daffodil', 'daili', 'daman', 'dashboard', 'data', 'databas', 'databrick', 'datacamp', 'dataset', 'date', 'davi', 'david', 'dawn', 'dax', 'day', 'dd', 'deal', 'dealer', 'dealt', 'debug', 'dec', 'decid', 'decis', 'decomposit', 'deep', 'deepspeech', 'defect', 'defin', 'degre', 'delafey', 'delhi', 'delimit', 'deliv', 'deliveri', 'dell', 'delta', 'demand', 'demonstr', 'dena', 'depart', 'deploy', 'depth', 'descriptor', 'design', 'desir', 'detect', 'determin', 'develop', 'developernlp', 'diana', 'differ', 'diploma', 'directori', 'dirichlet', 'disast', 'diseas', 'distribut', 'diu', 'dixon', 'django', 'dlib', 'dm', 'dnarna', 'dnn', 'docker', 'dockerbas', 'document', 'domain', 'domin', 'done', 'dotnet', 'dr', 'drive', 'driven', 'driver', 'drop', 'druck', 'dtsl', 'dual', 'due', 'dvr', 'dylan', 'dynam', 'e', 'eam', 'easili', 'ec2', 'ece', 'ecep', 'eclect', 'econom', 'eda', 'edison', 'eduardo', 'educ', 'effici', 'electr', 'electron', 'elev', 'eli', 'elo', 'elucidata', 'embed', 'emd', 'emertx', 'emi', 'emot', 'emper', 'empir', 'employ', 'employe', 'empryean', 'encod', 'end', 'endeavor', 'endtoend', 'engin', 'engine', 'engineerdevelop', 'engineersolut', 'english', 'engross', 'enhanc', 'enov', 'enrol', 'enthusiast', 'entir', 'entiti', 'entri', 'environ', 'ep', 'equip', 'eric', 'erp', 'etc', 'ethan', 'ethic', 'etl', 'ev', 'evalu', 'evangelist', 'evelynn', 'excel', 'excit', 'execut', 'exhibit', 'eximiu', 'exist', 'experi', 'experienc', 'expertis', 'explor', 'export', 'extens', 'extra', 'extract', 'extracurricular', 'f', 'f1score', 'face', 'facet', 'factual', 'fals', 'familiar', 'fascin', 'fashion', 'fast', 'faster', 'fault', 'faulti', 'fcn', 'feasibl', 'featur', 'feb', 'feder', 'feed', 'feeder', 'fellow', 'fellowship', 'field', 'file', 'final', 'financ', 'financi', 'find', 'finder', 'firm', 'fitzgerald', 'flask', 'flore', 'flutter', 'focus', 'fold', 'forecast', 'forest', 'format', 'formul', 'forward', 'foundat', 'frame', 'frequenc', 'fresher', 'front', 'frontend', 'fuel', 'full', 'function', 'fund', 'fundament', 'futur', 'g', 'gaidon', 'gandhi', 'garcia', 'gather', 'gdmn', 'ge', 'gener', 'genom', 'geocod', 'geograph', 'german', 'germani', 'get', 'ghaziabad', 'git', 'github', 'give', 'given', 'global', 'goa', 'goal', 'gobind', 'godavari', 'gold', 'gomez', 'good', 'googl', 'got', 'govern', 'goyal', 'grace', 'grade', 'graduat', 'grape', 'graph', 'graphen', 'graphic', 'grasp', 'grassroot', 'great', 'group', 'grow', 'growth', 'gru', 'gurgaon', 'guru', 'gurukulnagar', 'gzn', 'h', 'hadoop', 'haldia', 'hall', 'hamirpur', 'handl', 'handson', 'handwrit', 'hannov', 'hardwork', 'harper', 'harri', 'haskel', 'hawthorn', 'head', 'health', 'healthcar', 'help', 'hernandez', 'heroku', 'heurist', 'highend', 'highest', 'highli', 'highlight', 'hiit', 'hilda', 'hill', 'hindi', 'hindu', 'histori', 'hit', 'hive', 'hoc', 'hold', 'hollywood', 'home', 'hon', 'hone', 'hopkin', 'hosiyarpur', 'hotel', 'hous', 'hp', 'hr', 'html', 'huan', 'huggingfac', 'hunt', 'hybrid', 'hyderabad', 'iabac', 'iam', 'ibm', 'idea', 'identif', 'identifi', 'igenc', 'iiit', 'iisc', 'iit', 'imag', 'imarticu', 'impact', 'impig', 'implement', 'import', 'improv', 'imput', 'incid', 'includ', 'incom', 'increas', 'inderprastha', 'india', 'indian', 'indira', 'individu', 'indivudu', 'indusoft', 'industri', 'infer', 'infonanci', 'inform', 'infotech', 'ing', 'initi', 'innoplexu', 'innov', 'input', 'insid', 'insight', 'insitut', 'institut', 'integr', 'intel', 'intellig', 'intens', 'interact', 'interest', 'intern', 'interperson', 'interpret', 'intrigu', 'introduct', 'invest', 'involv', 'inyra', 'iot', 'iri', 'issu', 'j', 'jaipur', 'jame', 'jan', 'java', 'javascript', 'jawaharl', 'jb', 'jcp', 'jenkin', 'jharkhand', 'jira', 'jntu', 'job', 'jodhpur', 'john', 'join', 'jonathan', 'joshua', 'jp', 'ju', 'jul', 'juli', 'julia', 'jun', 'junior', 'jupyt', 'justdial', 'jyothi', 'k', 'kancheepuram', 'kanpur', 'kayla', 'kcce', 'keegan', 'keen', 'keiron', 'keisuk', 'kelin', 'kera', 'key', 'kharagpur', 'khole', 'kimberli', 'kind', 'kle', 'kln', 'kmean', 'knack', 'knn', 'knowledg', 'kormand', 'kottam', 'kruzr', 'kt', 'ktm', 'kubernet', 'kvcc20', 'kvit', 'l', 'l1', 'l2', 'lab', 'laboratori', 'ladder', 'lake', 'landmark', 'lando', 'landscap', 'languag', 'larg', 'largescal', 'larsen', 'layer', 'lead', 'lean', 'learn', 'learnig', 'leav', 'leclerc', 'legaci', 'lehna', 'lemmat', 'lend', 'lesli', 'level', 'leverag', 'librari', 'life', 'lifecycl', 'light', 'like', 'limit', 'linear', 'literatur', 'load', 'loan', 'local', 'lodg', 'logic', 'logist', 'long', 'look', 'lookup', 'loss', 'lot', 'low', 'loyalti', 'lpu', 'ls', 'lsmw', 'lstm', 'lt', 'ltd', 'lucknow', 'lydia', 'machin', 'maer', 'magazin', 'mahindra', 'mail', 'main', 'maintain', 'mainten', 'major', 'make', 'manag', 'mani', 'manip', 'manipul', 'manner', 'manual', 'mar', 'march', 'mark', 'market', 'master', 'masteri', 'masterstrok', 'match', 'materi', 'mathemat', 'matlab', 'matplotlib', 'max', 'may', 'mca', 'measur', 'mechan', 'mecomput', 'medalist', 'media', 'medic', 'member', 'memori', 'mental', 'mestli', 'metalik', 'metallurgi', 'method', 'methodolog', 'mi', 'microaverag', 'microsoft', 'middlewar', 'might', 'mile', 'miller', 'milroy', 'mine', 'minim', 'miss', 'ml', 'mobil', 'mobilenetv2', 'mode', 'model', 'modern', 'modul', 'money', 'mongodb', 'monitor', 'monje', 'month', 'moor', 'morgan', 'motiv', 'movi', 'msartifici', 'msc', 'mtech', 'mtechchem', 'mtechintegr', 'much', 'multipl', 'mumbai', 'murshidabad', 'music', 'mysor', 'mysql', 'n', 'na', 'name', 'nand', 'nanyang', 'narse', 'nashik', 'nasik', 'nation', 'natur', 'need', 'nehru', 'neiwhald', 'nelson', 'network', 'networkbas', 'neural', 'neuratech', 'new', 'news', 'nich', 'nicol', 'nidhiram', 'nit', 'nk', 'nlp', 'nlpbase', 'nltk', 'nodej', 'noida', 'nolan', 'norm', 'nosql', 'nov', 'nse', 'number', 'numer', 'numpi', 'nurs', 'nurtur', 'object', 'objectori', 'oclosia', 'ocr', 'ocrbas', 'oct', 'octillion', 'offer', 'old', 'olymp', 'ondevic', 'ongo', 'ontolog', 'oop', 'open', 'opencv', 'opensourc', 'oper', 'opportun', 'optim', 'oracledb', 'order', 'organ', 'orient', 'os', 'osra', 'outcom', 'outlook', 'overcom', 'p', 'pain', 'pair', 'panda', 'paper', 'part', 'particip', 'parttim', 'passeng', 'passion', 'patient', 'patil', 'patrick', 'pattern', 'pavard', 'pdf', 'pdfextractor', 'penelop', 'peopl', 'per', 'perez', 'perform', 'period', 'person', 'pertain', 'pg', 'pgg', 'phiast', 'phish', 'php', 'pick', 'pictograph', 'pilani', 'pioneer', 'pipelin', 'pivot', 'place', 'plan', 'platform', 'player', 'plot', 'plotli', 'point', 'polar', 'polish', 'popular', 'portal', 'possibl', 'post', 'postgresql', 'power', 'powerbi', 'ppc', 'practic', 'pranveer', 'predict', 'prepar', 'preprocess', 'prescrib', 'present', 'pretrain', 'price', 'problem', 'procedur', 'process', 'procur', 'produc', 'product', 'production', 'profession', 'profici', 'profil', 'profit', 'program', 'programm', 'progress', 'project', 'promis', 'proof', 'properti', 'prophet', 'propos', 'protect', 'provid', 'prune', 'publish', 'pune', 'pursu', 'pvt', 'pyspark', 'python', 'pythonist', 'pytorch', 'qa', 'qualif', 'qualiti', 'queri', 'quick', 'r', 'rachel', 'rais', 'random', 'rasa', 'rate', 'reach', 'reaction', 'reactj', 'readi', 'real', 'realli', 'realtim', 'reason', 'recent', 'recognit', 'recommend', 'record', 'redshift', 'reduc', 'refin', 'regress', 'regular', 'reinforc', 'relat', 'relationship', 'report', 'represent', 'requir', 'research', 'respons', 'rest', 'restapi', 'restor', 'result', 'retriev', 'reward', 'rich', 'right', 'risk', 'rm', 'rnn', 'rnt', 'robert', 'robot', 'rodriguez', 'role', 'rooftop', 'rubi', 'ryan', 'sa', 'saa', 'safe', 'safeti', 'sagemak', 'sai', 'sail', 'sailpoint', 'sale', 'salesforc', 'sampl', 'sanghvi', 'sap', 'sapc', 'satisfact', 'scala', 'scalabl', 'scale', 'scanner', 'scenario', 'schedul', 'school', 'scienc', 'scientist', 'scikit', 'scope', 'scorecard', 'scott', 'scratch', 'script', 'sde', 'sdlc', 'seaborn', 'search', 'sector', 'secur', 'seek', 'segment', 'select', 'semiconductor', 'sen', 'send', 'senior', 'sensor', 'sentenc', 'sentiment', 'sep', 'sergey', 'seri', 'servic', 'set', 'seth', 'sever', 'sgg', 'sgn', 'shang', 'share', 'sher', 'shivaji', 'short', 'shri', 'side', 'sighania', 'silnivesh', 'simon', 'simplifi', 'simul', 'simultan', 'singh', 'singhji', 'sit', 'size', 'skil', 'skill', 'small', 'smaller', 'smart', 'smartphon', 'sme', 'smile', 'smv', 'softwar', 'soh', 'solapur', 'solut', 'solv', 'sophist', 'sorter', 'sound', 'sourc', 'space', 'spaci', 'span', 'spark', 'sparkocr', 'special', 'specialist', 'specif', 'splice', 'spp', 'spsc', 'spss', 'sql', 'srd', 'sri', 'ssm', 'stack', 'stakehold', 'stanford', 'start', 'stat', 'statement', 'statist', 'steel', 'stem', 'stori', 'strateg', 'strategi', 'strive', 'strong', 'structur', 'student', 'studi', 'subject', 'succeed', 'success', 'suggest', 'suion', 'summar', 'summari', 'supervis', 'suppli', 'support', 'survey', 'svm', 'svn', 'svu', 'swaroop', 'switch', 'symbiosi', 'synthes', 'system', 'systemdm', 'tabl', 'tableau', 'take', 'taken', 'tanner', 'target', 'task', 'tat', 'tata', 'teach', 'team', 'tech', 'technic', 'techniqu', 'technolog', 'telecommun', 'tender', 'tensoflow', 'tensorflow', 'tensorflowj', 'term', 'tessa', 'tesseract', 'test', 'testdom', 'text', 'texual', 'theft', 'thoma', 'thought', 'ti', 'til', 'till', 'time', 'timeseri', 'tirupati', 'tmlf', 'togeth', 'toler', 'tool', 'topic', 'tornado', 'torr', 'toubro', 'toward', 'toxic', 'track', 'tradit', 'traffic', 'train', 'traine', 'trainer', 'trait', 'transact', 'transform', 'transit', 'translat', 'trddc', 'tread', 'treatment', 'tree', 'trend', 'tri', 'ttr', 'tuc', 'type', 'u', 'udac', 'udemi', 'ui', 'uk', 'ukbas', 'understand', 'understood', 'unit', 'univers', 'unlabel', 'unstructur', 'unsupervis', 'usag', 'use', 'user', 'util', 'uttarpradesh', 'v', 'valid', 'valu', 'valuabl', 'valuat', 'variabl', 'varieti', 'variou', 'vast', 'vba', 'veget', 'vellor', 'venkateshwara', 'ventur', 'verdict', 'verifi', 'versatil', 'version', 'via', 'virendra', 'vision', 'visual', 'visualis', 'vit', 'von', 'voyageniu', 'vw', 'w', 'wafer', 'walchand', 'walker', 'want', 'warang', 'wareh', 'warehous', 'wasnt', 'watson', 'way', 'web', 'webscrap', 'websit', 'well', 'whether', 'white', 'whose', 'willfr', 'william', 'willing', 'windmil', 'within', 'wood', 'word', 'work', 'workday', 'workshop', 'would', 'wrangl', 'write', 'wrt', 'wsm', 'x', 'xml', 'yamamoto', 'year', 'yolo', 'young', 'zachari', 'zeal', 'zf', 'zigsaw']

      084  1  101  11  15  2  ...  year  yolo  young  zachari  zeal  zf  zigsaw
0  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
1  1    0  0    0   0   0  1  ...     0     0      0        0     0   0       0
2  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
3  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
4  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
5  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
6  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
7  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
8  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0
9  1    0  0    0   0   0  0  ...     0     0      0        0     0   0       0

[10 rows x 1410 columns]

In [266]:
X_counts_df['Match Percentage']=train['Match Percentage']

In [267]:
x=X_counts_df.drop(columns=['Match Percentage'])
y=X_counts_df['Match Percentage']
z=X_counts_df_test

In [268]:
l=[]
for i in x.columns:
  if i in z.columns:
    l.append(i)
x=x[l]
z=z[l]

In [269]:
import xgboost as xgb
xgb_regressor = xgb.XGBRegressor()
xgb_regressor.fit(x,y)
xgb_predict=xgb_regressor.predict(z)

[06:01:06] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [270]:
xgb_predict

array([17.531214, 49.04869 , 29.175745, 39.19922 , 45.38302 , 30.745708,
       41.396816, 30.482714, 34.664642, 40.868824, 38.94647 , 43.924614,
       34.70681 , 39.020714, 36.53667 , 18.411837, 50.6339  , 44.791313,
       31.229916, 39.235367, 39.94464 , 44.983814, 41.926025, 43.58412 ,
       25.414873, 46.332134, 49.657795, 44.328987, 33.99149 , 35.99663 ,
       52.365604, 31.501728, 46.556755, 42.583706, 42.719894, 39.98822 ,
       39.520283, 41.97976 , 40.12794 , 47.43019 , 40.354126, 33.26913 ,
       49.21108 , 31.7441  , 31.941103, 38.142   , 45.762737, 46.717464,
       46.429684, 48.763557, 19.35018 , 35.299732, 43.39396 , 26.88012 ,
       40.10051 , 39.905746, 44.39228 , 40.584324, 48.080357, 42.894543],
      dtype=float32)

In [271]:
final_df=test.copy()

In [272]:
final_test_primary_original

      CandidateID
0   candidate_014
1   candidate_098
2   candidate_075
3   candidate_016
4   candidate_131
5   candidate_056
6   candidate_141
7   candidate_044
8   candidate_029
9   candidate_120
10  candidate_094
11  candidate_005
12  candidate_102
13  candidate_051
14  candidate_078
15  candidate_042
16  candidate_092
17  candidate_066
18  candidate_031
19  candidate_035
20  candidate_090
21  candidate_084
22  candidate_077
23  candidate_040
24  candidate_125
25  candidate_099
26  candidate_033
27  candidate_019
28  candidate_073
29  candidate_146
30  candidate_091
31  candidate_135
32  candidate_069
33  candidate_128
34  candidate_114
35  candidate_048
36  candidate_053
37  candidate_028
38  candidate_054
39  candidate_108
40  candidate_112
41  candidate_017
42  candidate_119
43  candidate_103
44  candidate_058
45  candidate_118
46  candidate_018
47  candidate_004
48  candidate_045
49  candidate_059
50  candidate_039
51  candidate_036
52  candidate_117
53  candidate_139
54  candidate_107
55  candidate_132
56  candidate_126
57  candidate_085
58  candidate_122
59  candidate_095

In [273]:
test=test.sort_values('CandidateID').reset_index(drop=True)

In [274]:
test['Match Percentage']=xgb_predict
test

      CandidateID  Match Percentage
0   candidate_004         17.531214
1   candidate_005         49.048691
2   candidate_014         29.175745
3   candidate_016         39.199219
4   candidate_017         45.383018
5   candidate_018         30.745708
6   candidate_019         41.396816
7   candidate_028         30.482714
8   candidate_029         34.664642
9   candidate_031         40.868824
10  candidate_033         38.946468
11  candidate_035         43.924614
12  candidate_036         34.706810
13  candidate_039         39.020714
14  candidate_040         36.536671
15  candidate_042         18.411837
16  candidate_044         50.633900
17  candidate_045         44.791313
18  candidate_048         31.229916
19  candidate_051         39.235367
20  candidate_053         39.944641
21  candidate_054         44.983814
22  candidate_056         41.926025
23  candidate_058         43.584122
24  candidate_059         25.414873
25  candidate_066         46.332134
26  candidate_069         49.657795
27  candidate_073         44.328987
28  candidate_075         33.991489
29  candidate_077         35.996632
30  candidate_078         52.365604
31  candidate_084         31.501728
32  candidate_085         46.556755
33  candidate_090         42.583706
34  candidate_091         42.719894
35  candidate_092         39.988220
36  candidate_094         39.520283
37  candidate_095         41.979759
38  candidate_098         40.127941
39  candidate_099         47.430191
40  candidate_102         40.354126
41  candidate_103         33.269131
42  candidate_107         49.211079
43  candidate_108         31.744101
44  candidate_112         31.941103
45  candidate_114         38.141998
46  candidate_117         45.762737
47  candidate_118         46.717464
48  candidate_119         46.429684
49  candidate_120         48.763557
50  candidate_122         19.350180
51  candidate_125         35.299732
52  candidate_126         43.393959
53  candidate_128         26.880119
54  candidate_131         40.100510
55  candidate_132         39.905746
56  candidate_135         44.392281
57  candidate_139         40.584324
58  candidate_141         48.080357
59  candidate_146         42.894543

In [275]:
last=pd.DataFrame(columns=['CandidateID','Match Percentage'])

In [276]:
for i in final_test_primary_original['CandidateID']:
  last=last.append(test[test['CandidateID'] == i],ignore_index=True)
last

      CandidateID  Match Percentage
0   candidate_014         29.175745
1   candidate_098         40.127941
2   candidate_075         33.991489
3   candidate_016         39.199219
4   candidate_131         40.100510
5   candidate_056         41.926025
6   candidate_141         48.080357
7   candidate_044         50.633900
8   candidate_029         34.664642
9   candidate_120         48.763557
10  candidate_094         39.520283
11  candidate_005         49.048691
12  candidate_102         40.354126
13  candidate_051         39.235367
14  candidate_078         52.365604
15  candidate_042         18.411837
16  candidate_092         39.988220
17  candidate_066         46.332134
18  candidate_031         40.868824
19  candidate_035         43.924614
20  candidate_090         42.583706
21  candidate_084         31.501728
22  candidate_077         35.996632
23  candidate_040         36.536671
24  candidate_125         35.299732
25  candidate_099         47.430191
26  candidate_033         38.946468
27  candidate_019         41.396816
28  candidate_073         44.328987
29  candidate_146         42.894543
30  candidate_091         42.719894
31  candidate_135         44.392281
32  candidate_069         49.657795
33  candidate_128         26.880119
34  candidate_114         38.141998
35  candidate_048         31.229916
36  candidate_053         39.944641
37  candidate_028         30.482714
38  candidate_054         44.983814
39  candidate_108         31.744101
40  candidate_112         31.941103
41  candidate_017         45.383018
42  candidate_119         46.429684
43  candidate_103         33.269131
44  candidate_058         43.584122
45  candidate_118         46.717464
46  candidate_018         30.745708
47  candidate_004         17.531214
48  candidate_045         44.791313
49  candidate_059         25.414873
50  candidate_039         39.020714
51  candidate_036         34.706810
52  candidate_117         45.762737
53  candidate_139         40.584324
54  candidate_107         49.211079
55  candidate_132         39.905746
56  candidate_126         43.393959
57  candidate_085         46.556755
58  candidate_122         19.350180
59  candidate_095         41.979759

In [277]:
last.to_csv("final.csv",index=False)

In [278]:
!pip install catboost
import catboost as ctb
cat = ctb.CatBoostRegressor()
cat.fit(x,y)
cat_predict=cat.predict(z)

Requirement already satisfied: catboost in /usr/local/lib/python3.7/dist-packages (0.26.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Learning rate set to 0.025425
0:	learn: 15.8564347	total: 4.63ms	remaining: 4.63s
1:	learn: 15.7590763	total: 8.55ms	remaining: 4.27s
2:	learn: 15.6406376	total: 12.7ms	remaining: 4.21s
3:	learn: 15.5187819	total: 16.8ms	remaining: 4.17s
4:	learn: 15.3970026	total: 20.8ms	remaining: 4.13s
5:	learn: 15.3216333	total: 24.8ms	remaining: 4.11s
6:	learn: 15.2094465	total: 28.7ms	remaining: 4.07s
7:	learn: 15.1026622	total: 32.8ms	remaining: 4.06s
8:	learn: 14.9767661	total: 36.7ms	remaining: 4.04s
9:	learn: 14.8704994	total: 40.5ms	remaining: 4.01s
10:	learn: 14.7911561	total: 44.5ms	remaining: 4s
11:	learn: 14.7515310	total: 46.2ms	remaining: 3.8s
12:	learn: 14.6409367	total: 50.2ms	remaining: 3.81s
13:	learn: 14.5668657	total: 54.1ms	remaining: 3.81s
14:	learn: 14.4686373	total: 58.2ms	remaining: 3.82s
15:	learn: 14.3852875	total: 62.4ms	remaining: 3.84s
16:	learn: 14.2773768	total: 66.2ms	remaining: 3.83s
17:	learn: 14.2287278	total: 70ms	remaining: 3.82s
18:	learn: 14.1401423	total: 74ms	remaining: 3.82s
19:	learn: 14.0810931	total: 78.1ms	remaining: 3.83s
20:	learn: 14.0082543	total: 82ms	remaining: 3.83s
21:	learn: 13.9007941	total: 88.5ms	remaining: 3.93s
22:	learn: 13.8112001	total: 92.3ms	remaining: 3.92s
23:	learn: 13.7222270	total: 96.2ms	remaining: 3.91s
24:	learn: 13.5961230	total: 100ms	remaining: 3.9s
25:	learn: 13.5142564	total: 104ms	remaining: 3.9s
26:	learn: 13.4145331	total: 108ms	remaining: 3.89s
27:	learn: 13.3126729	total: 112ms	remaining: 3.89s
28:	learn: 13.2227040	total: 121ms	remaining: 4.05s
29:	learn: 13.1658431	total: 127ms	remaining: 4.12s
30:	learn: 13.0845119	total: 131ms	remaining: 4.1s
31:	learn: 13.0137797	total: 135ms	remaining: 4.09s
32:	learn: 12.9387939	total: 139ms	remaining: 4.08s
33:	learn: 12.8833092	total: 143ms	remaining: 4.07s
34:	learn: 12.7933604	total: 147ms	remaining: 4.06s
35:	learn: 12.7252569	total: 150ms	remaining: 4.02s
36:	learn: 12.6535830	total: 154ms	remaining: 4.01s
37:	learn: 12.5615525	total: 158ms	remaining: 4s
38:	learn: 12.4826513	total: 162ms	remaining: 3.99s
39:	learn: 12.3951758	total: 166ms	remaining: 3.98s
40:	learn: 12.3276954	total: 170ms	remaining: 3.98s
41:	learn: 12.2594496	total: 174ms	remaining: 3.96s
42:	learn: 12.1774905	total: 179ms	remaining: 3.98s
43:	learn: 12.0966414	total: 183ms	remaining: 3.98s
44:	learn: 12.0060313	total: 187ms	remaining: 3.97s
45:	learn: 11.9738144	total: 191ms	remaining: 3.96s
46:	learn: 11.8781259	total: 198ms	remaining: 4.01s
47:	learn: 11.7876230	total: 206ms	remaining: 4.08s
48:	learn: 11.7511524	total: 210ms	remaining: 4.07s
49:	learn: 11.6646034	total: 214ms	remaining: 4.06s
50:	learn: 11.5500175	total: 218ms	remaining: 4.06s
51:	learn: 11.4660793	total: 222ms	remaining: 4.05s
52:	learn: 11.4014181	total: 226ms	remaining: 4.04s
53:	learn: 11.3214529	total: 230ms	remaining: 4.04s
54:	learn: 11.2507825	total: 235ms	remaining: 4.03s
55:	learn: 11.1835499	total: 239ms	remaining: 4.02s
56:	learn: 11.1209687	total: 243ms	remaining: 4.02s
57:	learn: 11.0674123	total: 247ms	remaining: 4.01s
58:	learn: 10.9947008	total: 251ms	remaining: 4s
59:	learn: 10.9481544	total: 255ms	remaining: 4s
60:	learn: 10.8620339	total: 259ms	remaining: 3.99s
61:	learn: 10.7803672	total: 263ms	remaining: 3.98s
62:	learn: 10.6953236	total: 267ms	remaining: 3.98s
63:	learn: 10.6367502	total: 272ms	remaining: 3.97s
64:	learn: 10.5590287	total: 276ms	remaining: 3.97s
65:	learn: 10.5052663	total: 280ms	remaining: 3.96s
66:	learn: 10.4265627	total: 284ms	remaining: 3.96s
67:	learn: 10.4006367	total: 288ms	remaining: 3.95s
68:	learn: 10.3586021	total: 292ms	remaining: 3.95s
69:	learn: 10.2802742	total: 297ms	remaining: 3.94s
70:	learn: 10.2068241	total: 301ms	remaining: 3.93s
71:	learn: 10.1533176	total: 305ms	remaining: 3.92s
72:	learn: 10.0744923	total: 309ms	remaining: 3.92s
73:	learn: 10.0246075	total: 313ms	remaining: 3.91s
74:	learn: 9.9635041	total: 317ms	remaining: 3.9s
75:	learn: 9.9068130	total: 321ms	remaining: 3.9s
76:	learn: 9.8553406	total: 325ms	remaining: 3.89s
77:	learn: 9.8235974	total: 329ms	remaining: 3.89s
78:	learn: 9.7478304	total: 333ms	remaining: 3.88s
79:	learn: 9.7030080	total: 337ms	remaining: 3.87s
80:	learn: 9.6630753	total: 341ms	remaining: 3.87s
81:	learn: 9.6054452	total: 345ms	remaining: 3.86s
82:	learn: 9.5476928	total: 349ms	remaining: 3.86s
83:	learn: 9.4734428	total: 353ms	remaining: 3.85s
84:	learn: 9.4138337	total: 357ms	remaining: 3.85s
85:	learn: 9.3512602	total: 361ms	remaining: 3.84s
86:	learn: 9.2934053	total: 366ms	remaining: 3.83s
87:	learn: 9.2316911	total: 370ms	remaining: 3.83s
88:	learn: 9.1553223	total: 374ms	remaining: 3.83s
89:	learn: 9.0881413	total: 378ms	remaining: 3.82s
90:	learn: 9.0381934	total: 382ms	remaining: 3.82s
91:	learn: 8.9868217	total: 386ms	remaining: 3.81s
92:	learn: 8.9291342	total: 390ms	remaining: 3.81s
93:	learn: 8.8956281	total: 396ms	remaining: 3.82s
94:	learn: 8.8536107	total: 402ms	remaining: 3.83s
95:	learn: 8.8049292	total: 406ms	remaining: 3.82s
96:	learn: 8.7642550	total: 410ms	remaining: 3.81s
97:	learn: 8.6996439	total: 414ms	remaining: 3.81s
98:	learn: 8.6366792	total: 418ms	remaining: 3.8s
99:	learn: 8.5754919	total: 422ms	remaining: 3.8s
100:	learn: 8.5290288	total: 426ms	remaining: 3.79s
101:	learn: 8.4667124	total: 430ms	remaining: 3.79s
102:	learn: 8.4238713	total: 434ms	remaining: 3.78s
103:	learn: 8.3418032	total: 438ms	remaining: 3.78s
104:	learn: 8.3168013	total: 443ms	remaining: 3.77s
105:	learn: 8.2787183	total: 446ms	remaining: 3.77s
106:	learn: 8.2481077	total: 451ms	remaining: 3.76s
107:	learn: 8.2248993	total: 454ms	remaining: 3.75s
108:	learn: 8.1551571	total: 458ms	remaining: 3.75s
109:	learn: 8.1078269	total: 462ms	remaining: 3.74s
110:	learn: 8.0548677	total: 466ms	remaining: 3.73s
111:	learn: 8.0231118	total: 470ms	remaining: 3.73s
112:	learn: 7.9634407	total: 474ms	remaining: 3.72s
113:	learn: 7.9351241	total: 478ms	remaining: 3.72s
114:	learn: 7.8883550	total: 482ms	remaining: 3.71s
115:	learn: 7.8543655	total: 486ms	remaining: 3.71s
116:	learn: 7.7972975	total: 490ms	remaining: 3.7s
117:	learn: 7.7692005	total: 494ms	remaining: 3.69s
118:	learn: 7.7350942	total: 498ms	remaining: 3.69s
119:	learn: 7.6950655	total: 502ms	remaining: 3.68s
120:	learn: 7.6435997	total: 506ms	remaining: 3.68s
121:	learn: 7.6158706	total: 510ms	remaining: 3.67s
122:	learn: 7.5985183	total: 514ms	remaining: 3.67s
123:	learn: 7.5601873	total: 517ms	remaining: 3.65s
124:	learn: 7.5195368	total: 521ms	remaining: 3.65s
125:	learn: 7.4746852	total: 525ms	remaining: 3.64s
126:	learn: 7.4388699	total: 529ms	remaining: 3.64s
127:	learn: 7.4005848	total: 533ms	remaining: 3.63s
128:	learn: 7.3633659	total: 537ms	remaining: 3.63s
129:	learn: 7.3237733	total: 541ms	remaining: 3.62s
130:	learn: 7.2809173	total: 548ms	remaining: 3.63s
131:	learn: 7.2368400	total: 554ms	remaining: 3.64s
132:	learn: 7.2178059	total: 558ms	remaining: 3.64s
133:	learn: 7.1780652	total: 562ms	remaining: 3.63s
134:	learn: 7.1514076	total: 566ms	remaining: 3.63s
135:	learn: 7.0967107	total: 570ms	remaining: 3.62s
136:	learn: 7.0581524	total: 575ms	remaining: 3.62s
137:	learn: 7.0293284	total: 579ms	remaining: 3.62s
138:	learn: 6.9726125	total: 583ms	remaining: 3.61s
139:	learn: 6.9295459	total: 587ms	remaining: 3.6s
140:	learn: 6.8998028	total: 591ms	remaining: 3.6s
141:	learn: 6.8629879	total: 599ms	remaining: 3.62s
142:	learn: 6.8353902	total: 604ms	remaining: 3.62s
143:	learn: 6.8179435	total: 608ms	remaining: 3.61s
144:	learn: 6.7820081	total: 612ms	remaining: 3.61s
145:	learn: 6.7456056	total: 616ms	remaining: 3.6s
146:	learn: 6.7101133	total: 620ms	remaining: 3.6s
147:	learn: 6.6746978	total: 624ms	remaining: 3.59s
148:	learn: 6.6470589	total: 628ms	remaining: 3.58s
149:	learn: 6.6210660	total: 632ms	remaining: 3.58s
150:	learn: 6.6090095	total: 636ms	remaining: 3.57s
151:	learn: 6.5722837	total: 640ms	remaining: 3.57s
152:	learn: 6.5360776	total: 644ms	remaining: 3.56s
153:	learn: 6.5109914	total: 648ms	remaining: 3.56s
154:	learn: 6.4685989	total: 652ms	remaining: 3.55s
155:	learn: 6.4210966	total: 656ms	remaining: 3.55s
156:	learn: 6.3906253	total: 660ms	remaining: 3.54s
157:	learn: 6.3406086	total: 664ms	remaining: 3.54s
158:	learn: 6.3115642	total: 670ms	remaining: 3.54s
159:	learn: 6.2883732	total: 674ms	remaining: 3.54s
160:	learn: 6.2655141	total: 678ms	remaining: 3.53s
161:	learn: 6.2110173	total: 682ms	remaining: 3.53s
162:	learn: 6.1841706	total: 686ms	remaining: 3.52s
163:	learn: 6.1598937	total: 690ms	remaining: 3.52s
164:	learn: 6.1485837	total: 694ms	remaining: 3.51s
165:	learn: 6.1042275	total: 698ms	remaining: 3.51s
166:	learn: 6.0770066	total: 702ms	remaining: 3.5s
167:	learn: 6.0342695	total: 706ms	remaining: 3.5s
168:	learn: 5.9971653	total: 710ms	remaining: 3.49s
169:	learn: 5.9649466	total: 714ms	remaining: 3.49s
170:	learn: 5.9400512	total: 718ms	remaining: 3.48s
171:	learn: 5.9046388	total: 722ms	remaining: 3.48s
172:	learn: 5.8642341	total: 726ms	remaining: 3.47s
173:	learn: 5.8290017	total: 730ms	remaining: 3.47s
174:	learn: 5.8118493	total: 734ms	remaining: 3.46s
175:	learn: 5.7673497	total: 738ms	remaining: 3.46s
176:	learn: 5.7253244	total: 743ms	remaining: 3.45s
177:	learn: 5.6977968	total: 747ms	remaining: 3.45s
178:	learn: 5.6568610	total: 751ms	remaining: 3.44s
179:	learn: 5.6131246	total: 755ms	remaining: 3.44s
180:	learn: 5.5858617	total: 759ms	remaining: 3.43s
181:	learn: 5.5668047	total: 763ms	remaining: 3.43s
182:	learn: 5.5334473	total: 767ms	remaining: 3.42s
183:	learn: 5.4913804	total: 771ms	remaining: 3.42s
184:	learn: 5.4538331	total: 775ms	remaining: 3.41s
185:	learn: 5.4271467	total: 779ms	remaining: 3.41s
186:	learn: 5.4024134	total: 783ms	remaining: 3.4s
187:	learn: 5.3782045	total: 787ms	remaining: 3.4s
188:	learn: 5.3507728	total: 791ms	remaining: 3.39s
189:	learn: 5.3274648	total: 802ms	remaining: 3.42s
190:	learn: 5.2859285	total: 807ms	remaining: 3.42s
191:	learn: 5.2508021	total: 811ms	remaining: 3.41s
192:	learn: 5.2290480	total: 815ms	remaining: 3.41s
193:	learn: 5.2028519	total: 819ms	remaining: 3.4s
194:	learn: 5.1644066	total: 823ms	remaining: 3.4s
195:	learn: 5.1296793	total: 827ms	remaining: 3.39s
196:	learn: 5.1141847	total: 831ms	remaining: 3.38s
197:	learn: 5.0823597	total: 835ms	remaining: 3.38s
198:	learn: 5.0464116	total: 839ms	remaining: 3.38s
199:	learn: 5.0195700	total: 843ms	remaining: 3.37s
200:	learn: 4.9867771	total: 847ms	remaining: 3.37s
201:	learn: 4.9537699	total: 853ms	remaining: 3.37s
202:	learn: 4.9238929	total: 860ms	remaining: 3.38s
203:	learn: 4.8955699	total: 866ms	remaining: 3.38s
204:	learn: 4.8589184	total: 870ms	remaining: 3.37s
205:	learn: 4.8218048	total: 874ms	remaining: 3.37s
206:	learn: 4.7834430	total: 878ms	remaining: 3.36s
207:	learn: 4.7500851	total: 882ms	remaining: 3.36s
208:	learn: 4.7238412	total: 886ms	remaining: 3.35s
209:	learn: 4.6867178	total: 890ms	remaining: 3.35s
210:	learn: 4.6626044	total: 894ms	remaining: 3.34s
211:	learn: 4.6388157	total: 898ms	remaining: 3.34s
212:	learn: 4.6133577	total: 902ms	remaining: 3.33s
213:	learn: 4.5806768	total: 911ms	remaining: 3.35s
214:	learn: 4.5521813	total: 918ms	remaining: 3.35s
215:	learn: 4.5305251	total: 922ms	remaining: 3.34s
216:	learn: 4.4942794	total: 925ms	remaining: 3.34s
217:	learn: 4.4635453	total: 929ms	remaining: 3.33s
218:	learn: 4.4339626	total: 933ms	remaining: 3.33s
219:	learn: 4.3934994	total: 938ms	remaining: 3.32s
220:	learn: 4.3795155	total: 941ms	remaining: 3.32s
221:	learn: 4.3538237	total: 945ms	remaining: 3.31s
222:	learn: 4.3081470	total: 949ms	remaining: 3.31s
223:	learn: 4.2791403	total: 953ms	remaining: 3.3s
224:	learn: 4.2431273	total: 958ms	remaining: 3.3s
225:	learn: 4.2199854	total: 962ms	remaining: 3.29s
226:	learn: 4.1911619	total: 966ms	remaining: 3.29s
227:	learn: 4.1696754	total: 969ms	remaining: 3.28s
228:	learn: 4.1370836	total: 973ms	remaining: 3.28s
229:	learn: 4.1183200	total: 977ms	remaining: 3.27s
230:	learn: 4.1021410	total: 981ms	remaining: 3.27s
231:	learn: 4.0705431	total: 985ms	remaining: 3.26s
232:	learn: 4.0413608	total: 989ms	remaining: 3.26s
233:	learn: 4.0101009	total: 993ms	remaining: 3.25s
234:	learn: 3.9802957	total: 1s	remaining: 3.26s
235:	learn: 3.9591194	total: 1s	remaining: 3.25s
236:	learn: 3.9307639	total: 1.01s	remaining: 3.25s
237:	learn: 3.9164171	total: 1.01s	remaining: 3.25s
238:	learn: 3.8908168	total: 1.02s	remaining: 3.24s
239:	learn: 3.8753542	total: 1.02s	remaining: 3.23s
240:	learn: 3.8382615	total: 1.02s	remaining: 3.23s
241:	learn: 3.8157228	total: 1.03s	remaining: 3.22s
242:	learn: 3.7897955	total: 1.03s	remaining: 3.22s
243:	learn: 3.7548827	total: 1.04s	remaining: 3.21s
244:	learn: 3.7217608	total: 1.04s	remaining: 3.21s
245:	learn: 3.6957789	total: 1.04s	remaining: 3.2s
246:	learn: 3.6634628	total: 1.05s	remaining: 3.2s
247:	learn: 3.6411535	total: 1.05s	remaining: 3.19s
248:	learn: 3.6174519	total: 1.06s	remaining: 3.19s
249:	learn: 3.5863883	total: 1.06s	remaining: 3.18s
250:	learn: 3.5580167	total: 1.06s	remaining: 3.18s
251:	learn: 3.5352245	total: 1.07s	remaining: 3.17s
252:	learn: 3.5233976	total: 1.07s	remaining: 3.17s
253:	learn: 3.5087996	total: 1.08s	remaining: 3.16s
254:	learn: 3.4978365	total: 1.08s	remaining: 3.16s
255:	learn: 3.4842745	total: 1.08s	remaining: 3.15s
256:	learn: 3.4697570	total: 1.09s	remaining: 3.15s
257:	learn: 3.4444937	total: 1.09s	remaining: 3.14s
258:	learn: 3.4245028	total: 1.1s	remaining: 3.14s
259:	learn: 3.3963323	total: 1.1s	remaining: 3.13s
260:	learn: 3.3645014	total: 1.1s	remaining: 3.13s
261:	learn: 3.3428783	total: 1.11s	remaining: 3.12s
262:	learn: 3.3109174	total: 1.11s	remaining: 3.12s
263:	learn: 3.2896380	total: 1.12s	remaining: 3.11s
264:	learn: 3.2610522	total: 1.12s	remaining: 3.11s
265:	learn: 3.2363477	total: 1.13s	remaining: 3.1s
266:	learn: 3.2131485	total: 1.13s	remaining: 3.1s
267:	learn: 3.2003374	total: 1.13s	remaining: 3.1s
268:	learn: 3.1712991	total: 1.14s	remaining: 3.09s
269:	learn: 3.1605348	total: 1.14s	remaining: 3.08s
270:	learn: 3.1384366	total: 1.15s	remaining: 3.08s
271:	learn: 3.1137478	total: 1.15s	remaining: 3.08s
272:	learn: 3.1026536	total: 1.15s	remaining: 3.07s
273:	learn: 3.0746173	total: 1.16s	remaining: 3.07s
274:	learn: 3.0637782	total: 1.16s	remaining: 3.06s
275:	learn: 3.0503549	total: 1.17s	remaining: 3.06s
276:	learn: 3.0398295	total: 1.17s	remaining: 3.05s
277:	learn: 3.0260061	total: 1.17s	remaining: 3.05s
278:	learn: 3.0033155	total: 1.18s	remaining: 3.04s
279:	learn: 2.9769281	total: 1.18s	remaining: 3.04s
280:	learn: 2.9672172	total: 1.19s	remaining: 3.03s
281:	learn: 2.9425126	total: 1.19s	remaining: 3.03s
282:	learn: 2.9212498	total: 1.19s	remaining: 3.02s
283:	learn: 2.8953963	total: 1.2s	remaining: 3.03s
284:	learn: 2.8672011	total: 1.21s	remaining: 3.03s
285:	learn: 2.8589881	total: 1.21s	remaining: 3.02s
286:	learn: 2.8353443	total: 1.21s	remaining: 3.02s
287:	learn: 2.8262746	total: 1.22s	remaining: 3.01s
288:	learn: 2.8049405	total: 1.22s	remaining: 3.01s
289:	learn: 2.7945517	total: 1.23s	remaining: 3s
290:	learn: 2.7856434	total: 1.23s	remaining: 3s
291:	learn: 2.7769458	total: 1.23s	remaining: 2.99s
292:	learn: 2.7695504	total: 1.24s	remaining: 2.99s
293:	learn: 2.7456722	total: 1.24s	remaining: 2.98s
294:	learn: 2.7380206	total: 1.25s	remaining: 2.98s
295:	learn: 2.7302667	total: 1.25s	remaining: 2.98s
296:	learn: 2.7088563	total: 1.25s	remaining: 2.97s
297:	learn: 2.6852972	total: 1.26s	remaining: 2.97s
298:	learn: 2.6659553	total: 1.26s	remaining: 2.96s
299:	learn: 2.6580262	total: 1.27s	remaining: 2.96s
300:	learn: 2.6391183	total: 1.27s	remaining: 2.95s
301:	learn: 2.6181199	total: 1.27s	remaining: 2.95s
302:	learn: 2.5997201	total: 1.28s	remaining: 2.94s
303:	learn: 2.5869069	total: 1.28s	remaining: 2.94s
304:	learn: 2.5802356	total: 1.29s	remaining: 2.93s
305:	learn: 2.5614180	total: 1.29s	remaining: 2.93s
306:	learn: 2.5545483	total: 1.3s	remaining: 2.93s
307:	learn: 2.5468088	total: 1.3s	remaining: 2.92s
308:	learn: 2.5284303	total: 1.3s	remaining: 2.92s
309:	learn: 2.5211065	total: 1.31s	remaining: 2.91s
310:	learn: 2.5132503	total: 1.31s	remaining: 2.91s
311:	learn: 2.4940224	total: 1.32s	remaining: 2.9s
312:	learn: 2.4745173	total: 1.32s	remaining: 2.9s
313:	learn: 2.4574236	total: 1.32s	remaining: 2.9s
314:	learn: 2.4507193	total: 1.33s	remaining: 2.89s
315:	learn: 2.4450275	total: 1.33s	remaining: 2.89s
316:	learn: 2.4385347	total: 1.34s	remaining: 2.88s
317:	learn: 2.4253560	total: 1.34s	remaining: 2.88s
318:	learn: 2.4056618	total: 1.34s	remaining: 2.87s
319:	learn: 2.3867339	total: 1.35s	remaining: 2.87s
320:	learn: 2.3699475	total: 1.35s	remaining: 2.86s
321:	learn: 2.3614820	total: 1.36s	remaining: 2.86s
322:	learn: 2.3555322	total: 1.36s	remaining: 2.85s
323:	learn: 2.3391510	total: 1.36s	remaining: 2.85s
324:	learn: 2.3215890	total: 1.37s	remaining: 2.84s
325:	learn: 2.3091587	total: 1.37s	remaining: 2.84s
326:	learn: 2.2913650	total: 1.38s	remaining: 2.83s
327:	learn: 2.2858231	total: 1.38s	remaining: 2.83s
328:	learn: 2.2812758	total: 1.39s	remaining: 2.83s
329:	learn: 2.2758410	total: 1.39s	remaining: 2.82s
330:	learn: 2.2701012	total: 1.39s	remaining: 2.82s
331:	learn: 2.2527931	total: 1.4s	remaining: 2.82s
332:	learn: 2.2358307	total: 1.41s	remaining: 2.81s
333:	learn: 2.2302428	total: 1.41s	remaining: 2.81s
334:	learn: 2.2253293	total: 1.41s	remaining: 2.81s
335:	learn: 2.2193173	total: 1.42s	remaining: 2.8s
336:	learn: 2.2145159	total: 1.42s	remaining: 2.8s
337:	learn: 2.1961430	total: 1.43s	remaining: 2.79s
338:	learn: 2.1799720	total: 1.43s	remaining: 2.79s
339:	learn: 2.1690483	total: 1.43s	remaining: 2.78s
340:	learn: 2.1541141	total: 1.44s	remaining: 2.78s
341:	learn: 2.1488263	total: 1.44s	remaining: 2.77s
342:	learn: 2.1340055	total: 1.45s	remaining: 2.77s
343:	learn: 2.1166019	total: 1.45s	remaining: 2.77s
344:	learn: 2.1125240	total: 1.45s	remaining: 2.76s
345:	learn: 2.1073747	total: 1.46s	remaining: 2.76s
346:	learn: 2.0906259	total: 1.46s	remaining: 2.75s
347:	learn: 2.0866390	total: 1.47s	remaining: 2.75s
348:	learn: 2.0705947	total: 1.47s	remaining: 2.74s
349:	learn: 2.0652391	total: 1.47s	remaining: 2.74s
350:	learn: 2.0613425	total: 1.48s	remaining: 2.73s
351:	learn: 2.0458964	total: 1.48s	remaining: 2.73s
352:	learn: 2.0415927	total: 1.49s	remaining: 2.73s
353:	learn: 2.0378028	total: 1.49s	remaining: 2.72s

In [279]:
final_cat=final_df.copy()

In [280]:
final_cat=final_cat.sort_values('CandidateID').reset_index(drop=True)

In [281]:
final_cat['Match Percentage']=cat_predict
final_cat

      CandidateID  Match Percentage
0   candidate_004         18.741494
1   candidate_005         45.765044
2   candidate_014         30.431373
3   candidate_016         36.090257
4   candidate_017         42.665300
5   candidate_018         35.553706
6   candidate_019         39.679493
7   candidate_028         33.922962
8   candidate_029         32.532577
9   candidate_031         42.090038
10  candidate_033         41.586335
11  candidate_035         42.316475
12  candidate_036         38.686345
13  candidate_039         33.349949
14  candidate_040         32.800350
15  candidate_042         23.660854
16  candidate_044         47.408417
17  candidate_045         44.384516
18  candidate_048         36.373735
19  candidate_051         40.287446
20  candidate_053         41.669965
21  candidate_054         43.202856
22  candidate_056         37.560979
23  candidate_058         33.878311
24  candidate_059         33.064689
25  candidate_066         40.546118
26  candidate_069         47.500056
27  candidate_073         46.637549
28  candidate_075         36.378482
29  candidate_077         32.670990
30  candidate_078         53.690858
31  candidate_084         34.003548
32  candidate_085         44.923611
33  candidate_090         40.248811
34  candidate_091         41.867518
35  candidate_092         31.987744
36  candidate_094         39.122518
37  candidate_095         41.057376
38  candidate_098         37.473603
39  candidate_099         42.387009
40  candidate_102         35.698382
41  candidate_103         35.364875
42  candidate_107         40.025073
43  candidate_108         26.996618
44  candidate_112         34.758236
45  candidate_114         34.873223
46  candidate_117         46.614276
47  candidate_118         49.175094
48  candidate_119         48.330914
49  candidate_120         46.794719
50  candidate_122         28.443770
51  candidate_125         33.493722
52  candidate_126         41.376982
53  candidate_128         27.460665
54  candidate_131         41.519179
55  candidate_132         32.962089
56  candidate_135         42.380051
57  candidate_139         38.580145
58  candidate_141         43.858676
59  candidate_146         44.819184

In [282]:
last_cat_frame=pd.DataFrame(columns=['CandidateID','Match Percentage'])

In [283]:
for i in final_test_primary_original['CandidateID']:
  print(final_cat[final_cat['CandidateID'] == i])
  last_cat_frame=last.append(final_cat[final_cat['CandidateID'] == i],ignore_index=True)
last_cat_frame=last_cat_frame.drop([last_cat_frame.index[59]])
last_cat_frame

     CandidateID  Match Percentage
2  candidate_014         30.431373
      CandidateID  Match Percentage
38  candidate_098         37.473603
      CandidateID  Match Percentage
28  candidate_075         36.378482
     CandidateID  Match Percentage
3  candidate_016         36.090257
      CandidateID  Match Percentage
54  candidate_131         41.519179
      CandidateID  Match Percentage
22  candidate_056         37.560979
      CandidateID  Match Percentage
58  candidate_141         43.858676
      CandidateID  Match Percentage
16  candidate_044         47.408417
     CandidateID  Match Percentage
8  candidate_029         32.532577
      CandidateID  Match Percentage
49  candidate_120         46.794719
      CandidateID  Match Percentage
36  candidate_094         39.122518
     CandidateID  Match Percentage
1  candidate_005         45.765044
      CandidateID  Match Percentage
40  candidate_102         35.698382
      CandidateID  Match Percentage
19  candidate_051         40.287446
      CandidateID  Match Percentage
30  candidate_078         53.690858
      CandidateID  Match Percentage
15  candidate_042         23.660854
      CandidateID  Match Percentage
35  candidate_092         31.987744
      CandidateID  Match Percentage
25  candidate_066         40.546118
     CandidateID  Match Percentage
9  candidate_031         42.090038
      CandidateID  Match Percentage
11  candidate_035         42.316475
      CandidateID  Match Percentage
33  candidate_090         40.248811
      CandidateID  Match Percentage
31  candidate_084         34.003548
      CandidateID  Match Percentage
29  candidate_077          32.67099
      CandidateID  Match Percentage
14  candidate_040          32.80035
      CandidateID  Match Percentage
51  candidate_125         33.493722
      CandidateID  Match Percentage
39  candidate_099         42.387009
      CandidateID  Match Percentage
10  candidate_033         41.586335
     CandidateID  Match Percentage
6  candidate_019         39.679493
      CandidateID  Match Percentage
27  candidate_073         46.637549
      CandidateID  Match Percentage
59  candidate_146         44.819184
      CandidateID  Match Percentage
34  candidate_091         41.867518
      CandidateID  Match Percentage
56  candidate_135         42.380051
      CandidateID  Match Percentage
26  candidate_069         47.500056
      CandidateID  Match Percentage
53  candidate_128         27.460665
      CandidateID  Match Percentage
45  candidate_114         34.873223
      CandidateID  Match Percentage
18  candidate_048         36.373735
      CandidateID  Match Percentage
20  candidate_053         41.669965
     CandidateID  Match Percentage
7  candidate_028         33.922962
      CandidateID  Match Percentage
21  candidate_054         43.202856
      CandidateID  Match Percentage
43  candidate_108         26.996618
      CandidateID  Match Percentage
44  candidate_112         34.758236
     CandidateID  Match Percentage
4  candidate_017           42.6653
      CandidateID  Match Percentage
48  candidate_119         48.330914
      CandidateID  Match Percentage
41  candidate_103         35.364875
      CandidateID  Match Percentage
23  candidate_058         33.878311
      CandidateID  Match Percentage
47  candidate_118         49.175094
     CandidateID  Match Percentage
5  candidate_018         35.553706
     CandidateID  Match Percentage
0  candidate_004         18.741494
      CandidateID  Match Percentage
17  candidate_045         44.384516
      CandidateID  Match Percentage
24  candidate_059         33.064689
      CandidateID  Match Percentage
13  candidate_039         33.349949
      CandidateID  Match Percentage
12  candidate_036         38.686345
      CandidateID  Match Percentage
46  candidate_117         46.614276
      CandidateID  Match Percentage
57  candidate_139         38.580145
      CandidateID  Match Percentage
42  candidate_107         40.025073
      CandidateID  Match Percentage
55  candidate_132         32.962089
      CandidateID  Match Percentage
52  candidate_126         41.376982
      CandidateID  Match Percentage
32  candidate_085         44.923611
      CandidateID  Match Percentage
50  candidate_122          28.44377
      CandidateID  Match Percentage
37  candidate_095         41.057376

      CandidateID  Match Percentage
0   candidate_014         29.175745
1   candidate_098         40.127941
2   candidate_075         33.991489
3   candidate_016         39.199219
4   candidate_131         40.100510
5   candidate_056         41.926025
6   candidate_141         48.080357
7   candidate_044         50.633900
8   candidate_029         34.664642
9   candidate_120         48.763557
10  candidate_094         39.520283
11  candidate_005         49.048691
12  candidate_102         40.354126
13  candidate_051         39.235367
14  candidate_078         52.365604
15  candidate_042         18.411837
16  candidate_092         39.988220
17  candidate_066         46.332134
18  candidate_031         40.868824
19  candidate_035         43.924614
20  candidate_090         42.583706
21  candidate_084         31.501728
22  candidate_077         35.996632
23  candidate_040         36.536671
24  candidate_125         35.299732
25  candidate_099         47.430191
26  candidate_033         38.946468
27  candidate_019         41.396816
28  candidate_073         44.328987
29  candidate_146         42.894543
30  candidate_091         42.719894
31  candidate_135         44.392281
32  candidate_069         49.657795
33  candidate_128         26.880119
34  candidate_114         38.141998
35  candidate_048         31.229916
36  candidate_053         39.944641
37  candidate_028         30.482714
38  candidate_054         44.983814
39  candidate_108         31.744101
40  candidate_112         31.941103
41  candidate_017         45.383018
42  candidate_119         46.429684
43  candidate_103         33.269131
44  candidate_058         43.584122
45  candidate_118         46.717464
46  candidate_018         30.745708
47  candidate_004         17.531214
48  candidate_045         44.791313
49  candidate_059         25.414873
50  candidate_039         39.020714
51  candidate_036         34.706810
52  candidate_117         45.762737
53  candidate_139         40.584324
54  candidate_107         49.211079
55  candidate_132         39.905746
56  candidate_126         43.393959
57  candidate_085         46.556755
58  candidate_122         19.350180
60  candidate_095         41.057376

In [284]:
last_cat_frame.to_csv("final_cat.csv",index=False)

In [285]:
final_train_primary

      CandidateID  ... Match Percentage
0   candidate_000  ...            13.60
1   candidate_001  ...            36.63
2   candidate_002  ...            54.93
3   candidate_003  ...            41.46
4   candidate_006  ...            48.91
..            ...  ...              ...
85  candidate_144  ...            54.20
86  candidate_145  ...            60.18
87  candidate_147  ...            44.94
88  candidate_148  ...            11.41
89  candidate_149  ...            56.70

[90 rows x 3 columns]

In [286]:
final_test_primary_original

      CandidateID
0   candidate_014
1   candidate_098
2   candidate_075
3   candidate_016
4   candidate_131
5   candidate_056
6   candidate_141
7   candidate_044
8   candidate_029
9   candidate_120
10  candidate_094
11  candidate_005
12  candidate_102
13  candidate_051
14  candidate_078
15  candidate_042
16  candidate_092
17  candidate_066
18  candidate_031
19  candidate_035
20  candidate_090
21  candidate_084
22  candidate_077
23  candidate_040
24  candidate_125
25  candidate_099
26  candidate_033
27  candidate_019
28  candidate_073
29  candidate_146
30  candidate_091
31  candidate_135
32  candidate_069
33  candidate_128
34  candidate_114
35  candidate_048
36  candidate_053
37  candidate_028
38  candidate_054
39  candidate_108
40  candidate_112
41  candidate_017
42  candidate_119
43  candidate_103
44  candidate_058
45  candidate_118
46  candidate_018
47  candidate_004
48  candidate_045
49  candidate_059
50  candidate_039
51  candidate_036
52  candidate_117
53  candidate_139
54  candidate_107
55  candidate_132
56  candidate_126
57  candidate_085
58  candidate_122
59  candidate_095

In [287]:
final_test_primary=final_test_primary.sort_values('CandidateID').reset_index(drop=True)
final_test_primary

      CandidateID                                                                                               resume
0   candidate_004    O L I V I A  S A N T O S CONSULTANT ANALYST  WORK EXPERIENCE  Cognizant, Apr 2020 - Ongoing  C...
1   candidate_005    ARMIN FITZGERALD  D A  T  A   M  A  N  A  G  E  R  PROFESSIONAL PROFILE  Expertise in Mathemat...
2   candidate_014    GRACE BAILRY M A C H I N E  L E A R N I N G  D E V E L O P M E N T  A N D  D E P L O Y M E N T...
3   candidate_016    A M E L I A  M A R T I N DATA SCIENCE MAJOR  WORK EXPERIENCE  NA  ACADEMIC PROFILE  B.Tech(Com...
4   candidate_017    P R O F I L E  I am a Junior Machine Learning developer who focuses on data  improvement and m...
5   candidate_018    EVELYNN ADAMS  G R A D U A T E  F R E S H E R  PROFESSIONAL PROFILE  I am a recent graduate wh...
6   candidate_019    JOSHUA WHITE A S S I S T A N T  S O F T W A R E  A N D  M A C H I N E  L E A R N I N G  E N G ...
7   candidate_028    ASI Technologies  Intern,  Dec 2020 - Ongoing  Working as an intern to learn the usage of Neur...
8   candidate_029    Eli Scott F R E SHER  Executive Profile  Seeking challenging opportunity in the field of data ...
9   candidate_031    P R O F I L E  An avid explorer of analytics in multiple facets pertaining to  production indu...
10  candidate_033    CHARLES RODRIGUEZ S O F T W A R E  A N D  P R O J E C T  M A N A G E R  SKILLS  Natural Langua...
11  candidate_035    CISCO  Software Developer and Analyst Trainee OCT 2018 - May 2019    Developed Async Functions...
12  candidate_036    James May F R E S H E R  S O F T W A R E  D E V E L O P E R  E N G I N E E R  Executive Profil...
13  candidate_039    NICOLE BREWER  P O S T  G R A D U A T E  B U S I N E S S A N A L Y S T  PROFESSIONAL PROFILE  ...
14  candidate_040    ETHAN GARCIA F R E S H E R  D E V E L O P E R  E N G I N E E R  SKILLS  C++, Python, C, Softwa...
15  candidate_042    Ryan Nelson F R E S H E R  S O F T W A R E  D E V E L O P E R    Executive Profile  I consider...
16  candidate_044    L E A H  A T K I N JUNIOR DEVELOPER  WORK EXPERIENCE  TRDDC  Junior Developer, Jan 2019- till ...
17  candidate_045    P R O F I L E  Young Aspirant looking for roles in data science , analytics and  Machine Learn...
18  candidate_048    Absolutdata Research & Analytics  Machine Learning Intern, Jan 2020 to Till Date   Implemented...
19  candidate_051    S O P H I A  F L O R E S MACHINE LEARNING DEVELOPER(NLP)  WORK EXPERIENCE  eLevaTe LtD.  Machi...
20  candidate_053    PENELOPE TORRES  G R A D U T E  R E S E A R C H  F E L L O W  PROFESSIONAL PROFILE  Passionate...
21  candidate_054    SETH HALL D A T A  S C I E N T I S T  A N D  D E V E L O P E R  SKILLS  Data Scientist, Machin...
22  candidate_056    Christian Von Kelin J U N I O R  A N A L Y S T  Executive Profile  As a junior analyst I curre...
23  candidate_058    S E B A S T I A N  G O L E R ASSOCIATE DATA MANAGER  WORK EXPERIENCE  iNyra Nursing Home  Asso...
24  candidate_059    P R O F I L E  An eclectic researcher , with adept creativity in mobilizing thoughts to  words...
25  candidate_066    HILDA HAWTHORN  P R O F I L E Associate Software Engineer experienced with data  handling and ...
26  candidate_069    RACHEL DAWN D A T A  S C I E N T I S T  SKILLS  Deep learning, Python, SQL , Keras, PyTorch, P...
27  candidate_073    P R O F I L E  I am a junior developer currently working as a Machine Learning  Engineer. I ma...
28  candidate_075    KEIRON PAVARD D A T A  E N G I N E E R  SKILLS  Data Engineer, Data Analytics , Data Visualiza...
29  candidate_077    Benett Campbell F R E S H E R  D A T A  A N A L Y S T  Executive Profile  I am fresher data an...
30  candidate_078    DOMINIC NEIWHALD  P R O F I L E Fresher who is dynamic and defined when it comes to  domain kn...
31  candidate_084    Robert Sergey F R E SHER  Executive Profile  I recently graduated with a B.Tech degree in IT a...
32  candidate_085    HARRY MILES  P R O F I L E Industrious and collaborative individual, Currently looking  for an...
33  candidate_090    DTSl Software Services  Associate Data Engineer, Jul 2019 - Ongoing   Synthesized current busi...
34  candidate_091    CASH FLORES  P R O F I L E Machine learning Enthusiast. Motivated to learn, grow and  excel my...
35  candidate_092    Aya Baker G R A D U A T E  S D E  A N D  B U S I N E S S  A N A L Y S T  Executive Profile  Lo...
36  candidate_094    P R O F I L E  Graduate Looking for roles related to BU analyst and machine  learning.  CDX IN...
37  candidate_095    ERIC MILROY  S Y S T E M  E N G I N E E R  A N D  A N A L Y S T  PROFESSIONAL PROFILE  Versati...
38  candidate_098    VoyaGenius Labs  Software Developer (ML), Dec 2018 - Ongoing   Geocoding and detecting rooftop...
39  candidate_099    Edison Anys M A C H I N E  L E A R N I N G  E N G I N E E R  Executive Profile  Machine Learni...
40  candidate_102    TANNER WILLIAMS  S O L U T I O N S  E N G I N E E R  PROFESSIONAL PROFILE  I am currently work...
41  candidate_103    TESSA MAERS  P R O F I L E A strategic analyst whose skil l  spans over a vast array of  exper...
42  candidate_107    A N D O R A  M C C O N N E L DATA SCIENTIST  WORK EXPERIENCE  HP  Lead Data Scientist, Feb 202...
43  candidate_108    P R O F I L E  I am a fresher business analyst with a knack for building applications that use...
44  candidate_112    Loyalty Rewards Management. Pvt. Ltd.   Business Analyst, Aug 2020 to Till Date    Administeri...
45  candidate_114    G A R E T T E  P A I G E ASSOCIATE SOFTWARE ENGINEER  WORK EXPERIENCE  Delta Info-nancial Serv...
46  candidate_117    MAX LECLERC  P R O F I L E A Fresher Seeking Roles In Machine Learning, Business  Analysis, Da...
47  candidate_118    IRIS GAIDON D A T A  A N A L Y S T  SKILLS  Machine Learning, Data Mining, Artificial Intellig...
48  candidate_119    Willfred Dixon A S S O C I A T E  D A T A  A N A L Y S T  Executive Profile  Data analyst acti...
49  candidate_120    P R O F I L E  Completed BSc in STATISTICS from the Mumbai University . Completed data  scienc...
50  candidate_122    DIANA MILLER  R E S E A R C H  A S S I S T A N T ( M L )  PROFESSIONAL PROFILE  You can find m...
51  candidate_125    ETHAN HUNT P Y T H O N  D E V E L O P E R    SKILLS  Django, Python, Relational databases, Res...
52  candidate_126    Asher Hall D A T A  C O N S U L T A N T  Executive Profile  Interested in helping businesses t...
53  candidate_128    B E U L A  S M I T H S O N DATA ANALYST  WORK EXPERIENCE  Graphene health tech Pvt Ltd  BI Eng...
54  candidate_131    ZACHARY PEREZ  P R O F I L E Good knowledge of C++ and OOPS concepts. Good  knowledge of Data ...
55  candidate_132    DAVID PHIAST A P P L I C A T I O N  D E V E L O P E R  SKILLS  Deep Learning, Machine Learning...
56  candidate_135    KHOLE MOORE G R A D U A T E  R E S E A R C H E R  SKILLS  Machine Learning Engineer, Data Anal...
57  candidate_139    KEISUKE YAMAMOTO  P R O F I L E Professional with 3 months of experience in Web  Development a...
58  candidate_141    P R O F I L E  Software developer with a niche towards end to end machine learning projects . ...
59  candidate_146    LEHNA PATRICK  P R O F I L E I  have worked on grassroot level design of data based  models an...